{
  "hash": "1d7e3482106d2f8722114cf916eb855d",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Study 6: Advanced Velocity-RIR Analyses\"\nsubtitle: \"Novel Analyses for Velocity-Based Training Prescription\"\nauthor: \"Deadlift RIR-Velocity Research Team\"\ndate: today\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    code-fold: true\n    code-summary: \"Show code\"\n    theme: cosmo\n    fig-width: 10\n    fig-height: 6\nexecute:\n  warning: false\n  message: false\n---\n\n\n\n\n## Executive Summary\n\nThis study presents five novel analyses (H2-H6) that extend our understanding of the deadlift velocity-RIR relationship, addressing key gaps in the velocity-based training literature.\n\n### Key Findings\n\n| Analysis | Result | Practical Implication |\n|----------|--------|----------------------|\n| **H2: MVT Variability** | CV = 30.8% | Individual calibration essential |\n| **H3: Day Reliability** | Slope ICC = 0.72 | Periodic recalibration needed |\n| **H4: Model Comparison** | 26.3% prefer quadratic | Linear model adequate |\n| **H5: Velocity Decay** | Accelerates (p = 0.035) | Non-linear considerations |\n| **H6: Failure Prediction** | MAE = 1.29 reps | First rep velocity useful |\n\n## Experimental Setup\n\n### Study Design\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nParticipants: 19 \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTotal observations: 406 \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTotal sets: 74 \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReps per set: 1 - 8 (mean: 5.5 )\n```\n\n\n:::\n:::\n\n\n**Protocol:**\n\n- **Participants**: 19 resistance-trained individuals (15 male, 4 female)\n- **Exercise**: Conventional deadlift\n- **Loads**: 80% and 90% of 1RM\n- **Testing days**: 2 separate days\n- **Protocol**: Each participant performed sets to muscular failure at both loads on both days\n- **Measurement**: Mean concentric velocity (MCV) for each repetition using linear position transducer\n\n**Data Structure:**\n\nEach observation represents a single repetition within a set to failure:\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: Sample data structure (first 10 rows)\n\n|id        |day   |load_percentage |set_id                  | rep_number| rir| mean_velocity| reps_to_failure|\n|:---------|:-----|:---------------|:-----------------------|----------:|---:|-------------:|---------------:|\n|Sebastião |Day 1 |90%             |Sebastião_Day1_90pct_S1 |          1|   3|         0.333|               4|\n|Sebastião |Day 1 |90%             |Sebastião_Day1_90pct_S1 |          2|   2|         0.293|               4|\n|Sebastião |Day 1 |90%             |Sebastião_Day1_90pct_S1 |          3|   1|         0.235|               4|\n|Sebastião |Day 1 |90%             |Sebastião_Day1_90pct_S1 |          4|   0|         0.246|               4|\n|Sebastião |Day 1 |80%             |Sebastião_Day1_80pct_S2 |          1|   5|         0.398|               6|\n|Sebastião |Day 1 |80%             |Sebastião_Day1_80pct_S2 |          2|   4|         0.363|               6|\n|Sebastião |Day 1 |80%             |Sebastião_Day1_80pct_S2 |          3|   3|         0.386|               6|\n|Sebastião |Day 1 |80%             |Sebastião_Day1_80pct_S2 |          4|   2|         0.387|               6|\n|Sebastião |Day 1 |80%             |Sebastião_Day1_80pct_S2 |          5|   1|         0.325|               6|\n|Sebastião |Day 1 |80%             |Sebastião_Day1_80pct_S2 |          6|   0|         0.206|               6|\n\n\n:::\n:::\n\n\n## H2: Minimum Velocity Threshold (MVT) Variability\n\n### Research Question\n\n**How variable is the velocity at muscular failure (RIR=0) across individuals?**\n\n### Why This Matters\n\nThe Minimum Velocity Threshold (MVT) is the velocity at which an athlete reaches muscular failure. Understanding MVT variability has critical implications:\n\n- If MVT is consistent across individuals (~0.15-0.20 m/s for all), it could serve as a **universal failure indicator**\n- If MVT varies widely, **individual calibration is essential** before using velocity-based prescriptions\n- Practical question: Can coaches use a single \"stop velocity\" for all athletes?\n\n### Methods\n\n1. Extracted all observations at RIR = 0 (failure reps)\n2. Calculated population-level MVT statistics (mean, SD, CV, IQR)\n3. Calculated individual MVT for each participant\n4. Tested for sex differences using Mann-Whitney U test\n5. Tested for load differences (80% vs 90%) using paired comparison\n\n### Results\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nPopulation MVT Statistics:\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Mean: 0.206 m/s\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  SD: 0.063 m/s\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  CV: 30.8 %\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  IQR: 0.082 m/s\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Range: 0.119 - 0.402 m/s\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Extract failure data\nfailure_data <- data[data$rir == 0, ]\n\n# Density plot\nggplot(failure_data, aes(x = mean_velocity)) +\n  geom_histogram(aes(y = after_stat(density)), bins = 20, fill = \"steelblue\", alpha = 0.7) +\n  geom_density(color = \"darkred\", linewidth = 1) +\n  geom_vline(xintercept = mvt_result$population_stats$mean,\n             linetype = \"dashed\", color = \"black\", linewidth = 1) +\n  annotate(\"text\", x = mvt_result$population_stats$mean + 0.02, y = 5,\n           label = paste(\"Mean =\", round(mvt_result$population_stats$mean, 3), \"m/s\"),\n           hjust = 0) +\n  labs(x = \"Velocity at Failure (m/s)\", y = \"Density\",\n       title = \"MVT Distribution Across All Failure Observations\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![Distribution of Minimum Velocity Threshold (MVT) at failure](06_advanced_velocity_analyses_files/figure-html/h2-plot-1.png){width=960}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Individual MVT plot\nind_mvt <- mvt_result$individual_stats\nind_mvt <- ind_mvt[order(ind_mvt$mean_mvt), ]\nind_mvt$id <- factor(ind_mvt$id, levels = ind_mvt$id)\n\nggplot(ind_mvt, aes(x = id, y = mean_mvt, color = sex)) +\n  geom_point(size = 3) +\n  geom_errorbar(aes(ymin = mean_mvt - sd_mvt, ymax = mean_mvt + sd_mvt),\n                width = 0.3) +\n  geom_hline(yintercept = mvt_result$population_stats$mean,\n             linetype = \"dashed\", color = \"gray50\") +\n  coord_flip() +\n  labs(x = \"Participant\", y = \"MVT (m/s)\",\n       title = \"Individual MVT with Standard Deviation\",\n       color = \"Sex\") +\n  scale_color_manual(values = c(\"female\" = \"#E41A1C\", \"male\" = \"#377EB8\")) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![Individual MVT values showing between-participant variability](06_advanced_velocity_analyses_files/figure-html/h2-individual-1.png){width=960}\n:::\n:::\n\n\n**Load Comparison:**\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n80% 1RM MVT: 0.217 ± 0.066 m/s\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n90% 1RM MVT: 0.196 ± 0.061 m/s\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDifference: 0.021 m/s\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\np-value: 0.148 \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSignificant: FALSE \n```\n\n\n:::\n:::\n\n\n### Interpretation\n\nThe coefficient of variation (CV = 30.8%) indicates **high inter-individual variability** in MVT. This finding has important practical implications:\n\n1. **A single MVT value cannot be applied to all athletes** - using a population mean (0.21 m/s) would underestimate capacity for some and overshoot for others\n2. **Individual calibration is essential** - each athlete needs their own MVT determined through testing to failure\n3. **No significant load effect** - MVT appears similar at 80% and 90% 1RM, suggesting MVT is an individual characteristic independent of load\n\n## H3: Day-to-Day Reliability\n\n### Research Question\n\n**Are individual velocity-RIR relationships stable across testing days?**\n\n### Why This Matters\n\nIf velocity profiles are reliable day-to-day:\n- A **single calibration session is sufficient** to establish individual velocity zones\n- Athletes don't need frequent retesting\n\nIf velocity profiles are unreliable:\n- Athletes need **frequent recalibration** (perhaps weekly or monthly)\n- Session-to-session factors (fatigue, recovery, motivation) may affect velocity targets\n\n### Methods\n\n1. Fit individual linear models (velocity ~ RIR) for Day 1 and Day 2 separately\n2. Extract slopes (velocity loss per RIR) and intercepts (baseline velocity)\n3. Calculate MVT predictions for each day (predicted velocity at RIR = 0)\n4. Compute ICC(2,1) - two-way random effects model\n5. Calculate SEM (Standard Error of Measurement) and MDC95 (Minimal Detectable Change)\n\n**ICC Interpretation (Koo & Li, 2016):**\n\n| ICC | Interpretation |\n|-----|----------------|\n| < 0.50 | Poor |\n| 0.50-0.75 | Moderate |\n| 0.75-0.90 | Good |\n| > 0.90 | Excellent |\n\n### Results\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nSlope ICC (velocity loss per RIR):\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  ICC: 0.72 \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  95% CI: 0.644 - 0.796 \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Interpretation: Moderate \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMVT ICC (predicted failure velocity):\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  ICC: 0.498 \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  95% CI: 0.379 - 0.617 \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Interpretation: Poor \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  SEM: 0.024 m/s\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  MDC95: 0.0666 m/s\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nday_params <- reliability$day_parameters\n\n# Slopes comparison\nggplot(day_params, aes(x = slope_day1, y = slope_day2)) +\n  geom_point(size = 3, alpha = 0.7) +\n  geom_abline(slope = 1, intercept = 0, linetype = \"dashed\", color = \"gray50\") +\n  geom_smooth(method = \"lm\", se = TRUE, color = \"steelblue\") +\n  labs(x = \"Slope Day 1 (m/s per RIR)\", y = \"Slope Day 2 (m/s per RIR)\",\n       title = \"Day-to-Day Reliability of Individual Slopes\",\n       subtitle = paste(\"ICC =\", round(reliability$slope_icc$icc, 2))) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![Day 1 vs Day 2 comparison of individual slopes](06_advanced_velocity_analyses_files/figure-html/h3-plot-1.png){width=960}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(day_params, aes(x = mvt_day1, y = mvt_day2)) +\n  geom_point(size = 3, alpha = 0.7) +\n  geom_abline(slope = 1, intercept = 0, linetype = \"dashed\", color = \"gray50\") +\n  geom_smooth(method = \"lm\", se = TRUE, color = \"steelblue\") +\n  labs(x = \"MVT Day 1 (m/s)\", y = \"MVT Day 2 (m/s)\",\n       title = \"Day-to-Day Reliability of Predicted MVT\",\n       subtitle = paste(\"ICC =\", round(reliability$mvt_icc$icc, 2))) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![Day 1 vs Day 2 comparison of predicted MVT](06_advanced_velocity_analyses_files/figure-html/h3-mvt-plot-1.png){width=960}\n:::\n:::\n\n\n### Interpretation\n\n- **Slope reliability is moderate** (ICC = 0.72), suggesting the rate of velocity decline per RIR is reasonably consistent\n- **MVT reliability is poor** (ICC = 0.5), indicating that predicted failure velocity varies substantially between days\n- **MDC95 = 0.067 m/s** - changes in MVT smaller than this may represent measurement error rather than true change\n\n**Practical recommendation:** Consider periodic recalibration (every 2-4 weeks) rather than relying on a single test session.\n\n## H4: Polynomial vs Linear Model Comparison\n\n### Research Question\n\n**Does a quadratic model fit the velocity-RIR relationship better than linear?**\n\n### Why This Matters\n\n- **Linear assumption**: Velocity decreases at a constant rate with each rep (each rep costs the same velocity)\n- **Quadratic model**: Velocity loss accelerates near failure (fatigue compounds)\n\nIf quadratic is substantially better, this suggests:\n- The velocity-RIR relationship is non-linear\n- Simple linear velocity zones may underestimate proximity to failure in the final reps\n- Coaches should use curvilinear charts or adjust expectations near failure\n\n### Methods\n\n1. For each participant, fit:\n   - Linear: velocity ~ RIR\n   - Quadratic: velocity ~ RIR + RIR²\n2. Compare using adjusted R², AIC, and BIC\n3. Fit population-level LMM versions and conduct likelihood ratio test\n4. Count how many participants show significantly better fit with quadratic\n\n### Results\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nIndividual Model Comparison:\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Participants analyzed: 19 \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Linear preferred: 14 \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Quadratic preferred: 5 ( 26.3 %)\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Avg R² improvement (quad - linear): 0.0164 \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nind_results <- poly_result$individual_results\n\nggplot(ind_results, aes(x = reorder(id, delta_aic), y = delta_aic, fill = best_model)) +\n  geom_col() +\n  geom_hline(yintercept = -2, linetype = \"dashed\", color = \"red\") +\n  geom_hline(yintercept = 2, linetype = \"dashed\", color = \"red\") +\n  annotate(\"text\", x = 1, y = -3, label = \"Quadratic better\", hjust = 0, color = \"gray40\") +\n  annotate(\"text\", x = 1, y = 3, label = \"Linear better\", hjust = 0, color = \"gray40\") +\n  coord_flip() +\n  labs(x = \"Participant\", y = \"ΔAIC (Quadratic - Linear)\",\n       title = \"Model Comparison by Participant\",\n       subtitle = \"Negative values favor quadratic model\",\n       fill = \"Best Model\") +\n  scale_fill_manual(values = c(\"linear\" = \"steelblue\", \"quadratic\" = \"coral\")) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![AIC comparison between linear and quadratic models by participant](06_advanced_velocity_analyses_files/figure-html/h4-plot-1.png){width=960}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(ind_results, aes(x = r2_adj_linear, y = r2_adj_quad)) +\n  geom_point(aes(color = best_model), size = 3) +\n  geom_abline(slope = 1, intercept = 0, linetype = \"dashed\") +\n  labs(x = \"Adjusted R² (Linear)\", y = \"Adjusted R² (Quadratic)\",\n       title = \"Model Fit Comparison\",\n       color = \"Best Model\") +\n  scale_color_manual(values = c(\"linear\" = \"steelblue\", \"quadratic\" = \"coral\")) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![R² comparison between linear and quadratic models](06_advanced_velocity_analyses_files/figure-html/h4-r2-1.png){width=960}\n:::\n:::\n\n\n### Interpretation\n\nOnly 26.3% of participants show a meaningfully better fit with the quadratic model. This suggests:\n\n1. **Linear model is generally adequate** for describing the velocity-RIR relationship\n2. The additional complexity of a quadratic term is not justified for most individuals\n3. Practitioners can confidently use **linear velocity zones** for training prescription\n\n**Note:** While a minority of individuals may benefit from quadratic modeling, the linear approximation provides sufficient accuracy for practical applications.\n\n## H5: Velocity Decay Rate Within Sets\n\n### Research Question\n\n**How does velocity loss per rep change as a set progresses?**\n\n### Why This Matters\n\nUnderstanding velocity decay patterns informs:\n- **When to stop a set** - if decay accelerates, stopping earlier preserves movement quality\n- **Model selection** - constant decay supports linear models; accelerating decay suggests non-linear approaches\n- **Fatigue thresholds** - identifying the rep where decay sharply increases\n\n### Methods\n\n1. Calculate rep-to-rep velocity change (Δv = v_n - v_{n-1})\n2. Model decay rate vs rep number: Δv ~ rep_number\n3. Test if decay accelerates (negative slope = accelerating fatigue)\n4. Detect breakpoint where decay notably increases\n\n### Results\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nVelocity Decay Summary:\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Average decay per rep: -0.0283 m/s\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Early reps (1-3): -0.0206 m/s\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Late reps (4+): -0.0338 m/s\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Acceleration: -0.0132 m/s\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAcceleration Test:\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Slope: -0.00318 \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  p-value: 0.03495 \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Interpretation: Decay accelerates toward failure \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create spaghetti plot of velocity trajectories\nggplot(data, aes(x = rep_number, y = mean_velocity, group = set_id)) +\n  geom_line(alpha = 0.3, color = \"steelblue\") +\n  stat_summary(aes(group = 1), fun = mean, geom = \"line\",\n               color = \"darkred\", linewidth = 1.5) +\n  stat_summary(aes(group = 1), fun = mean, geom = \"point\",\n               color = \"darkred\", size = 3) +\n  labs(x = \"Rep Number\", y = \"Mean Velocity (m/s)\",\n       title = \"Velocity Trajectories Across Sets\",\n       subtitle = \"Individual sets (blue) with population mean (red)\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![Velocity trajectories for individual sets](06_advanced_velocity_analyses_files/figure-html/h5-trajectory-1.png){width=960}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Decay by rep number\ndecay_data <- decay$set_trajectories\n\nggplot(decay_data, aes(x = factor(rep_number), y = delta_v)) +\n  geom_boxplot(fill = \"steelblue\", alpha = 0.7) +\n  geom_hline(yintercept = 0, linetype = \"dashed\", color = \"gray50\") +\n  labs(x = \"Rep Number\", y = \"Velocity Change from Previous Rep (m/s)\",\n       title = \"Rep-to-Rep Velocity Change\",\n       subtitle = \"Negative values indicate velocity loss\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![Rep-to-rep velocity change by rep number](06_advanced_velocity_analyses_files/figure-html/h5-decay-1.png){width=960}\n:::\n:::\n\n\n### Interpretation\n\n**Velocity decay accelerates as the set progresses** (p = 0.035):\n\n- Early reps (1-3): Average decay = 20.6 mm/s per rep\n- Late reps (4+): Average decay = 33.8 mm/s per rep\n\nThis 13.2 mm/s acceleration in decay rate suggests:\n\n1. **Fatigue compounds near failure** - the last few reps cost more velocity than earlier reps\n2. **Velocity thresholds are conservative early** - athletes have more \"buffer\" in early reps\n3. **Quality deteriorates rapidly near failure** - this supports stopping 1-2 reps before failure for technique preservation\n\n## H6: Early Rep Velocity for Failure Prediction\n\n### Research Question\n\n**Can the first 1-3 rep velocities predict when failure will occur?**\n\n### Why This Matters\n\nThis is perhaps the most practically valuable analysis:\n- **Real-time autoregulation**: Predict total reps from the first rep velocity\n- **No rep counting needed**: Know when to stop based on velocity alone\n- **Pre-set planning**: Estimate how many reps are possible before starting\n\n### Methods\n\n1. For each set, extract: v1 (first rep velocity), v2, v3, and total reps\n2. Build prediction models:\n   - Model 1: reps ~ v1\n   - Model 2: reps ~ v1 + v2\n   - Model 3: reps ~ v1 + v2 + v3\n   - Model 4: reps ~ v1 + load\n3. Evaluate with leave-one-set-out cross-validation\n4. Create practical lookup table\n\n### Results\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nLeave-One-Set-Out Cross-Validation:\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Sets analyzed: 66 \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  MAE: 1.29 reps\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  RMSE: 1.53 reps\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  R²: 0.065 \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Within ±1 rep: 42.4 %\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Within ±2 reps: 75.8 %\n```\n\n\n:::\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: Practical Lookup Table: First Rep Velocity → Predicted Reps\n\n| First Rep Velocity (m/s)| Predicted Reps| Lower 95%| Upper 95%|\n|------------------------:|--------------:|---------:|---------:|\n|                      0.1|            4.9|       1.8|       8.0|\n|                      0.2|            5.2|       2.1|       8.3|\n|                      0.2|            5.4|       2.4|       8.5|\n|                      0.3|            5.7|       2.6|       8.7|\n|                      0.3|            6.0|       2.9|       9.0|\n|                      0.4|            6.2|       3.2|       9.3|\n|                      0.5|            6.5|       3.4|       9.6|\n|                      0.5|            6.8|       3.7|       9.9|\n|                      0.6|            7.0|       3.9|      10.2|\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Prepare set-level data\nset_data <- do.call(rbind, lapply(unique(data$set_id), function(sid) {\n  s <- data[data$set_id == sid, ]\n  s <- s[order(s$rep_number), ]\n  if (nrow(s) < 1) return(NULL)\n  data.frame(\n    set_id = sid,\n    v1 = s$mean_velocity[1],\n    reps_to_failure = s$reps_to_failure[1],\n    load_percentage = s$load_percentage[1]\n  )\n}))\n\nggplot(set_data, aes(x = v1, y = reps_to_failure, color = load_percentage)) +\n  geom_point(size = 3, alpha = 0.7) +\n  geom_smooth(method = \"lm\", se = TRUE, aes(group = 1), color = \"black\") +\n  labs(x = \"First Rep Velocity (m/s)\", y = \"Total Reps to Failure\",\n       title = \"Relationship Between First Rep Velocity and Set Capacity\",\n       color = \"Load\") +\n  scale_color_manual(values = c(\"80%\" = \"#E41A1C\", \"90%\" = \"#377EB8\")) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![First rep velocity vs total reps completed](06_advanced_velocity_analyses_files/figure-html/h6-plot-1.png){width=960}\n:::\n:::\n\n\n### Interpretation\n\nThe first rep velocity provides a **reasonable prediction of set capacity**:\n\n- **MAE = 1.29 reps** means predictions are typically within ~1 rep of actual\n- **75.8% accuracy within ±2 reps** is sufficient for practical autoregulation\n- **Each +0.1 m/s in first rep velocity → ~0.5 additional reps expected**\n\n**Practical Application:**\nUse the lookup table to estimate available reps from your first rep velocity. For example:\n- First rep at 0.30 m/s → Expect ~6 reps (95% PI: 3-9)\n- First rep at 0.45 m/s → Expect ~7 reps (95% PI: 3-10)\n\n## Practical Implications\n\n### Summary of Recommendations\n\n| Finding | Practical Recommendation |\n|---------|-------------------------|\n| High MVT variability (CV = 31%) | Calibrate MVT individually for each athlete |\n| Moderate slope reliability (ICC = 0.72) | Recalibrate velocity zones every 2-4 weeks |\n| Linear model adequate | Use simple linear velocity zones |\n| Decay accelerates near failure | Stop 1-2 reps from failure for quality |\n| First rep predicts set capacity | Use first rep velocity for autoregulation |\n\n### Implementation Steps\n\n1. **Initial Calibration**: Test each athlete to failure at submaximal loads (75-85% 1RM) to establish individual MVT\n2. **Set Up Zones**: Create linear velocity zones from MVT to maximum velocity\n3. **Monitor First Rep**: Use first rep velocity to estimate available reps\n4. **Stop Before Failure**: Given acceleration of velocity loss, target stopping 1-2 reps before predicted failure\n5. **Recalibrate Periodically**: Update velocity zones every 2-4 weeks or after significant training blocks\n\n## Limitations\n\n1. **Sample size**: 19 participants limits generalizability\n2. **Exercise specificity**: Results apply to deadlift; other exercises may differ\n3. **Load range**: Only 80% and 90% 1RM tested; lighter loads may show different patterns\n4. **Training status**: Participants were resistance-trained; novices may differ\n5. **Day-to-day factors**: Only 2 testing days; longer-term reliability unknown\n\n## References\n\n- Jukic, I., et al. (2024). Velocity-Based Training. *Sports Medicine*.\n- Zourdos, M. C., et al. (2016). Novel Resistance Training-Specific RPE Scale. *Journal of Strength and Conditioning Research*.\n- Pelland, J. C., et al. (2022). Using Load-Velocity Profiling. *Sports Medicine*.\n- Koo, T. K., & Li, M. Y. (2016). A Guideline of Selecting and Reporting ICC. *Journal of Chiropractic Medicine*.\n\n---\n\n*Study 6 of the Deadlift RIR-Velocity Research Project*\n\n*Analysis performed using R R version 4.3.3 (2024-02-29) with custom R6 classes following SOLID principles*\n",
    "supporting": [
      "06_advanced_velocity_analyses_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}