{
  "hash": "0404d068f27f059a445bd677f0279acc",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Velocity-Based Training for the Conventional Deadlift\"\nsubtitle: \"An Investigation of the RIR-Velocity Relationship\"\nauthor:\n  - name: \"João Costa\"\n    affiliation: \"Sport Science Research\"\n  - name: \"Filipe Braga\"\n    affiliation: \"MSc Thesis Research\"\ndate: today\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    code-fold: true\n    code-summary: \"Show code\"\n  pdf:\n    toc: true\n    toc-depth: 3\n    number-sections: true\n    colorlinks: true\n    papersize: a4\n    geometry:\n      - margin=2.5cm\n    include-in-header:\n      text: |\n        \\usepackage{booktabs}\n        \\usepackage{longtable}\nbibliography: references.bib\n---\n\n\n\n\n## Executive Summary\n\nThis research investigates whether velocity-based training (VBT) principles, well-established for exercises like the squat and bench press, can be successfully applied to the **conventional deadlift**---an exercise with unique biomechanical characteristics.\n\n### Our Analytical Approach\n\nThis analysis follows a **model-building** philosophy rather than traditional null hypothesis testing. The difference matters:\n\n| Approach | Question Asked | Goal |\n|----------|----------------|------|\n| Hypothesis Testing | \"Is the effect different from zero?\" | Reject or fail to reject H₀ |\n| **Model Building** | \"How well does this model describe the data?\" | Find the best description |\n\nWe build models to **understand and predict**---specifically, to create velocity-based training tools that work in practice. Our validation strategy uses robust methods (cluster-robust SEs, bootstrap CIs, conformal prediction) not because our model is \"broken,\" but as **pit stops** to confirm that conclusions don't depend on technical assumptions.\n\n### Key Findings\n\n| Question | Finding | Practical Implication |\n|----------|---------|----------------------|\n| **Does VBT work for deadlifts?** | Yes, but with more variability | Use VBT as one tool, not the only tool |\n| **Individual vs general models?** | Individual ~2x more accurate | Calibrate individually for serious athletes |\n| **Does load matter?** | No significant effect | One velocity table works across loads |\n| **MVT variability?** | CV = 30.8% | Individual calibration essential |\n| **Day-to-day reliability?** | Moderate (ICC ~0.5-0.7) | Recalibrate every 2-4 weeks |\n| **First-rep prediction?** | MAE = 1.29 reps | Useful for real-time autoregulation |\n\n### The Core Finding: Individual Variability\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Using OOP ModelPlotter class (CLAUDE.md principles)\nif (!is.null(lmm_results) && !is.null(lmm_results$best_model) &&\n    !is.null(lmm_results$best_model$model)) {\n\n  model_plotter$plot_model(\n    data = data,\n    model = lmm_results$best_model$model,\n    title = \"Why Individual Calibration Matters\"\n  )\n\n} else {\n  # Fallback to simple spaghetti if LMM not available\n  plot_spaghetti(\n    data,\n    highlight_population = TRUE,\n    title = \"Why Individual Calibration Matters\"\n  )\n}\n```\n\n::: {.cell-output-display}\n![Model Plot: Raw data (points) overlaid with individual fitted lines (gray) and the population-average model (red). This visualization shows both what we observed and what our model predicts.](deadlift_study_files/figure-html/fig-hero-model-plot-1.png){#fig-hero-model-plot width=100%}\n:::\n:::\n\n\nThis **model plot** shows our key insight: velocity decreases as athletes approach failure (the general trend in red), but **each athlete has a unique pattern** (gray lines). The scatter of raw data points around their individual predictions shows the within-person variability, while the spread of gray lines around the red line shows between-person variability. Using the population average (red) instead of individual calibration introduces substantial prediction error—this is why individual models are ~2x more accurate than general models.\n\n---\n\n## 1. Introduction\n\n### 1.1 Background\n\nVelocity-Based Training (VBT) has emerged as an objective method for monitoring and prescribing resistance training intensity. The fundamental principle is that as athletes approach muscular failure, their movement velocity decreases in a predictable manner. This relationship between velocity and Repetitions in Reserve (RIR) has been extensively studied in exercises like the back squat and bench press.\n\nThe theoretical foundation for VBT rests on the **force-velocity relationship**: as fatigue accumulates, the maximum force a muscle can produce decreases, resulting in slower movement at any given load. By monitoring velocity in real-time, coaches can objectively gauge proximity to failure without relying solely on subjective effort ratings.\n\n### 1.2 The Deadlift Challenge\n\nThe **conventional deadlift** presents unique biomechanical characteristics that may affect the velocity-RIR relationship:\n\n1. **Concentric-only initiation**: Unlike the squat, the deadlift begins from a dead stop without an eccentric-concentric stretch-shortening cycle, eliminating the elastic energy contribution\n\n2. **Grip as a limiting factor**: The grip can become a limiting factor independent of the target musculature (posterior chain), potentially causing failure before true muscular exhaustion\n\n3. **Binary failure pattern**: Deadlifts tend to fail more abruptly---either the bar leaves the floor or it doesn't---compared to the gradual \"grinding\" often seen in squats\n\n4. **Longer lever arms**: The horizontal distance between the load and hip joint creates substantial moment arms that change throughout the lift\n\n### 1.3 Research Questions\n\nThis thesis research addresses six key questions:\n\n1. Does a meaningful velocity-RIR relationship exist for deadlifts?\n2. Do individual models outperform general equations?\n3. Does load percentage affect the velocity-RIR relationship?\n4. How variable is the minimum velocity threshold (MVT) across individuals?\n5. How reliable are individual velocity profiles across testing days?\n6. Can first-rep velocity predict set capacity?\n\n---\n\n## 2. Methods\n\n### 2.1 Participants\n\n\n::: {#tbl-participants .cell tbl-cap='Participant Characteristics'}\n\n```{.r .cell-code}\nsummary_df <- data.frame(\n  Metric = c(\"Total Participants\", \"Male\", \"Female\",\n             \"Observations\", \"Velocity Range (m/s)\",\n             \"RIR Range\", \"Weight Range (kg)\"),\n  Value = c(\n    deadlift_results$summary$n_participants,\n    round(deadlift_results$summary$n_male),\n    round(deadlift_results$summary$n_female),\n    deadlift_results$summary$n_observations,\n    paste(round(deadlift_results$summary$velocity_range, 3), collapse = \" - \"),\n    paste(deadlift_results$summary$rir_range, collapse = \" - \"),\n    paste(deadlift_results$summary$weight_range, collapse = \" - \")\n  )\n)\n\nformat_table(summary_df, col.names = c(\"\", \"\"))\n```\n\n::: {.cell-output-display}\n\n\n|                     |              |\n|:--------------------|:-------------|\n|Total Participants   |19            |\n|Male                 |15            |\n|Female               |4             |\n|Observations         |406           |\n|Velocity Range (m/s) |0.119 - 0.675 |\n|RIR Range            |0 - 7         |\n|Weight Range (kg)    |85 - 210      |\n\n\n:::\n:::\n\n\n### 2.2 Protocol\n\nParticipants performed the conventional deadlift under standardized conditions:\n\n- **Exercise**: Conventional deadlift with standard Olympic barbell\n- **Loads**: 80% and 90% of 1RM (determined via prior 1RM testing)\n- **Testing Days**: 2 separate days (minimum 48-72 hours apart) for cross-validation\n- **Sets per condition**: Each load tested on each day (4 total conditions per participant)\n- **Rest periods**: 3-5 minutes between sets\n- **Failure criterion**: Inability to complete a full repetition or voluntary termination\n\n### 2.3 Velocity Measurement\n\nMean concentric velocity (MCV) was measured using a linear position transducer attached to the barbell. MCV represents the average velocity from the initiation of the pull until lockout.\n\n### 2.4 RIR Assignment\n\nRIR was assigned **prospectively** based on set completion:\n\n- Final repetition completed = RIR 0 (failure)\n- Penultimate repetition = RIR 1\n- And so forth...\n\nThis differs from subjective RIR estimates, providing an objective measure of proximity to failure.\n\n### 2.5 Statistical Analysis\n\nThe analysis employed multiple complementary approaches:\n\n**Individual vs General Models:**\n\n- General models: Population-level polynomial regression (velocity ~ RIR + RIR²)\n- Individual models: Participant-specific polynomial regressions\n- Cross-validation: Day 1 models tested on Day 2 data\n\n#### Why Mixed Models? The Non-Independence Problem\n\nStandard regression assumes each observation is independent---knowing one data point tells you nothing about another. But our data violates this assumption fundamentally: **multiple repetitions are nested within the same athlete**.\n\nConsider why this matters:\n\n1. **Athlete A** might be naturally slower across all RIR levels (lower intercept)\n2. **Athlete B** might show steeper velocity decline as they fatigue (steeper slope)\n3. **Observations from the same athlete are correlated**---if Athlete A's first rep is slow, their second rep will likely also be slow\n\nIgnoring this clustering leads to two problems:\n\n- **Inflated sample size**: We have 406 observations but only 19 independent units (athletes)\n- **Pseudoreplication**: Standard errors become artificially small, producing spuriously significant p-values\n\n**The Design Effect** quantifies this inflation. With an intraclass correlation (ICC) of ρ and cluster size n, the effective sample size is reduced by:\n\n$$\\text{Design Effect} = 1 + (n - 1) \\times \\rho$$\n\nFor example, if ICC = 0.30 and each athlete contributes 15 observations, the design effect is $1 + (15-1) \\times 0.30 = 5.2$. This means our 406 observations behave like only 78 independent observations for estimating population effects.\n\n**Linear Mixed Effects Models (LMM)** solve this problem by explicitly modeling both:\n\n- **Fixed effects**: The population-average velocity-RIR relationship (what we want to estimate)\n- **Random effects**: Individual deviations from the population average (what creates the non-independence)\n\nThis approach provides correct standard errors, proper inference, and the ability to make both population-level and individual-level predictions.\n\n**Advanced Analyses:**\n\n- MVT variability assessment (CV, IQR)\n- Day-to-day reliability (ICC)\n- Polynomial vs linear model comparison (AIC, BIC)\n- Velocity decay analysis\n- Failure prediction from early rep velocities (LOOCV)\n\n---\n\n## 3. Results\n\n### 3.1 The Velocity-RIR Relationship\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data, aes(x = mean_velocity, y = rir, color = load_percentage)) +\n  geom_point(alpha = 0.4, size = 2) +\n  geom_smooth(method = \"lm\", formula = y ~ poly(x, 2), se = FALSE, linewidth = 1.2) +\n  facet_wrap(~load_percentage, labeller = labeller(load_percentage = c(\n    `80%` = \"80% 1RM\",\n    `90%` = \"90% 1RM\"\n  ))) +\n  scale_color_load() +\n  labs(\n    x = \"Mean Velocity (m/s)\",\n    y = \"Repetitions in Reserve\"\n  ) +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![Velocity-RIR relationship for conventional deadlift](deadlift_study_files/figure-html/fig-scatter-1.png){#fig-scatter width=100%}\n:::\n:::\n\n\nA clear negative relationship exists: higher RIR (more reps remaining) is associated with faster velocities. However, the scatter is notably larger than typically reported for squat data, particularly at 80% 1RM.\n\n### 3.2 General vs Individual Models\n\n\n::: {#tbl-models .cell tbl-cap='Model Fit Comparison'}\n\n```{.r .cell-code}\ncomparison_df <- data.frame(\n  `Model Type` = c(\"General (Polynomial)\", \"Individual (Polynomial)\"),\n  `R²` = c(\n    round(deadlift_results$comparison$general_r2, 3),\n    round(deadlift_results$comparison$individual_r2, 3)\n  ),\n  `Interpretation` = c(\n    paste0(\"Explains ~\", round(deadlift_results$comparison$general_r2 * 100), \"% of variance\"),\n    paste0(\"Explains ~\", round(deadlift_results$comparison$individual_r2 * 100), \"% of variance\")\n  ),\n  check.names = FALSE\n)\n\nformat_table(comparison_df)\n```\n\n::: {.cell-output-display}\n\n\n|                        |      |                          |\n|:-----------------------|-----:|:-------------------------|\n|General (Polynomial)    | 0.362|Explains ~36% of variance |\n|Individual (Polynomial) | 0.707|Explains ~71% of variance |\n\n\n:::\n:::\n\n\n**Key Finding**: Individual models explain **2x more variance** than general models, consistent with squat research. This substantial improvement justifies individual calibration for serious athletes.\n\n### 3.3 Exercise Comparison: Deadlift vs Squat\n\n\n::: {#tbl-exercise-comparison .cell tbl-cap='Deadlift vs Squat RIR-Velocity Relationship'}\n\n```{.r .cell-code}\nexercise_comparison <- data.frame(\n  Metric = c(\"Participants\", \"Load Types\", \"General R²\", \"Individual R²\", \"Improvement Factor\"),\n  Squat = c(\n    \"46\", \"70%, 80%, 90%\",\n    round(squat_results$comparison$general_r2, 2),\n    round(squat_results$comparison$individual_r2, 2),\n    paste0(round(squat_results$comparison$improvement_factor, 2), \"x\")\n  ),\n  Deadlift = c(\n    as.character(deadlift_results$summary$n_participants),\n    \"80%, 90%\",\n    round(deadlift_results$comparison$general_r2, 2),\n    round(deadlift_results$comparison$individual_r2, 2),\n    paste0(round(deadlift_results$comparison$improvement_factor, 2), \"x\")\n  )\n)\n\nformat_table(exercise_comparison)\n```\n\n::: {.cell-output-display}\n\n\n|                   |              |         |\n|:------------------|:-------------|:--------|\n|Participants       |46            |19       |\n|Load Types         |70%, 80%, 90% |80%, 90% |\n|General R²         |0.5           |0.36     |\n|Individual R²      |0.88          |0.71     |\n|Improvement Factor |1.78x         |1.95x    |\n\n\n:::\n:::\n\n\nThe deadlift shows **lower R² values** than the squat, likely due to:\n\n1. **Binary failure pattern**: Less intermediate velocity signal\n2. **Grip fatigue**: Introduces noise uncorrelated with true RIR\n3. **Absence of stretch-shortening cycle**: Increased rep-to-rep variability\n4. **Technical breakdown**: May affect velocity differently than pure muscular fatigue\n\n### 3.4 Cross-Day Prediction Accuracy\n\nA critical test of any VBT model is its ability to predict performance on novel occasions. We tested Day 1 models on Day 2 data:\n\n\n::: {#tbl-prediction .cell tbl-cap='Cross-Day Prediction Accuracy'}\n\n```{.r .cell-code}\nif (!is.null(deadlift_results$general_prediction_accuracy)) {\n  accuracy <- deadlift_results$general_prediction_accuracy\n\n  prediction_df <- data.frame(\n    Metric = c(\n      \"Mean Absolute Error\",\n      \"Median Absolute Error\",\n      \"Within 1 rep\",\n      \"Within 2 reps\"\n    ),\n    Value = c(\n      paste(round(mean(accuracy$absolute_error, na.rm = TRUE), 2), \"reps\"),\n      paste(round(median(accuracy$absolute_error, na.rm = TRUE), 2), \"reps\"),\n      paste0(round(mean(accuracy$absolute_error <= 1, na.rm = TRUE) * 100, 1), \"%\"),\n      paste0(round(mean(accuracy$absolute_error <= 2, na.rm = TRUE) * 100, 1), \"%\")\n    )\n  )\n\n  format_table(prediction_df, col.names = c(\"Metric\", \"Value\"))\n} else {\n  cat(\"*Cross-day prediction accuracy will be available after running the analysis pipeline.*\\n\")\n}\n```\n\n::: {.cell-output-display}\n\n\n|Metric                |Value     |\n|:---------------------|:---------|\n|Mean Absolute Error   |1.39 reps |\n|Median Absolute Error |1.15 reps |\n|Within 1 rep          |46.8%     |\n|Within 2 reps         |72.2%     |\n\n\n:::\n:::\n\n\nThese prediction errors (~1.4 reps MAE) are practically meaningful---they indicate that a VBT system targeting RIR 2 might actually result in RIR 0-4 in practice. This uncertainty should be factored into training prescription, with conservative targets.\n\n### 3.5 Velocity Distribution by Load\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data, aes(x = factor(rir), y = mean_velocity, fill = load_percentage)) +\n  geom_boxplot(alpha = 0.5, outlier.shape = NA, width = 0.7) +\n  geom_point(\n    aes(color = load_percentage),\n    position = position_jitterdodge(jitter.width = 0.15, dodge.width = 0.7),\n    alpha = 0.6, size = 1.5\n  ) +\n  labs(\n    x = \"Repetitions in Reserve\",\n    y = \"Mean Velocity (m/s)\",\n    fill = \"Load\",\n    color = \"Load\"\n  ) +\n  scale_fill_load() +\n  scale_color_manual(values = c(\"80%\" = \"#CC7A00\", \"90%\" = \"#007A5E\")) +\n  theme(legend.position = \"bottom\") +\n  guides(fill = guide_legend(override.aes = list(alpha = 0.7)),\n         color = \"none\")\n```\n\n::: {.cell-output-display}\n![Velocity distribution by load and RIR](deadlift_study_files/figure-html/fig-velocity-load-1.png){#fig-velocity-load width=100%}\n:::\n:::\n\n\n**Observations:**\n\n- Higher load (90%) = lower velocities overall\n- Clear velocity decrease as RIR approaches 0\n- Wide variability between individuals at the same RIR\n\n### 3.6 Load Effects (LMM Analysis)\n\n#### The Question\n\nWhen prescribing VBT for deadlifts, should coaches use **one velocity table for all loads**, or do they need **separate tables for each load percentage**? If the velocity-RIR relationship differs substantially between 80% and 90% 1RM, then a single table would introduce systematic errors at one or both loads.\n\n#### The Method\n\nTo test whether load percentage affects the velocity-RIR relationship, we used a **Linear Mixed Effects Model (LMM)** with likelihood ratio testing:\n\n1. **Null Model**: Velocity ~ RIR + (1 + RIR | participant)\n   - Assumes load percentage has no effect\n\n2. **Alternative Model**: Velocity ~ RIR × Load + (1 + RIR | participant)\n   - Allows separate slopes for each load\n\nThe models were compared using a **likelihood ratio test** (LRT). A significant LRT indicates that including load percentage improves model fit beyond what would be expected by chance.\n\n**Why LMM?** Unlike simple regression, LMMs properly account for the nested data structure (multiple observations per participant) by estimating both population-average effects (fixed effects) and individual deviations (random effects). This prevents pseudo-replication bias and provides more accurate inference.\n\n#### The Finding\n\n\n\n```{.r .cell-code}\nif (!is.null(lmm_results) && !is.null(lmm_results$load_importance_result)) {\n  load_result <- lmm_results$load_importance_result\n\n  if (isTRUE(load_result$recommendation == \"global\")) {\n    cat(\"**Result**: Load percentage does NOT significantly affect the velocity-RIR relationship.\\n\\n\")\n    if (!is.null(load_result$lr_stat) && is.numeric(load_result$lr_stat)) {\n      cat(\"- Likelihood ratio test: χ² =\", round(as.numeric(load_result$lr_stat), 2), \", p =\", format_p(as.numeric(load_result$p_value)), \"\\n\")\n    }\n    cat(\"- The interaction between RIR and load percentage was not statistically significant\\n\\n\")\n    cat(\"**Practical Implication**: Coaches can use a **single global velocity table** regardless of whether athletes are lifting at 80% or 90% 1RM. This substantially simplifies training prescription---no need to consult different tables for different loads.\\n\")\n  } else {\n    cat(\"**Result**: Load percentage significantly affects the velocity-RIR relationship.\\n\\n\")\n    if (!is.null(load_result$lr_stat) && is.numeric(load_result$lr_stat)) {\n      cat(\"- Likelihood ratio test: χ² =\", round(as.numeric(load_result$lr_stat), 2), \", p =\", format_p(as.numeric(load_result$p_value)), \"\\n\\n\")\n    }\n    cat(\"**Practical Implication**: **Load-specific tables** are recommended. Using a single table would introduce systematic prediction errors at one or both loads.\\n\")\n  }\n} else {\n  cat(\"*Load effect analysis will be available after running the LMM analysis pipeline.*\\n\")\n}\n```\n\n**Result**: Load percentage does NOT significantly affect the velocity-RIR relationship.\n\n- The interaction between RIR and load percentage was not statistically significant\n\n**Practical Implication**: Coaches can use a **single global velocity table** regardless of whether athletes are lifting at 80% or 90% 1RM. This substantially simplifies training prescription---no need to consult different tables for different loads.\n\n\n### 3.5 Velocity Stop Tables\n\n#### What Are Velocity Stop Tables?\n\nA **velocity stop table** provides target velocities for each RIR level. During training, when bar velocity drops to the threshold for a given RIR, the athlete stops the set. This enables objective, real-time autoregulation without relying on subjective fatigue ratings.\n\n#### How Were These Tables Generated?\n\nThe tables were generated using **Linear Mixed Effects Model predictions**:\n\n1. **Model specification**:\n   - Fixed effect: RIR (the predictor)\n   - Random effects: Participant-specific intercepts and slopes\n   - This accounts for both the population-average relationship and individual variation\n\n2. **Prediction generation**:\n   - For each RIR value (0-5), we predicted the expected velocity using the fixed effects\n   - 95% confidence intervals were computed from the fixed effects standard errors\n   - These intervals represent uncertainty in the population-average relationship\n\n3. **Conformal prediction** (if available):\n   - Additionally, we computed conformal prediction intervals that provide distribution-free coverage guarantees\n   - These intervals are more conservative and account for both model uncertainty and individual variation\n\n**Why this approach?** The LMM predictions represent the best estimate of the \"typical\" velocity at each RIR for this population. The confidence intervals quantify how precisely we've estimated this relationship.\n\n\n::: {#tbl-velocity-stop .cell tbl-cap='Velocity Stop Table: Target velocities for each RIR level'}\n\n```{.r .cell-code}\nif (!is.null(lmm_results)) {\n  vt <- lmm_results$velocity_table$table\n\n  if (\"load_percentage\" %in% names(vt)) {\n    vt$velocity <- round(vt$velocity, 3)\n    vt$lower_95 <- round(vt$lower_95, 3)\n    vt$upper_95 <- round(vt$upper_95, 3)\n    format_table(vt[, c(\"rir\", \"load_percentage\", \"velocity\", \"lower_95\", \"upper_95\")],\n          col.names = c(\"RIR\", \"Load\", \"Velocity (m/s)\", \"Lower 95%\", \"Upper 95%\"))\n  } else {\n    vt$velocity <- round(vt$velocity, 3)\n    vt$lower_95 <- round(vt$lower_95, 3)\n    vt$upper_95 <- round(vt$upper_95, 3)\n    format_table(vt[, c(\"rir\", \"velocity\", \"lower_95\", \"upper_95\")],\n          col.names = c(\"RIR\", \"Velocity (m/s)\", \"Lower 95%\", \"Upper 95%\"))\n  }\n}\n```\n\n::: {.cell-output-display}\n\n\n| RIR| Velocity (m/s)| Lower 95%| Upper 95%|\n|---:|--------------:|---------:|---------:|\n|   0|          0.215|     0.114|     0.317|\n|   1|          0.244|     0.143|     0.346|\n|   2|          0.274|     0.172|     0.375|\n|   3|          0.303|     0.201|     0.404|\n|   4|          0.332|     0.231|     0.433|\n|   5|          0.361|     0.260|     0.463|\n|   6|          0.390|     0.289|     0.492|\n|   7|          0.420|     0.318|     0.521|\n\n\n:::\n:::\n\n\n**How to Use This Table:**\n\n1. Monitor bar velocity in real-time during training\n2. Stop the set when velocity drops to your target RIR threshold\n3. Example: To leave 2 reps in reserve, stop when velocity reaches the corresponding threshold\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (!is.null(lmm_results)) {\n  vt <- lmm_results$velocity_table$table\n\n  if (\"load_percentage\" %in% names(vt)) {\n    ggplot(vt, aes(x = rir, y = velocity, color = load_percentage)) +\n      geom_line(linewidth = 1.2) +\n      geom_point(size = 3) +\n      geom_ribbon(aes(ymin = lower_95, ymax = upper_95, fill = load_percentage),\n                  alpha = 0.2, color = NA) +\n      scale_color_load() + scale_fill_load() +\n      labs(x = \"Repetitions in Reserve (RIR)\", y = \"Mean Velocity (m/s)\")\n  } else {\n    ggplot(vt, aes(x = rir, y = velocity)) +\n      geom_line(linewidth = 1.2, color = COLORS$primary) +\n      geom_point(size = 3, color = COLORS$primary) +\n      geom_ribbon(aes(ymin = lower_95, ymax = upper_95),\n                  alpha = 0.2, fill = COLORS$primary) +\n      labs(x = \"Repetitions in Reserve (RIR)\", y = \"Mean Velocity (m/s)\",\n           title = \"Global Velocity Stop Table for Deadlift\")\n  }\n}\n```\n\n::: {.cell-output-display}\n![Velocity Stop Thresholds by RIR](deadlift_study_files/figure-html/fig-velocity-table-1.png){#fig-velocity-table width=100%}\n:::\n:::\n\n\n### 3.6 Individual vs General Table Accuracy\n\n#### The Question\n\nDoes **individual calibration** meaningfully improve prediction accuracy compared to the general population table? If the improvement is marginal, individual calibration may not be worth the additional testing time. If substantial, it's essential for serious athletes.\n\n#### The Method\n\nWe compared two approaches using **out-of-sample prediction error**:\n\n1. **General (Population) Table**: Uses the LMM fixed effects only---the same velocity targets for everyone\n2. **Individual (Calibrated) Table**: Uses LMM fixed effects + random effects (BLUPs)---personalized velocity targets\n\n**Metrics:**\n\n- **MAE (Mean Absolute Error)**: Average velocity prediction error in mm/s\n- **RMSE (Root Mean Square Error)**: Penalizes larger errors more heavily\n\n\n::: {#tbl-individual-comparison .cell tbl-cap='General vs Individual Table Accuracy'}\n\n```{.r .cell-code}\nif (!is.null(lmm_results)) {\n  ic <- lmm_results$individual_comparison\n\n  comparison_df <- data.frame(\n    Approach = c(\"General (Population)\", \"Individual (Calibrated)\"),\n    MAE = c(round(ic$global_mae * 1000, 2), round(ic$individual_mae * 1000, 2)),\n    RMSE = c(round(ic$global_rmse * 1000, 2), round(ic$individual_rmse * 1000, 2))\n  )\n\n  format_table(comparison_df, col.names = c(\"Approach\", \"MAE (mm/s)\", \"RMSE (mm/s)\"))\n}\n```\n\n::: {.cell-output-display}\n\n\n|Approach                | MAE (mm/s)| RMSE (mm/s)|\n|:-----------------------|----------:|-----------:|\n|General (Population)    |      59.86|       79.17|\n|Individual (Calibrated) |      39.54|       51.75|\n\n\n:::\n:::\n\n\n```{.r .cell-code}\nif (!is.null(lmm_results)) {\n  ic <- lmm_results$individual_comparison\n  cat(\"\\n**Improvement from individualization**:\", round(ic$mae_improvement_pct, 1), \"%\\n\")\n}\n```\n\n\n**Improvement from individualization**: 34 %\n\n\n#### The Finding\n\nIndividual calibration reduces prediction error by approximately 34%. This is a substantial improvement that justifies the additional testing burden for serious athletes who require precise autoregulation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Using OOP ModelPlotter class (CLAUDE.md principles)\nif (!is.null(lmm_results) && !is.null(lmm_results$best_model) &&\n    !is.null(lmm_results$best_model$model)) {\n\n  model_plotter$plot_prediction_comparison(\n    data = data,\n    model = lmm_results$best_model$model,\n    title = \"Why Individual Calibration Matters: Error Distribution Comparison\"\n  )\n}\n```\n\n::: {.cell-output-display}\n![Prediction Error Comparison: Population (fixed effects only) vs Individual (fixed + random effects) predictions. The distribution of individual errors is more concentrated around zero.](deadlift_study_files/figure-html/fig-prediction-comparison-1.png){#fig-prediction-comparison width=100%}\n:::\n:::\n\n\nThis visualization directly demonstrates the benefit of individual calibration. The **tighter distribution** of individual prediction errors (green) compared to population errors (blue) shows that accounting for individual differences substantially improves prediction accuracy. The practical implication: using the population average velocity table will lead to larger prediction errors for most athletes.\n\n**Practical Implication**: The general table is a reasonable starting point for recreational lifters, but competitive athletes should invest in individual calibration sessions.\n\n### 3.7 Conformal Prediction Intervals\n\n#### The Problem with Parametric Intervals\n\nTraditional prediction intervals assume the residuals are normally distributed and homoscedastic (constant variance). When assumptions fail, parametric intervals may have incorrect coverage---claiming 95% coverage but actually achieving 85% or 105%.\n\n#### The Conformal Prediction Solution\n\n**Conformal prediction** [@vovk2005; @lei2018] provides **distribution-free** intervals with guaranteed finite-sample coverage. The key insight is to use the data itself to calibrate the interval width, rather than relying on distributional assumptions.\n\n#### Method: Split Conformal Prediction\n\nWe use **split conformal prediction**:\n\n1. **Split data**: Day 1 (calibration), Day 2 (test)\n2. **Fit model** on calibration set\n3. **Calculate nonconformity scores**: Absolute residuals on calibration set\n4. **Find threshold**: The 95th percentile of nonconformity scores\n5. **Construct intervals**: For new predictions, add/subtract the threshold\n\nThis procedure guarantees that if calibration and test data are exchangeable, coverage will be at least 95% in expectation.\n\n#### Conformal vs Parametric Comparison\n\n\n::: {#tbl-conformal .cell tbl-cap='Conformal vs Parametric Prediction Intervals'}\n\n```{.r .cell-code}\nif (!is.null(lmm_results) && !is.null(lmm_results$conformal)) {\n  conf <- lmm_results$conformal\n\n  comparison_df <- data.frame(\n    Metric = c(\"Target Coverage\", \"Empirical Coverage\", \"Average Interval Width\"),\n    Parametric = c(\n      \"95%\",\n      sprintf(\"%.1f%%\", conf$comparison$parametric_coverage * 100),\n      sprintf(\"%.4f m/s\", conf$comparison$parametric_width)\n    ),\n    Conformal = c(\n      \"95%\",\n      sprintf(\"%.1f%%\", conf$comparison$conformal_coverage * 100),\n      sprintf(\"%.4f m/s\", conf$comparison$conformal_width)\n    )\n  )\n\n  format_table(comparison_df, col.names = c(\"Metric\", \"Parametric\", \"Conformal\"))\n} else {\n  # Generate display with placeholder values to show table structure\n  cat(\"*Note: Full conformal prediction results will be available after running the complete LMM analysis pipeline with `make analyze-lmm`.*\\n\\n\")\n  cat(\"**Expected output:**\\n\\n\")\n  cat(\"| Metric | Parametric | Conformal |\\n\")\n  cat(\"|--------|------------|----------|\\n\")\n  cat(\"| Target Coverage | 95% | 95% |\\n\")\n  cat(\"| Empirical Coverage | ~92-96% | ~94-96% |\\n\")\n  cat(\"| Average Interval Width | ~0.08-0.12 m/s | ~0.10-0.14 m/s |\\n\")\n}\n```\n\n::: {.cell-output-display}\n\n\n|Metric                 |Parametric |Conformal |\n|:----------------------|:----------|:---------|\n|Target Coverage        |95%        |95%       |\n|Empirical Coverage     |95%        |95%       |\n|Average Interval Width |95%        |95%       |\n\n\n:::\n:::\n\n\n```{.r .cell-code}\nif (!is.null(lmm_results) && !is.null(lmm_results$conformal)) {\n  conf <- lmm_results$conformal\n  # Use correct field names: pi_coverage for parametric, coverage for conformal\n  parametric_cov <- conf$comparison$pi_coverage\n  conformal_cov <- conf$coverage\n\n  cat(\"\\n**Key Insight:**\\n\\n\")\n  cat(\"- Parametric (PI) coverage:\", sprintf(\"%.1f%%\", parametric_cov * 100),\n      \"(deviation from 95%:\", sprintf(\"%.1f%%\", abs(parametric_cov - 0.95) * 100), \")\\n\")\n  cat(\"- Conformal coverage:\", sprintf(\"%.1f%%\", conformal_cov * 100),\n      \"(deviation from 95%:\", sprintf(\"%.1f%%\", abs(conformal_cov - 0.95) * 100), \")\\n\\n\")\n\n  if (abs(conformal_cov - 0.95) < abs(parametric_cov - 0.95)) {\n    cat(\"**Conformal intervals achieve coverage closer to the 95% target.**\\n\")\n  } else {\n    cat(\"**Parametric intervals achieve coverage closer to the 95% target.**\\n\")\n  }\n}\n```\n\n\n**Key Insight:**\n\n- Parametric (PI) coverage: 91.6% (deviation from 95%: 3.4% )\n- Conformal coverage: 95.6% (deviation from 95%: 0.6% )\n\n**Conformal intervals achieve coverage closer to the 95% target.**\n\n\n#### Conformal Prediction Details\n\n\n::: {#tbl-conformal-details .cell tbl-cap='Conformal Prediction Interval Calibration Details'}\n\n```{.r .cell-code}\nif (!is.null(lmm_results) && !is.null(lmm_results$conformal)) {\n  conf <- lmm_results$conformal\n\n  detail_df <- data.frame(\n    Component = c(\n      \"Nonconformity Score Threshold (95th percentile)\",\n      \"Interval Half-Width\",\n      \"Total Interval Width\",\n      \"Target Coverage\",\n      \"Achieved Conformal Coverage\",\n      \"Achieved Parametric (PI) Coverage\"\n    ),\n    Value = c(\n      sprintf(\"%.4f m/s\", conf$q_hat),\n      sprintf(\"± %.4f m/s\", conf$q_hat),\n      sprintf(\"%.4f m/s\", conf$interval_width),\n      \"95%\",\n      sprintf(\"%.1f%% (error: %.2f%%)\", conf$coverage * 100,\n              abs(conf$coverage - 0.95) * 100),\n      sprintf(\"%.1f%% (error: %.2f%%)\", conf$comparison$pi_coverage * 100,\n              abs(conf$comparison$pi_coverage - 0.95) * 100)\n    )\n  )\n\n  format_table(detail_df, col.names = c(\"Component\", \"Value\"))\n}\n```\n\n::: {.cell-output-display}\n\n\n|Component                                       |Value                |\n|:-----------------------------------------------|:--------------------|\n|Nonconformity Score Threshold (95th percentile) |0.1047 m/s           |\n|Interval Half-Width                             |± 0.1047 m/s         |\n|Total Interval Width                            |0.2094 m/s           |\n|Target Coverage                                 |95%                  |\n|Achieved Conformal Coverage                     |95.6% (error: 0.61%) |\n|Achieved Parametric (PI) Coverage               |91.6% (error: 3.37%) |\n\n\n:::\n:::\n\n\n#### Visualization: Conformal vs Parametric Intervals\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (!is.null(lmm_results) && !is.null(lmm_results$conformal)) {\n  conf <- lmm_results$conformal\n  vt <- lmm_results$velocity_table$table\n  vt$conformal_lower <- vt$velocity - conf$q_hat\n  vt$conformal_upper <- vt$velocity + conf$q_hat\n\n  # Reshape for plotting\n  interval_comparison <- data.frame(\n    rir = rep(vt$rir, 2),\n    velocity = rep(vt$velocity, 2),\n    lower = c(vt$lower_95, vt$conformal_lower),\n    upper = c(vt$upper_95, vt$conformal_upper),\n    method = rep(c(\"Parametric (95% CI)\", \"Conformal (95% PI)\"), each = nrow(vt))\n  )\n\n  ggplot(interval_comparison, aes(x = rir)) +\n    geom_ribbon(aes(ymin = lower, ymax = upper, fill = method), alpha = 0.3) +\n    geom_line(aes(y = velocity), color = \"black\", linewidth = 1) +\n    geom_point(aes(y = velocity), color = \"black\", size = 3) +\n    facet_wrap(~method) +\n    labs(\n      x = \"Repetitions in Reserve (RIR)\",\n      y = \"Mean Velocity (m/s)\",\n      title = \"Comparison of Prediction Interval Methods\",\n      subtitle = \"Wider intervals indicate more uncertainty\"\n    ) +\n    theme_minimal() +\n    theme(legend.position = \"none\") +\n    scale_fill_manual(values = c(COLORS$primary, COLORS$secondary))\n}\n```\n\n::: {.cell-output-display}\n![Conformal vs Parametric Prediction Intervals Across RIR Levels](deadlift_study_files/figure-html/fig-conformal-intervals-1.png){#fig-conformal-intervals width=100%}\n:::\n:::\n\n\n#### Velocity Stop Table with Conformal Intervals\n\nThis table provides **conservative velocity targets** using conformal prediction intervals, which have guaranteed 95% coverage regardless of distributional assumptions.\n\n\n::: {#tbl-conformal-stops .cell tbl-cap='Velocity Stop Thresholds with Conformal Prediction Intervals'}\n\n```{.r .cell-code}\nif (!is.null(lmm_results) && !is.null(lmm_results$conformal)) {\n  conf <- lmm_results$conformal\n  vt <- lmm_results$velocity_table$table\n\n  conformal_table <- data.frame(\n    RIR = vt$rir,\n    `Target Velocity` = round(vt$velocity, 3),\n    `Lower 95% (Conservative)` = round(vt$velocity - conf$q_hat, 3),\n    `Upper 95%` = round(vt$velocity + conf$q_hat, 3),\n    `Interval Width` = round(2 * conf$q_hat, 3),\n    check.names = FALSE\n  )\n\n  format_table(conformal_table,\n        col.names = c(\"Target RIR\", \"Mean Velocity (m/s)\", \"Lower Bound\", \"Upper Bound\", \"Width (m/s)\"))\n}\n```\n\n::: {.cell-output-display}\n\n\n| Target RIR| Mean Velocity (m/s)| Lower Bound| Upper Bound| Width (m/s)|\n|----------:|-------------------:|-----------:|-----------:|-----------:|\n|          0|               0.215|       0.110|       0.320|       0.209|\n|          1|               0.244|       0.140|       0.349|       0.209|\n|          2|               0.274|       0.169|       0.378|       0.209|\n|          3|               0.303|       0.198|       0.408|       0.209|\n|          4|               0.332|       0.227|       0.437|       0.209|\n|          5|               0.361|       0.256|       0.466|       0.209|\n|          6|               0.390|       0.286|       0.495|       0.209|\n|          7|               0.420|       0.315|       0.524|       0.209|\n\n\n:::\n:::\n\n\n**How to Use This Table:**\n\n1. **Conservative approach (recommended)**: Use the **Lower Bound** column. If your current velocity is at or below this threshold, you are likely at or past your target RIR with 95% confidence.\n\n2. **Aggressive approach**: Use the **Mean Velocity** column. You'll hit your target RIR on average, but may occasionally overshoot (go too close to failure).\n\n\n\n```{.r .cell-code}\nif (!is.null(lmm_results) && !is.null(lmm_results$conformal)) {\n  conf <- lmm_results$conformal\n  vt <- lmm_results$velocity_table$table\n  rir2_row <- vt[vt$rir == 2, ]\n\n  cat(\"3. **Example**: To stop at RIR 2:\\n\")\n  cat(\"   - **Conservative**: Stop when velocity drops to ~\", round(rir2_row$velocity - conf$q_hat, 2), \"m/s\\n\")\n  cat(\"   - **Mean target**: Stop when velocity drops to ~\", round(rir2_row$velocity, 2), \"m/s\\n\")\n}\n```\n\n3. **Example**: To stop at RIR 2:\n   - **Conservative**: Stop when velocity drops to ~ 0.17 m/s\n   - **Mean target**: Stop when velocity drops to ~ 0.27 m/s\n\n\n#### Coverage Comparison\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (!is.null(lmm_results) && !is.null(lmm_results$conformal)) {\n  conf <- lmm_results$conformal\n\n  coverage_df <- data.frame(\n    Method = c(\"Conformal\", \"Parametric\", \"Target\"),\n    Coverage = c(\n      conf$comparison$conformal_coverage * 100,\n      conf$comparison$parametric_coverage * 100,\n      95\n    ),\n    Type = c(\"Achieved\", \"Achieved\", \"Target\")\n  )\n\n  ggplot(coverage_df, aes(x = Method, y = Coverage, fill = Type)) +\n    geom_col(width = 0.6) +\n    geom_hline(yintercept = 95, linetype = \"dashed\", color = COLORS$secondary, linewidth = 1) +\n    geom_text(aes(label = sprintf(\"%.1f%%\", Coverage)), vjust = -0.5, size = 4) +\n    scale_fill_manual(values = c(\"Achieved\" = COLORS$primary, \"Target\" = \"#009E73\")) +\n    labs(\n      x = \"\",\n      y = \"Coverage (%)\",\n      title = \"Prediction Interval Coverage Comparison\",\n      subtitle = \"Conformal prediction achieves coverage closer to the 95% target\"\n    ) +\n    ylim(0, 105) +\n    theme_minimal() +\n    theme(legend.position = \"none\")\n}\n```\n\n::: {.cell-output-display}\n![Coverage Comparison: Conformal vs Parametric Methods](deadlift_study_files/figure-html/fig-coverage-comparison-1.png){#fig-coverage-comparison width=100%}\n:::\n:::\n\n\n#### Practical Implications of Conformal Intervals\n\n\n\n```{.r .cell-code}\nif (!is.null(lmm_results) && !is.null(lmm_results$conformal)) {\n  conf <- lmm_results$conformal\n\n  cat(\"The conformal prediction approach has several advantages for velocity-based training:\\n\\n\")\n  cat(\"1. **Distribution-free guarantee**: Unlike parametric intervals that assume normality, conformal intervals work regardless of the true error distribution.\\n\\n\")\n  cat(\"2. **Honest uncertainty**: The interval width (\", round(conf$q_hat * 2, 3), \"m/s) reflects the true prediction uncertainty in our sample.\\n\\n\")\n  cat(\"3. **Conservative targets**: Using the lower bound of conformal intervals ensures you don't accidentally train too close to failure.\\n\\n\")\n  cat(\"4. **Practical interpretation**: The\", round(conf$q_hat * 1000, 0), \"mm/s half-width means velocity measurements within this range of your target are essentially equivalent---don't over-interpret small velocity differences.\\n\")\n}\n```\n\nThe conformal prediction approach has several advantages for velocity-based training:\n\n1. **Distribution-free guarantee**: Unlike parametric intervals that assume normality, conformal intervals work regardless of the true error distribution.\n\n2. **Honest uncertainty**: The interval width ( 0.209 m/s) reflects the true prediction uncertainty in our sample.\n\n3. **Conservative targets**: Using the lower bound of conformal intervals ensures you don't accidentally train too close to failure.\n\n4. **Practical interpretation**: The 105 mm/s half-width means velocity measurements within this range of your target are essentially equivalent---don't over-interpret small velocity differences.\n\n\n---\n\n## 4. Advanced Analyses\n\n### 4.1 Minimum Velocity Threshold (MVT) Variability\n\n#### The Question\n\nThe **Minimum Velocity Threshold (MVT)** is the velocity at which an athlete can no longer complete a repetition (RIR = 0). If MVT is consistent across individuals, it could serve as a **universal failure indicator**---any time velocity drops below this threshold, the set should end. But how variable is MVT across individuals?\n\n#### The Method\n\nWe quantified MVT variability using:\n\n1. **Coefficient of Variation (CV)**: SD/Mean × 100%---a standardized measure of spread\n2. **Range (Min-Max)**: The full spread of MVT values observed\n3. **IQR**: Middle 50% of values, robust to outliers\n\n**Interpretation Guidelines:**\n\n- CV < 10%: Low variability → universal threshold may work\n- CV 10-25%: Moderate variability → individual calibration recommended\n- CV > 25%: High variability → individual calibration essential\n\n#### The Finding\n\n\n\n```{.r .cell-code}\nif (!is.null(advanced_results)) {\n  mvt <- advanced_results$mvt\n  cat(\"**Population MVT Statistics:**\\n\\n\")\n  cat(\"- Mean:\", round(mvt$population_stats$mean, 3), \"m/s\\n\")\n  cat(\"- SD:\", round(mvt$population_stats$sd, 3), \"m/s\\n\")\n  cat(\"- **CV:**\", round(mvt$population_stats$cv_percent, 1), \"%\\n\")\n  cat(\"- Range:\", round(mvt$population_stats$min, 3), \"-\", round(mvt$population_stats$max, 3), \"m/s\\n\")\n}\n```\n\n**Population MVT Statistics:**\n\n- Mean: 0.206 m/s\n- SD: 0.063 m/s\n- **CV:** 30.8 %\n- Range: 0.119 - 0.402 m/s\n\n::: {.cell}\n\n```{.r .cell-code}\nif (!is.null(advanced_results)) {\n  failure_data <- data[data$rir == 0, ]\n  mvt <- advanced_results$mvt\n\n  ggplot(failure_data, aes(x = mean_velocity)) +\n    geom_histogram(aes(y = after_stat(density)), bins = 20, fill = COLORS$primary, alpha = 0.7) +\n    geom_density(color = COLORS$secondary, linewidth = 1) +\n    geom_vline(xintercept = mvt$population_stats$mean, linetype = \"dashed\", linewidth = 1) +\n    labs(x = \"Velocity at Failure (m/s)\", y = \"Density\",\n         title = \"MVT Distribution Across Failure Observations\")\n}\n```\n\n::: {.cell-output-display}\n![Distribution of Minimum Velocity Threshold at failure](deadlift_study_files/figure-html/fig-mvt-1.png){#fig-mvt width=100%}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nif (!is.null(advanced_results) && !is.null(advanced_results$mvt$individual_stats)) {\n  ind_mvt <- advanced_results$mvt$individual_stats\n  ind_mvt <- ind_mvt[order(ind_mvt$mean_mvt), ]\n  ind_mvt$id <- factor(ind_mvt$id, levels = ind_mvt$id)\n\n  ggplot(ind_mvt, aes(x = id, y = mean_mvt, color = sex)) +\n    geom_point(size = 3) +\n    geom_errorbar(aes(ymin = mean_mvt - sd_mvt, ymax = mean_mvt + sd_mvt),\n                  width = 0.3) +\n    geom_hline(yintercept = advanced_results$mvt$population_stats$mean,\n               linetype = \"dashed\", color = \"gray50\") +\n    coord_flip() +\n    labs(x = \"Participant\", y = \"MVT (m/s)\",\n         title = \"Individual MVT with Standard Deviation\",\n         color = \"Sex\") +\n    scale_color_manual(values = c(\"female\" = COLORS$secondary, \"male\" = COLORS$primary))\n}\n```\n\n::: {.cell-output-display}\n![Individual MVT values showing between-participant variability](deadlift_study_files/figure-html/fig-mvt-individual-1.png){#fig-mvt-individual width=100%}\n:::\n:::\n\n\n**Load Comparison:**\n\n\n\n```{.r .cell-code}\nif (!is.null(advanced_results) && !is.null(advanced_results$mvt$load_comparison)) {\n  lc <- advanced_results$mvt$load_comparison\n  cat(\"- 80% 1RM MVT:\", round(lc$load_80_mean, 3), \"±\", round(lc$load_80_sd, 3), \"m/s\\n\")\n  cat(\"- 90% 1RM MVT:\", round(lc$load_90_mean, 3), \"±\", round(lc$load_90_sd, 3), \"m/s\\n\")\n  cat(\"- Difference:\", round(lc$difference, 3), \"m/s\\n\")\n  cat(\"- p-value:\", format(lc$wilcox_p, digits = 4), \"\\n\")\n  if (lc$significant) {\n    cat(\"- **Significant difference** - MVT varies by load\\n\")\n  } else {\n    cat(\"- No significant load effect - MVT appears consistent across loads\\n\")\n  }\n}\n```\n\n- 80% 1RM MVT: 0.217 ± 0.066 m/s\n- 90% 1RM MVT: 0.196 ± 0.061 m/s\n- Difference: 0.021 m/s\n- p-value: 0.148 \n- No significant load effect - MVT appears consistent across loads\n\n\nThe CV of 30.8% indicates **high inter-individual variability** (above the 25% threshold).\n\n**Practical Implication**: A universal MVT threshold would misclassify many athletes---some would stop too early (false positive for failure), others too late (missed failure). Individual calibration is not optional for accurate VBT in deadlifts.\n\n### 4.2 Day-to-Day Reliability\n\n#### The Question\n\nIf an athlete's velocity profile is established on Day 1, how well does it predict their performance on Day 2? Low reliability would require frequent recalibration, reducing the practical value of VBT.\n\n#### The Method\n\nWe assessed reliability using the **Intraclass Correlation Coefficient (ICC)** [@shroutfleiss1979; @kooli2016]:\n\n1. **ICC(2,1)**: Two-way random effects model, single measurement---the standard for test-retest reliability\n2. **Parameters assessed**:\n   - Velocity-RIR slope (sensitivity of velocity to fatigue)\n   - MVT (velocity at failure)\n\n**Interpretation Guidelines** [@kooli2016]:\n\n- ICC < 0.50: Poor reliability\n- ICC 0.50-0.75: Moderate reliability\n- ICC 0.75-0.90: Good reliability\n- ICC > 0.90: Excellent reliability\n\n**Additional Metrics:**\n\n- **SEM (Standard Error of Measurement)**: Expected test-retest variability in same units as measurement\n- **MDC95 (Minimal Detectable Change)**: The smallest change that exceeds measurement error with 95% confidence\n\n#### The Finding\n\n\n\n```{.r .cell-code}\nif (!is.null(advanced_results)) {\n  rel <- advanced_results$reliability\n  cat(\"**Reliability Results:**\\n\\n\")\n  cat(\"| Parameter | ICC | 95% CI | Interpretation |\\n\")\n  cat(\"|-----------|-----|--------|----------------|\\n\")\n  cat(sprintf(\"| Velocity-RIR Slope | %.2f | [%.2f, %.2f] | %s |\\n\",\n              rel$slope_icc$icc, rel$slope_icc$ci_lower, rel$slope_icc$ci_upper, rel$slope_icc$interpretation))\n  cat(sprintf(\"| MVT | %.2f | [%.2f, %.2f] | %s |\\n\",\n              rel$mvt_icc$icc, rel$mvt_icc$ci_lower, rel$mvt_icc$ci_upper, rel$mvt_icc$interpretation))\n  cat(\"\\n**Measurement Error:**\\n\\n\")\n  cat(\"- SEM:\", round(rel$mvt_icc$sem * 1000, 1), \"mm/s\\n\")\n  cat(\"- MDC95:\", round(rel$mvt_icc$mdc95 * 1000, 1), \"mm/s\\n\")\n  cat(\"\\n*Interpretation: A velocity change of at least\", round(rel$mvt_icc$mdc95 * 1000, 1), \"mm/s is needed to be confident it's a real change, not measurement noise.*\\n\")\n}\n```\n\n**Reliability Results:**\n\n| Parameter | ICC | 95% CI | Interpretation |\n|-----------|-----|--------|----------------|\n| Velocity-RIR Slope | 0.72 | [0.64, 0.80] | Moderate |\n| MVT | 0.50 | [0.38, 0.62] | Poor |\n\n**Measurement Error:**\n\n- SEM: 24 mm/s\n- MDC95: 66.6 mm/s\n\n*Interpretation: A velocity change of at least 66.6 mm/s is needed to be confident it's a real change, not measurement noise.*\n\n::: {.cell}\n\n```{.r .cell-code}\nif (!is.null(advanced_results) && !is.null(advanced_results$reliability$day_parameters)) {\n  day_params <- advanced_results$reliability$day_parameters\n\n  ggplot(day_params, aes(x = slope_day1, y = slope_day2)) +\n    geom_point(size = 3, alpha = 0.7, color = COLORS$primary) +\n    geom_abline(slope = 1, intercept = 0, linetype = \"dashed\", color = \"gray50\") +\n    geom_smooth(method = \"lm\", se = TRUE, color = COLORS$secondary) +\n    labs(x = \"Slope Day 1 (m/s per RIR)\", y = \"Slope Day 2 (m/s per RIR)\",\n         title = \"Day-to-Day Reliability of Individual Slopes\",\n         subtitle = paste(\"ICC =\", round(advanced_results$reliability$slope_icc$icc, 2)))\n}\n```\n\n::: {.cell-output-display}\n![Day 1 vs Day 2 comparison of individual velocity-RIR slopes](deadlift_study_files/figure-html/fig-reliability-slopes-1.png){#fig-reliability-slopes width=100%}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nif (!is.null(advanced_results) && !is.null(advanced_results$reliability$day_parameters)) {\n  day_params <- advanced_results$reliability$day_parameters\n\n  ggplot(day_params, aes(x = mvt_day1, y = mvt_day2)) +\n    geom_point(size = 3, alpha = 0.7, color = COLORS$primary) +\n    geom_abline(slope = 1, intercept = 0, linetype = \"dashed\", color = \"gray50\") +\n    geom_smooth(method = \"lm\", se = TRUE, color = COLORS$secondary) +\n    labs(x = \"MVT Day 1 (m/s)\", y = \"MVT Day 2 (m/s)\",\n         title = \"Day-to-Day Reliability of Predicted MVT\",\n         subtitle = paste(\"ICC =\", round(advanced_results$reliability$mvt_icc$icc, 2)))\n}\n```\n\n::: {.cell-output-display}\n![Day 1 vs Day 2 comparison of predicted MVT](deadlift_study_files/figure-html/fig-reliability-mvt-1.png){#fig-reliability-mvt width=100%}\n:::\n:::\n\n\n#### Bland-Altman Analysis\n\nThe Bland-Altman plot provides additional insight beyond ICC by showing:\n\n- **Systematic bias**: Is there a consistent difference between days?\n- **Limits of agreement**: What range of day-to-day variation should we expect?\n- **Proportional bias**: Does variability depend on the magnitude of the measurement?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (!is.null(advanced_results) && !is.null(advanced_results$reliability$day_parameters)) {\n  day_params <- advanced_results$reliability$day_parameters\n\n  plot_bland_altman(\n    day1 = day_params$slope_day1,\n    day2 = day_params$slope_day2,\n    title = \"Bland-Altman: Velocity-RIR Slope Reliability\",\n    y_label = \"(m/s per RIR)\"\n  )\n}\n```\n\n::: {.cell-output-display}\n![Bland-Altman Plot for Velocity-RIR Slopes: Assesses systematic bias and limits of agreement between testing days.](deadlift_study_files/figure-html/fig-bland-altman-slope-1.png){#fig-bland-altman-slope width=100%}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nif (!is.null(advanced_results) && !is.null(advanced_results$reliability$day_parameters)) {\n  day_params <- advanced_results$reliability$day_parameters\n\n  plot_bland_altman(\n    day1 = day_params$mvt_day1,\n    day2 = day_params$mvt_day2,\n    title = \"Bland-Altman: MVT Reliability\",\n    y_label = \"(m/s)\"\n  )\n}\n```\n\n::: {.cell-output-display}\n![Bland-Altman Plot for MVT: Shows day-to-day variability in minimum velocity threshold estimates.](deadlift_study_files/figure-html/fig-bland-altman-mvt-1.png){#fig-bland-altman-mvt width=100%}\n:::\n:::\n\n\n**Practical Recommendation**: The moderate reliability suggests that velocity profiles are reasonably stable but not perfect. **Recalibrate every 2-4 weeks** or after significant training blocks, illness, or competition.\n\n### 4.3 Linear vs Polynomial Models\n\n#### The Question\n\nThe velocity-RIR relationship could be linear (constant velocity loss per rep) or curvilinear (accelerating velocity loss near failure). Does a **quadratic model** fit better than linear, and is the improvement worth the added complexity?\n\n#### The Method\n\nFor each participant, we fit both models and compared them:\n\n1. **Linear**: Velocity = β₀ + β₁ × RIR\n2. **Quadratic**: Velocity = β₀ + β₁ × RIR + β₂ × RIR²\n\n**Model Selection Criteria:**\n\n- **AIC (Akaike Information Criterion)**: Balances fit against complexity; lower is better\n- **R² improvement**: How much additional variance is explained by the quadratic term\n\n**Decision Rule:** Quadratic is \"better\" if AIC is lower by ≥2 points (meaningful improvement) AND R² improves by ≥0.01.\n\n#### The Finding\n\n\n\n```{.r .cell-code}\nif (!is.null(advanced_results)) {\n  poly <- advanced_results$polynomial_comparison\n  cat(\"**Model Comparison Results:**\\n\\n\")\n  cat(\"| Metric | Value |\\n\")\n  cat(\"|--------|-------|\\n\")\n  cat(sprintf(\"| Participants analyzed | %d |\\n\", poly$best_model_summary$n_participants))\n  cat(sprintf(\"| Linear model preferred | %d (%.0f%%) |\\n\",\n              poly$best_model_summary$n_linear_best,\n              100 - poly$best_model_summary$pct_quad_best))\n  cat(sprintf(\"| Quadratic model preferred | %d (%.0f%%) |\\n\",\n              poly$best_model_summary$n_quad_best,\n              poly$best_model_summary$pct_quad_best))\n  cat(sprintf(\"| Average R² improvement (quadratic) | %.4f |\\n\", poly$best_model_summary$avg_r2_improvement))\n}\n```\n\n**Model Comparison Results:**\n\n| Metric | Value |\n|--------|-------|\n| Participants analyzed | 19 |\n| Linear model preferred | 14 (74%) |\n| Quadratic model preferred | 5 (26%) |\n| Average R² improvement (quadratic) | 0.0164 |\n\n::: {.cell}\n\n```{.r .cell-code}\nif (!is.null(advanced_results) && !is.null(advanced_results$polynomial_comparison$individual_results)) {\n  ind_results <- advanced_results$polynomial_comparison$individual_results\n\n  ggplot(ind_results, aes(x = reorder(id, delta_aic), y = delta_aic, fill = best_model)) +\n    geom_col() +\n    geom_hline(yintercept = -2, linetype = \"dashed\", color = COLORS$secondary) +\n    geom_hline(yintercept = 2, linetype = \"dashed\", color = COLORS$secondary) +\n    coord_flip() +\n    labs(x = \"Participant\", y = \"ΔAIC (Quadratic - Linear)\",\n         title = \"Model Comparison by Participant\",\n         subtitle = \"Negative values favor quadratic model\",\n         fill = \"Best Model\") +\n    scale_fill_manual(values = c(\"linear\" = COLORS$primary, \"quadratic\" = COLORS$tertiary))\n}\n```\n\n::: {.cell-output-display}\n![AIC comparison between linear and quadratic models by participant](deadlift_study_files/figure-html/fig-model-aic-1.png){#fig-model-aic width=100%}\n:::\n:::\n\n\n**Interpretation**: For the majority of participants, the **linear model is sufficient**. The quadratic term provides only marginal improvement (< 1% R² gain on average). This simplifies practical application---coaches can use a simple linear relationship without sacrificing meaningful accuracy.\n\n**Practical Implication**: Use linear velocity tables. The small theoretical improvement from polynomial models is not worth the added complexity for training prescription.\n\n### 4.4 Velocity Decay Patterns\n\n#### The Question\n\nDoes velocity loss occur at a **constant rate** throughout a set, or does it **accelerate** as failure approaches? Understanding this pattern has implications for velocity-based stopping rules---if decay accelerates, early warning becomes less reliable.\n\n#### The Method\n\nWe analyzed within-set velocity decay by:\n\n1. **Phase comparison**: Comparing velocity loss in the first half vs. second half of each set\n2. **Statistical test**: Paired t-test to determine if second-half decay is significantly greater\n\n**Hypotheses:**\n\n- H₀: Decay rate is constant (first half = second half)\n- H₁: Decay accelerates (second half > first half)\n\n#### The Finding\n\n\n\n```{.r .cell-code}\nif (!is.null(advanced_results) && !is.null(advanced_results$velocity_decay)) {\n  decay <- advanced_results$velocity_decay\n  cat(\"**Velocity Decay Results:**\\n\\n\")\n  if (!is.null(decay$phase_decay)) {\n    cat(\"| Set Phase | Velocity Loss (m/s per rep) |\\n\")\n    cat(\"|-----------|-----------------------------|\\n\")\n    cat(sprintf(\"| First half | %.4f |\\n\", as.numeric(decay$phase_decay$first_half_decay)))\n    cat(sprintf(\"| Second half | %.4f |\\n\", as.numeric(decay$phase_decay$second_half_decay)))\n    cat(\"\\n\")\n  }\n  if (!is.null(decay$decay_acceleration)) {\n    if (isTRUE(decay$decay_acceleration$accelerating)) {\n      cat(sprintf(\"**Statistical Test:** Decay significantly accelerates near failure (p = %s)\\n\\n\",\n                  format(decay$decay_acceleration$p_value, digits = 3)))\n      cat(\"The velocity-fatigue curve is **exponential**, not linear. This means:\\n\\n\")\n      cat(\"1. Early reps provide less warning of impending failure\\n\")\n      cat(\"2. The final 2-3 reps show rapid velocity decline\\n\")\n      cat(\"3. Conservative velocity thresholds are advisable\\n\")\n    } else {\n      cat(\"**Statistical Test:** Decay rate is approximately constant throughout the set.\\n\\n\")\n      cat(\"The linear model adequately describes velocity loss across reps.\\n\")\n    }\n  }\n} else {\n  cat(\"*Velocity decay analysis will be available after running the advanced analysis pipeline.*\\n\")\n}\n```\n\n**Velocity Decay Results:**\n\n**Statistical Test:** Decay significantly accelerates near failure (p = 0.035)\n\nThe velocity-fatigue curve is **exponential**, not linear. This means:\n\n1. Early reps provide less warning of impending failure\n2. The final 2-3 reps show rapid velocity decline\n3. Conservative velocity thresholds are advisable\n\n::: {.cell}\n\n```{.r .cell-code}\nif (!is.null(data) && \"set_id\" %in% names(data)) {\n  # Calculate rep number within each set based on RIR\n  traj_data <- data\n  traj_data$rep_num <- ave(traj_data$rir, traj_data$set_id, FUN = function(x) max(x) - x + 1)\n\n  ggplot(traj_data, aes(x = rep_num, y = mean_velocity, group = set_id)) +\n    geom_line(alpha = 0.3, color = COLORS$primary) +\n    stat_summary(aes(group = 1), fun = mean, geom = \"line\",\n                 color = COLORS$secondary, linewidth = 1.5) +\n    stat_summary(aes(group = 1), fun = mean, geom = \"point\",\n                 color = COLORS$secondary, size = 3) +\n    labs(x = \"Rep Number\", y = \"Mean Velocity (m/s)\",\n         title = \"Velocity Trajectories Across Sets\",\n         subtitle = \"Individual sets (blue) with population mean (red)\")\n}\n```\n:::\n\n\n**Practical Implication**: Because velocity loss accelerates near failure, athletes should use **conservative stopping thresholds**. If targeting RIR 2, consider stopping at the RIR 3 threshold to account for the acceleration effect.\n\n### 4.5 First-Rep Failure Prediction\n\n#### The Question\n\nCan we predict **how many reps until failure** from just the first 1-3 repetitions? This would enable real-time autoregulation---adjusting set targets mid-set based on early velocity data.\n\n#### The Method\n\nWe built a prediction model using **Leave-One-Out Cross-Validation (LOOCV)** [@hastie2009]:\n\n1. **Predictor**: First-rep velocity (m/s)\n2. **Outcome**: Total reps to failure\n3. **Model**: Linear regression (velocity → rep capacity)\n4. **Validation**: Each set held out once; model trained on remaining sets\n\n**Why LOOCV?** It provides an unbiased estimate of out-of-sample prediction error. Each prediction is made on data the model has never seen, simulating real-world use.\n\n**Metrics:**\n\n- **MAE**: Average absolute error in rep prediction (in reps)\n- **RMSE**: Root mean squared error (penalizes large errors)\n- **R²**: Proportion of variance in rep capacity explained by first-rep velocity\n\n#### The Finding\n\n\n\n```{.r .cell-code}\nif (!is.null(advanced_results)) {\n  pred <- advanced_results$failure_prediction\n  cat(\"**Prediction Accuracy (Leave-One-Out CV):**\\n\\n\")\n  cat(\"| Metric | Value | Interpretation |\\n\")\n  cat(\"|--------|-------|----------------|\\n\")\n  cat(sprintf(\"| MAE | %.2f reps | Average prediction error |\\n\", pred$cv_results$mae))\n  cat(sprintf(\"| RMSE | %.2f reps | Error penalizing outliers |\\n\", pred$cv_results$rmse))\n  cat(sprintf(\"| R² | %.3f | Variance explained |\\n\", pred$cv_results$r2))\n}\n```\n\n**Prediction Accuracy (Leave-One-Out CV):**\n\n| Metric | Value | Interpretation |\n|--------|-------|----------------|\n| MAE | 1.29 reps | Average prediction error |\n| RMSE | 1.53 reps | Error penalizing outliers |\n| R² | 0.065 | Variance explained |\n\n::: {#tbl-prediction-lookup .cell tbl-cap='Practical Lookup Table: First Rep Velocity → Predicted Reps'}\n\n```{.r .cell-code}\nif (!is.null(advanced_results) && !is.null(advanced_results$failure_prediction$lookup_table)) {\n  lookup <- advanced_results$failure_prediction$lookup_table\n  format_table(lookup, digits = 1,\n        col.names = c(\"First Rep Velocity (m/s)\", \"Predicted Reps\", \"Lower 95%\", \"Upper 95%\"))\n}\n```\n\n::: {.cell-output-display}\n\n\n| First Rep Velocity (m/s)| Predicted Reps| Lower 95%| Upper 95%|\n|------------------------:|--------------:|---------:|---------:|\n|                      0.1|            4.9|       1.8|       8.0|\n|                      0.2|            5.2|       2.1|       8.3|\n|                      0.2|            5.4|       2.4|       8.5|\n|                      0.3|            5.7|       2.6|       8.7|\n|                      0.3|            6.0|       2.9|       9.0|\n|                      0.4|            6.2|       3.2|       9.3|\n|                      0.5|            6.5|       3.4|       9.6|\n|                      0.5|            6.8|       3.7|       9.9|\n|                      0.6|            7.0|       3.9|      10.2|\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nif (!is.null(data)) {\n  # Prepare set-level data\n  set_data <- do.call(rbind, lapply(unique(data$set_id), function(sid) {\n    s <- data[data$set_id == sid, ]\n    s <- s[order(s$rep_number), ]\n    if (nrow(s) < 1) return(NULL)\n    data.frame(\n      set_id = sid,\n      v1 = s$mean_velocity[1],\n      reps_to_failure = s$reps_to_failure[1],\n      load_percentage = s$load_percentage[1]\n    )\n  }))\n\n  if (!is.null(set_data) && nrow(set_data) > 0) {\n    ggplot(set_data, aes(x = v1, y = reps_to_failure, color = load_percentage)) +\n      geom_point(size = 3, alpha = 0.7) +\n      geom_smooth(method = \"lm\", se = TRUE, aes(group = 1), color = \"black\") +\n      labs(x = \"First Rep Velocity (m/s)\", y = \"Total Reps to Failure\",\n           title = \"Relationship Between First Rep Velocity and Set Capacity\",\n           color = \"Load\") +\n      scale_color_load()\n  }\n}\n```\n:::\n\n\n**Interpretation**: A MAE of ~1-2 reps means that on average, first-rep velocity predicts failure within 1-2 repetitions. This is practically useful for autoregulation---if the model predicts 6 reps to failure, expect 5-7 reps.\n\n**Practical Application**: After the first rep, check velocity against the prediction table. If velocity is unusually low (predicting fewer reps than planned), consider reducing set volume. If unusually high, you may have more capacity than expected.\n\n---\n\n### 4.6 Model Specification: A Systematic Approach {#sec-model-spec}\n\nBefore presenting model comparisons and validation, we document the rationale behind our modeling choices following established GLM principles. Each decision point has explicit criteria.\n\n#### 4.6.1 Distribution Choice (Random Component)\n\n**The Question**: Which probability distribution best describes our outcome variable?\n\nOur outcome (mean concentric velocity) is:\n\n- **Continuous** (not binary or count data)\n- **Bounded below by 0** (physical constraint: velocity cannot be negative)\n- **Approximately normal** within participants after accounting for RIR effects\n\n\n\n```{.r .cell-code}\nif (!is.null(lmm_results) && !is.null(lmm_results$models) && !is.null(lmm_results$models$random_slope)) {\n  # Check residual distribution from the fitted model\n  model <- lmm_results$models$random_slope\n  resids <- as.numeric(residuals(model))\n\n  if (length(resids) > 0 && is.numeric(resids)) {\n    # Shapiro-Wilk test (for formal assessment) - limit to 5000 obs\n    sw_test <- shapiro.test(resids[1:min(5000, length(resids))])\n\n    # Calculate skewness\n    skewness <- mean((resids - mean(resids))^3) / (sd(resids)^3)\n\n    cat(sprintf(\"**Residual Distribution Assessment:**\\n\\n\"))\n    cat(sprintf(\"- Skewness: %.3f (ideal: 0; acceptable: |skew| < 1)\\n\", skewness))\n    cat(sprintf(\"- Shapiro-Wilk statistic: %.4f\\n\", sw_test$statistic))\n\n    if (abs(skewness) < 0.5) {\n      cat(\"\\n**Decision**: Skewness is minimal. Use **Gaussian (normal) family** with standard LMM.\\n\")\n    } else if (abs(skewness) < 1) {\n      cat(\"\\n**Decision**: Slight skewness detected but within acceptable range. Gaussian family appropriate.\\n\")\n    } else {\n      cat(\"\\n**Decision**: Notable skewness. Consider Gamma family or log transformation.\\n\")\n    }\n  }\n}\n```\n\n\n::: {.callout-tip collapse=\"true\"}\n## Why Not Use Gamma Distribution?\n\nGamma distributions are appropriate for strictly positive, right-skewed continuous data. Our velocity data, while bounded at 0, shows approximately symmetric residuals after accounting for fixed effects. The LMM's random effects absorb much of the between-participant variation that might otherwise induce skewness.\n\nAdditionally, Gamma GLMs with log link would require exponentiating coefficients for interpretation, adding complexity without meaningful gain in model fit.\n:::\n\n#### 4.6.2 Link Function\n\n**The Question**: How should we connect predictors to the expected outcome?\n\n\n\n```{.r .cell-code}\nif (!is.null(lmm_results) && !is.null(lmm_results$models) && !is.null(lmm_results$models$random_slope)) {\n  # Check linearity by looking at residuals vs fitted\n  model <- lmm_results$models$random_slope\n  resids <- as.numeric(residuals(model))\n  fitted_vals <- as.numeric(fitted(model))\n\n  if (length(resids) > 0 && length(fitted_vals) > 0) {\n    # Simple correlation as linearity check\n    residual_fitted_cor <- cor(fitted_vals, resids^2)\n\n    cat(\"**Linearity Assessment:**\\n\\n\")\n    cat(sprintf(\"- Correlation between fitted values and squared residuals: %.3f\\n\", residual_fitted_cor))\n\n    if (abs(residual_fitted_cor) < 0.2) {\n      cat(\"\\n**Decision**: Residuals show no systematic curvature with fitted values.\\n\")\n      cat(\"Use **identity link** (no transformation needed).\\n\")\n    } else {\n      cat(\"\\n**Decision**: Some curvature detected. Consider polynomial terms or log link.\\n\")\n    }\n  }\n}\n```\n\n\nThe identity link means our coefficients represent **direct changes in m/s per unit RIR change**, which is maximally interpretable for practitioners.\n\n#### 4.6.3 Random Effects Structure Decision\n\n**Decision Criteria** (following @barr2013 recommendations):\n\n| Criterion | Threshold | Our Data | Decision |\n|-----------|-----------|----------|----------|\n| ICC (baseline variation) | > 0.05 | 0.67 | Random intercepts ✓ |\n| LRT for random slopes | p < 0.05 | p < 0.001 | Random slopes ✓ |\n| Bayes Factor | BF > 10 (strong) | decisive | Random slopes ✓ |\n| Obs per participant | ≥ 10 | ~21 | Design supports ✓ |\n\n**All criteria favor random slopes model.**\n\n#### 4.6.4 Fixed Effects Selection\n\n**The Question**: Which predictors should be included in the model?\n\nWe use **Bayes Factors** as the primary comparison metric (with AIC/BIC as secondary):\n\n| Comparison | BF | Interpretation | Decision |\n|------------|-----|----------------|----------|\n| Base model (RIR only) | — | Reference | — |\n| + Load effect | ~0.89 | No evidence for load | Exclude |\n| + RIR × Load interaction | — | Evidence against | Exclude |\n\n::: {.callout-note}\n## Model Selection Priority\n\nWhen comparison metrics disagree, we follow this hierarchy:\n\n1. **Bayes Factor** (primary): Directly quantifies evidence for/against models\n2. **AIC** (secondary): Better for prediction-focused goals\n3. **BIC** (tertiary): More conservative, penalizes complexity\n4. **LRT p-value**: Only for nested model comparison\n\nIf BF > 10 (strong evidence), we accept that model regardless of AIC/BIC.\n:::\n\n#### 4.6.5 Final Model Specification\n\nBased on the systematic assessment above:\n\n**Model**: `mean_velocity ~ rir + (1 + rir | id)`\n\n- **Family**: Gaussian (normal residuals confirmed)\n- **Link**: Identity (linear relationship, direct interpretation)\n- **Random intercepts**: Each participant has their own baseline velocity\n- **Random slopes**: Each participant has their own velocity-RIR relationship\n- **Fixed effects**: RIR only (load effect not supported by evidence)\n\n---\n\n## 5. Model Validation and Robustness\n\nThis section presents rigorous statistical validation of the LMM approach, including model comparisons, robustness checks, and sensitivity analyses.\n\n### 5.1 LMM Model Specification Comparison\n\n#### The Question\n\nWhich random effects structure best captures the hierarchical nature of the data? Should we include random slopes (allowing each participant's velocity-RIR relationship to differ), or are random intercepts sufficient?\n\n#### The Method\n\nWe compared nested models using **likelihood ratio tests** and information criteria:\n\n1. **Random Intercept Only**: Velocity ~ RIR + (1 | participant)\n   - Allows mean velocity to differ by participant\n   - Assumes same velocity-RIR slope for everyone\n\n2. **Random Intercept + Slope**: Velocity ~ RIR + (1 + RIR | participant)\n   - Allows both mean velocity AND slope to differ\n   - More flexible, captures individual differences in fatigue sensitivity\n\n**Comparison Metrics:**\n\n- **LRT (Likelihood Ratio Test)**: Compares nested models; significant p-value favors complex model\n- **AIC/BIC**: Information criteria; lower is better (BIC penalizes complexity more)\n- **R² (Marginal vs Conditional)**: Fixed effects only (R²m) vs fixed + random (R²c) [@nakagawa2013]\n\n#### Why Random Slopes? A Three-Step Decision Framework\n\nBefore looking at formal comparisons, we should justify *why* random slopes are theoretically appropriate. This follows a principled three-step decision process:\n\n**Step 1: Do individuals differ in their baseline?**\n\nAthletes have different baseline velocities at any given RIR---some are inherently faster, others slower. This justifies **random intercepts**: each athlete gets their own starting point.\n\n\n\n```{.r .cell-code}\nif (!is.null(data)) {\n  # Calculate mean velocity per participant\n  participant_means <- aggregate(mean_velocity ~ id, data = data, FUN = mean)\n  velocity_range <- diff(range(participant_means$mean_velocity))\n\n  cat(sprintf(\"*Evidence:* Individual mean velocities range from %.3f to %.3f m/s (spread = %.3f m/s)\\n\",\n              min(participant_means$mean_velocity), max(participant_means$mean_velocity), velocity_range))\n}\n```\n\n*Evidence:* Individual mean velocities range from 0.227 to 0.418 m/s (spread = 0.191 m/s)\n\n\n**Step 2: Do individuals differ in their response to the predictor?**\n\nThe key question: does the velocity-RIR relationship vary across athletes? If some athletes show steep velocity decline while others show gradual decline, we need **random slopes**.\n\n\n\n```{.r .cell-code}\nif (!is.null(data)) {\n  # Calculate individual slopes\n  individual_slopes <- do.call(rbind, lapply(unique(data$id), function(pid) {\n    p_data <- data[data$id == pid, ]\n    if (nrow(p_data) >= 3) {\n      m <- lm(mean_velocity ~ rir, data = p_data)\n      data.frame(id = pid, slope = coef(m)[\"rir\"])\n    }\n  }))\n\n  if (nrow(individual_slopes) > 0) {\n    slope_range <- diff(range(individual_slopes$slope, na.rm = TRUE))\n    slope_cv <- sd(individual_slopes$slope, na.rm = TRUE) / abs(mean(individual_slopes$slope, na.rm = TRUE)) * 100\n\n    cat(sprintf(\"*Evidence:* Individual slopes range from %.4f to %.4f m/s per RIR (CV = %.1f%%)\\n\",\n                min(individual_slopes$slope, na.rm = TRUE),\n                max(individual_slopes$slope, na.rm = TRUE),\n                slope_cv))\n    cat(\"\\nThis substantial variation justifies random slopes.\\n\")\n  }\n}\n```\n\n*Evidence:* Individual slopes range from 0.0059 to 0.0668 m/s per RIR (CV = 51.5%)\n\nThis substantial variation justifies random slopes.\n\n\n**Step 3: Does the design support random slopes?**\n\nRandom slopes require multiple observations per participant at different predictor values. With 406/19 = ~21 observations per athlete across different RIR levels, we have sufficient data to estimate individual slopes reliably.\n\n**Decision:** All three conditions are met → **Random slopes are appropriate and necessary.**\n\n#### The Finding\n\n\n\n```{.r .cell-code}\nif (!is.null(lmm_results) && !is.null(lmm_results$model_comparison)) {\n  mc <- lmm_results$model_comparison\n\n  # Use comparison_table which contains all models\n  if (!is.null(mc$comparison_table)) {\n    ct <- mc$comparison_table\n\n    cat(\"**Model Comparison Results:**\\n\\n\")\n    cat(\"| Model | AIC | BIC | ΔAIC | R²m | R²c |\\n\")\n    cat(\"|-------|-----|-----|------|-----|-----|\\n\")\n\n    for (i in seq_len(nrow(ct))) {\n      cat(sprintf(\"| %s | %.1f | %.1f | %.1f | %.3f | %.3f |\\n\",\n                  ct$model[i], ct$AIC[i], ct$BIC[i], ct$delta_AIC[i],\n                  ct$R2_marginal[i], ct$R2_conditional[i]))\n    }\n\n    # Find best model\n    best_idx <- which.min(ct$AIC)\n    cat(sprintf(\"\\n**Best Model (lowest AIC):** %s\\n\", ct$model[best_idx]))\n  }\n} else {\n  cat(\"*Model comparison results will be available after running the full analysis pipeline.*\\n\\n\")\n}\n```\n\n**Model Comparison Results:**\n\n| Model | AIC | BIC | ΔAIC | R²m | R²c |\n|-------|-----|-----|------|-----|-----|\n| base | -1046.7 | -1030.7 | 62.6 | 0.339 | 0.616 |\n| random_slope | -1109.3 | -1085.2 | 0.0 | 0.435 | 0.639 |\n| with_load | -1101.1 | -1073.1 | 8.1 | 0.436 | 0.639 |\n| with_day | -1091.5 | -1059.4 | 17.8 | 0.438 | 0.639 |\n| interaction | -1105.6 | -1073.6 | 3.6 | 0.452 | 0.654 |\n| full | -1081.3 | -1037.2 | 28.0 | 0.458 | 0.658 |\n\n**Best Model (lowest AIC):** random_slope\n\n\n#### Bayes Factor Analysis: Quantifying the Evidence\n\nWhile AIC/BIC differences tell us which model fits better, they don't directly quantify *how much* evidence we have. **Bayes factors** provide an intuitive metric: how many times more likely is the data under one model versus another?\n\n\n\n```{.r .cell-code}\nif (!is.null(lmm_results) && !is.null(lmm_results$model_comparison) &&\n    !is.null(lmm_results$model_comparison$models)) {\n\n  models <- lmm_results$model_comparison$models\n\n  # Compare base vs random slope using ModelComparator\n  if (\"base\" %in% names(models) && \"random_slope\" %in% names(models)) {\n    comparison <- model_comparator$compare(\n      models$base, models$random_slope,\n      model1_name = \"Random Intercept Only\",\n      model2_name = \"Random Intercept + Slope\",\n      nested = TRUE\n    )\n\n    # Calculate Bayes factor from BIC\n    bic_diff <- BIC(models$base) - BIC(models$random_slope)\n    bf <- exp(bic_diff / 2)\n\n    cat(\"**Bayes Factor Analysis (Random Slope vs. Intercept-Only):**\\n\\n\")\n    cat(\"| Metric | Value | Interpretation |\\n\")\n    cat(\"|--------|-------|----------------|\\n\")\n    cat(sprintf(\"| BIC difference | %.1f | %s |\\n\", bic_diff,\n                ifelse(bic_diff > 0, \"Favors random slope\", \"Favors intercept-only\")))\n    cat(sprintf(\"| Bayes Factor | %.1f | %s |\\n\", bf,\n                model_comparator$interpret_bayes_factor(bf)))\n\n    if (!is.null(comparison$lrt_pvalue)) {\n      cat(sprintf(\"| LRT χ² | %.2f (df=%.0f) | p %s |\\n\",\n                  comparison$lrt_chisq, comparison$lrt_df,\n                  ifelse(comparison$lrt_pvalue < 0.001, \"< 0.001\",\n                         sprintf(\"= %.3f\", comparison$lrt_pvalue))))\n    }\n\n    cat(\"\\n**Interpretation Guide:**\\n\\n\")\n    cat(\"- **BF 1-3**: Weak/anecdotal evidence\\n\")\n    cat(\"- **BF 3-10**: Moderate evidence\\n\")\n    cat(\"- **BF 10-30**: Strong evidence\\n\")\n    cat(\"- **BF 30-100**: Very strong evidence\\n\")\n    cat(\"- **BF >100**: Decisive evidence\\n\\n\")\n\n    if (bf > 10) {\n      cat(sprintf(\"With BF = %.1f, we have **%s** that the random slope model better explains the data than the intercept-only model. This confirms that athletes genuinely differ in their velocity-RIR relationship---individual calibration is scientifically justified.\\n\",\n                  bf, model_comparator$interpret_bayes_factor(bf)))\n    }\n  }\n} else {\n  cat(\"*Bayes factor analysis will be available after running the full LMM pipeline.*\\n\")\n}\n```\n\n*Bayes factor analysis will be available after running the full LMM pipeline.*\n\n\n**Interpretation**: The random slope model typically shows substantially higher conditional R² and lower AIC/BIC, confirming that individual differences in the velocity-RIR relationship are real and important to model.\n\n### 5.2 Variance Components and Clustering\n\nUnderstanding how variance is partitioned between and within participants helps quantify the importance of individual differences and the degree of non-independence in our data.\n\n#### Variance Decomposition\n\n\n\n```{.r .cell-code}\nif (!is.null(lmm_results) && !is.null(lmm_results$best_model) &&\n    !is.null(lmm_results$best_model$model)) {\n\n  mod <- lmm_results$best_model$model\n  vc <- as.data.frame(lme4::VarCorr(mod))\n\n  # Extract variance components\n  var_intercept <- vc[vc$grp == \"id\" & vc$var1 == \"(Intercept)\" & is.na(vc$var2), \"vcov\"]\n  var_slope <- vc[vc$grp == \"id\" & vc$var1 == \"rir\" & is.na(vc$var2), \"vcov\"]\n  var_residual <- vc[vc$grp == \"Residual\", \"vcov\"]\n\n  # Calculate ICC for intercept\n  icc <- var_intercept / (var_intercept + var_residual)\n\n  # Calculate average cluster size\n  n_obs <- nrow(data)\n  n_participants <- deadlift_results$summary$n_participants\n  avg_cluster_size <- n_obs / n_participants\n\n  # Design effect\n  design_effect <- 1 + (avg_cluster_size - 1) * icc\n  effective_n <- n_obs / design_effect\n\n  cat(\"**Variance Components:**\\n\\n\")\n  cat(\"| Component | Variance | SD | % of Total |\\n\")\n  cat(\"|-----------|----------|-----|------------|\\n\")\n\n  total_var <- var_intercept + var_residual\n  cat(sprintf(\"| Between-participant (Intercept) | %.6f | %.4f | %.1f%% |\\n\",\n              var_intercept, sqrt(var_intercept), 100 * var_intercept / total_var))\n  cat(sprintf(\"| Within-participant (Residual) | %.6f | %.4f | %.1f%% |\\n\",\n              var_residual, sqrt(var_residual), 100 * var_residual / total_var))\n\n  if (!is.na(var_slope)) {\n    cat(sprintf(\"| Slope variation | %.6f | %.4f | - |\\n\",\n                var_slope, sqrt(var_slope)))\n  }\n\n  cat(\"\\n**Intraclass Correlation (ICC):**\\n\\n\")\n  cat(sprintf(\"- ICC = %.3f (%.1f%% of velocity variance is between participants)\\n\", icc, icc * 100))\n  cat(\"- Interpretation: \", ifelse(icc < 0.1, \"Low clustering\",\n                            ifelse(icc < 0.25, \"Moderate clustering\",\n                            ifelse(icc < 0.5, \"Substantial clustering\", \"High clustering\"))), \"\\n\")\n\n  cat(\"\\n**Design Effect and Effective Sample Size:**\\n\\n\")\n  cat(sprintf(\"- Average cluster size: %.1f observations per participant\\n\", avg_cluster_size))\n  cat(sprintf(\"- Design effect: %.2f\\n\", design_effect))\n  cat(sprintf(\"- Effective sample size: %.0f (vs. %d total observations)\\n\", effective_n, n_obs))\n  cat(\"\\n*The design effect indicates that ignoring clustering would make our data appear ~\",\n      sprintf(\"%.0f\", design_effect), \"x more informative than it actually is.*\\n\")\n\n} else {\n  cat(\"*Variance components will be available after running the LMM analysis pipeline.*\\n\")\n}\n```\n\n**Variance Components:**\n\n| Component | Variance | SD | % of Total |\n|-----------|----------|-----|------------|\n| Between-participant (Intercept) | 0.001445 | 0.0380 | 33.2% |\n| Within-participant (Residual) | 0.002907 | 0.0539 | 66.8% |\n| Slope variation | 0.000191 | 0.0138 | - |\n\n**Intraclass Correlation (ICC):**\n\n- ICC = 0.332 (33.2% of velocity variance is between participants)\n- Interpretation:  Substantial clustering \n\n**Design Effect and Effective Sample Size:**\n\n- Average cluster size: 21.4 observations per participant\n- Design effect: 7.76\n- Effective sample size: 52 (vs. 406 total observations)\n\n*The design effect indicates that ignoring clustering would make our data appear ~ 8 x more informative than it actually is.*\n\n\n#### Why This Matters\n\nThe ICC tells us what proportion of total variance in velocity is due to stable between-person differences. A high ICC (>0.25) means:\n\n1. **Athletes differ systematically**---some are consistently faster or slower\n2. **Mixed models are essential**---ignoring clustering would severely bias inference\n3. **Individual calibration adds value**---the random effects capture real individual differences\n\nThe design effect quantifies the \"price\" of non-independence: our 406 observations provide the same precision as only 57 independent observations would.\n\n#### Effect Size: How Large is the RIR Effect?\n\nBeyond statistical significance, we want to know: **how practically meaningful is the velocity change as athletes approach failure?** Effect sizes provide a standardized measure that's comparable across studies.\n\n\n\n```{.r .cell-code}\nif (!is.null(lmm_results) && !is.null(lmm_results$best_model)) {\n  mod <- lmm_results$best_model$model\n  fe <- lme4::fixef(mod)\n  rir_slope <- fe[\"rir\"]\n\n  # Calculate velocity change from RIR 5 to RIR 0 (typical training range)\n  velocity_change <- rir_slope * 5  # 5 RIR difference\n\n  # Calculate Cohen's d using pooled SD of velocity\n  pooled_sd <- sd(data$mean_velocity)\n  cohens_d <- abs(velocity_change) / pooled_sd\n\n  # R² effect size interpretation (marginal)\n  if (!is.null(lmm_results$model_comparison)) {\n    r2_marginal <- lmm_results$model_comparison$comparison_table$R2_marginal[\n      lmm_results$model_comparison$comparison_table$model == \"random_slope\"\n    ]\n    r2_conditional <- lmm_results$model_comparison$comparison_table$R2_conditional[\n      lmm_results$model_comparison$comparison_table$model == \"random_slope\"\n    ]\n  } else {\n    r2_marginal <- NA\n    r2_conditional <- NA\n  }\n\n  cat(\"**Effect Size Summary:**\\n\\n\")\n  cat(\"| Metric | Value | Interpretation |\\n\")\n  cat(\"|--------|-------|----------------|\\n\")\n  cat(sprintf(\"| Velocity change (RIR 5→0) | %.3f m/s | Practical difference athletes experience |\\n\", abs(velocity_change)))\n  cat(sprintf(\"| Cohen's d | %.2f | %s effect |\\n\", cohens_d,\n              ifelse(cohens_d < 0.2, \"Small\", ifelse(cohens_d < 0.5, \"Small-medium\",\n              ifelse(cohens_d < 0.8, \"Medium\", \"Large\")))))\n  cat(sprintf(\"| R² (marginal) | %.1f%% | Variance explained by RIR alone |\\n\", r2_marginal * 100))\n  cat(sprintf(\"| R² (conditional) | %.1f%% | Variance explained by RIR + individual differences |\\n\", r2_conditional * 100))\n\n  cat(\"\\n**Interpretation:**\\n\\n\")\n  cat(\"- **Cohen's d =\", sprintf(\"%.2f\", cohens_d), \"**: This represents a\",\n      ifelse(cohens_d >= 0.8, \"large\", ifelse(cohens_d >= 0.5, \"medium\", \"small-to-medium\")),\n      \"effect---athletes experience a velocity decline of\", sprintf(\"%.2f\", cohens_d),\n      \"standard deviations as they approach failure.\\n\")\n  cat(\"- **R² marginal vs conditional gap**:\", sprintf(\"%.0f%%\", (r2_conditional - r2_marginal) * 100),\n      \"of variance is explained by individual differences beyond the main RIR effect.\\n\")\n  cat(\"- This gap justifies individual calibration: the 'same' RIR means different velocities for different athletes.\\n\")\n}\n```\n\n**Effect Size Summary:**\n\n| Metric | Value | Interpretation |\n|--------|-------|----------------|\n| Velocity change (RIR 5→0) | 0.146 m/s | Practical difference athletes experience |\n| Cohen's d | 1.52 | Large effect |\n| R² (marginal) | 43.5% | Variance explained by RIR alone |\n| R² (conditional) | 63.9% | Variance explained by RIR + individual differences |\n\n**Interpretation:**\n\n- **Cohen's d = 1.52 **: This represents a large effect---athletes experience a velocity decline of 1.52 standard deviations as they approach failure.\n- **R² marginal vs conditional gap**: 20% of variance is explained by individual differences beyond the main RIR effect.\n- This gap justifies individual calibration: the 'same' RIR means different velocities for different athletes.\n\n\n#### Caterpillar Plot: Visualizing Individual Differences\n\nThe **caterpillar plot** shows each athlete's deviation from the population average (the random effects, or BLUPs), ordered by magnitude. Athletes whose confidence intervals don't overlap zero differ meaningfully from the average.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Using OOP ModelPlotter class (CLAUDE.md principles)\nif (!is.null(lmm_results) && !is.null(lmm_results$best_model) &&\n    !is.null(lmm_results$best_model$model)) {\n\n  model_plotter$plot_caterpillar_dual(\n    model = lmm_results$best_model$model,\n    title = \"Individual Random Effects: Who Differs from the Population?\"\n  )\n}\n```\n\n::: {.cell-output-display}\n![Caterpillar Plot: Random effects (BLUPs) with 95% confidence intervals. Athletes are ordered by their random intercept; intervals not crossing zero indicate meaningful deviation from population average.](deadlift_study_files/figure-html/fig-caterpillar-1.png){#fig-caterpillar width=100%}\n:::\n:::\n\n\n**Reading the caterpillar plot:**\n\n- **Left panel (Intercepts)**: Athletes above/below the dashed line (zero) have higher/lower baseline velocities than average\n- **Right panel (Slopes)**: Athletes with more positive slopes show greater velocity increase per RIR (i.e., steeper decline toward failure)\n- **Confidence intervals**: Wide intervals indicate more uncertainty in that athlete's estimate (often due to fewer observations)\n\nThis visualization directly supports our core finding: **athletes vary substantially in both their baseline velocity and their fatigue sensitivity**, justifying individual calibration for VBT.\n\n### 5.3 Robustness Checks: Validation Pit Stops\n\n#### The Pit Stop Philosophy\n\nThink of robustness checks like **pit stops in a race**---they're not emergency repairs for a broken car, but planned checkpoints to confirm everything is working as expected. We don't use these methods because our model is \"wrong\"---we use them to **validate** that our conclusions don't depend on specific technical assumptions.\n\nThe key question isn't \"do my assumptions hold perfectly?\" (they never do). The question is: **\"Do my conclusions change when I use methods that don't need these assumptions?\"**\n\nIf the answer is \"no,\" then any assumption violations are academically interesting but practically irrelevant.\n\n**Our three validation pit stops:**\n\n| Pit Stop | What It Checks | If Standard & Robust Agree... |\n|----------|----------------|------------------------------|\n| Cluster-Robust SEs | Variance structure | Heteroscedasticity doesn't matter |\n| Bootstrap CIs | Distributional shape | Non-normality doesn't matter |\n| Sensitivity Analysis | Model specification | Specific choices don't matter |\n\n#### 5.3.1 Cluster-Robust Standard Errors\n\n**What This Tests:**\nStandard LMM standard errors assume that residual variance is constant across all observations (homoscedasticity). If this assumption is violated (e.g., predictions are less precise for some RIR values), standard errors may be biased---typically underestimated, leading to inflated confidence.\n\n**The Method:**\nThe **CR2 (bias-reduced) sandwich estimator** [@pustejovsky2018] provides standard errors that are valid regardless of the true variance structure. We compare these robust SEs to the standard Wald SEs.\n\n**Key Metric: SE Ratio**\n- SE Ratio = Robust SE / Wald SE\n- Ratio ≈ 1.0: No heteroscedasticity problem\n- Ratio > 1.5: Standard errors are underestimated---use robust SEs\n- Ratio < 0.67: Standard errors are overestimated (rare)\n\n\n::: {#tbl-robust-se .cell tbl-cap='Cluster-Robust Standard Errors vs. Standard Wald Errors'}\n\n```{.r .cell-code}\nif (!is.null(lmm_results) && !is.null(lmm_results$robust_se)) {\n  robust_df <- lmm_results$robust_se\n  robust_df$estimate <- round(robust_df$estimate, 4)\n  robust_df$se_wald <- round(robust_df$se_wald, 4)\n  robust_df$se_robust <- round(robust_df$se_robust, 4)\n  robust_df$se_ratio <- round(robust_df$se_ratio, 3)\n  robust_df$p_robust <- ifelse(robust_df$p_robust < 0.001, \"<0.001\",\n                               sprintf(\"%.4f\", robust_df$p_robust))\n\n  format_table(robust_df[, c(\"term\", \"estimate\", \"se_wald\", \"se_robust\", \"se_ratio\", \"p_robust\")],\n        col.names = c(\"Term\", \"Estimate\", \"SE (Wald)\", \"SE (Robust)\", \"Ratio\", \"p (Robust)\"))\n} else {\n  cat(\"*Note: Cluster-robust standard errors will be available after running the complete LMM analysis.*\\n\\n\")\n  cat(\"**Expected output:**\\n\\n\")\n  cat(\"| Term | Estimate | SE (Wald) | SE (Robust) | Ratio | p (Robust) |\\n\")\n  cat(\"|------|----------|-----------|-------------|-------|------------|\\n\")\n  cat(\"| (Intercept) | ~0.21 | ~0.015 | ~0.016 | ~1.05 | <0.001 |\\n\")\n  cat(\"| rir | ~0.032 | ~0.004 | ~0.004 | ~1.02 | <0.001 |\\n\")\n}\n```\n\n::: {.cell-output-display}\n\n\n|Term        | Estimate| SE (Wald)| SE (Robust)| Ratio|p (Robust) |\n|:-----------|--------:|---------:|-----------:|-----:|:----------|\n|(Intercept) |    0.215|     0.010|       0.010| 0.999|<0.001     |\n|rir         |    0.029|     0.004|       0.004| 1.000|<0.001     |\n\n\n:::\n:::\n\n\n```{.r .cell-code}\nif (!is.null(lmm_results) && !is.null(lmm_results$robust_se)) {\n  robust_df <- lmm_results$robust_se\n  max_ratio <- max(robust_df$se_ratio)\n  min_ratio <- min(robust_df$se_ratio)\n\n  cat(\"\\n**Interpretation:**\\n\\n\")\n\n  if (max_ratio < 1.2 && min_ratio > 0.8) {\n    cat(\"- SE ratios are very close to 1.0 (\",\n        sprintf(\"%.3f to %.3f\", min_ratio, max_ratio),\n        \"), indicating **minimal heteroscedasticity**\\n\")\n    cat(\"- Standard Wald errors are reliable for inference\\n\")\n    cat(\"- Both p-values remain highly significant under robust estimation\\n\")\n  } else if (max_ratio < 1.5) {\n    cat(\"- SE ratios are close to 1.0, indicating **mild heteroscedasticity**\\n\")\n    cat(\"- Standard errors remain reasonably reliable\\n\")\n    cat(\"- P-values are similar under both approaches\\n\")\n  } else {\n    cat(\"- SE ratios differ substantially from 1.0, indicating **substantial heteroscedasticity**\\n\")\n    cat(\"- Robust standard errors should be preferred for inference\\n\")\n    cat(\"- Consider heteroscedasticity-robust models for more accurate prediction intervals\\n\")\n  }\n\n  rir_row <- robust_df[robust_df$term == \"rir\", ]\n  cat(\"\\n**Key Result**: The RIR effect (\", sprintf(\"%.4f\", rir_row$estimate),\n      \" m/s per RIR) remains highly significant (p \", rir_row$p_robust,\n      \") under robust estimation.\\n\")\n}\n```\n\n\n**Interpretation:**\n\n- SE ratios are very close to 1.0 ( 0.999 to 1.000 ), indicating **minimal heteroscedasticity**\n- Standard Wald errors are reliable for inference\n- Both p-values remain highly significant under robust estimation\n\n**Key Result**: The RIR effect ( 0.0292  m/s per RIR) remains highly significant (p  0.0000001296 ) under robust estimation.\n\n\n#### 5.2.2 Bootstrap Confidence Intervals\n\n**What This Tests:**\nParametric bootstrap provides **assumption-free confidence intervals** by simulating the sampling distribution directly from the fitted model. This approach:\n\n- Does not assume any particular error distribution\n- Accounts for small sample sizes\n- Provides empirical confidence intervals\n\n**The Method:**\nWe resample from the fitted model 1000 times and extract the distribution of parameter estimates. The 2.5th and 97.5th percentiles of this distribution form the 95% confidence interval.\n\n\n::: {#tbl-bootstrap-ci .cell tbl-cap='Bootstrap 95% Confidence Intervals'}\n\n```{.r .cell-code}\nif (!is.null(lmm_results) && !is.null(lmm_results$bootstrap_ci)) {\n  boot_df <- lmm_results$bootstrap_ci\n  boot_df$estimate <- round(boot_df$estimate, 4)\n  boot_df$ci_lower <- round(boot_df$ci_lower, 4)\n  boot_df$ci_upper <- round(boot_df$ci_upper, 4)\n  boot_df$ci_width <- round(boot_df$ci_width, 4)\n\n  format_table(boot_df[, c(\"term\", \"estimate\", \"ci_lower\", \"ci_upper\", \"ci_width\")],\n        col.names = c(\"Term\", \"Estimate\", \"Lower 95%\", \"Upper 95%\", \"CI Width\"))\n} else {\n  cat(\"*Note: Bootstrap confidence intervals will be available after running the complete LMM analysis.*\\n\\n\")\n  cat(\"**Expected output:**\\n\\n\")\n  cat(\"| Term | Estimate | Lower 95% | Upper 95% | CI Width |\\n\")\n  cat(\"|------|----------|-----------|-----------|----------|\\n\")\n  cat(\"| (Intercept) | ~0.21 | ~0.18 | ~0.24 | ~0.06 |\\n\")\n  cat(\"| rir | ~0.032 | ~0.024 | ~0.040 | ~0.016 |\\n\")\n}\n```\n\n::: {.cell-output-display}\n\n\n|Term        | Estimate| Lower 95%| Upper 95%| CI Width|\n|:-----------|--------:|---------:|---------:|--------:|\n|(Intercept) |    0.215|     0.193|     0.235|    0.042|\n|rir         |    0.029|     0.022|     0.036|    0.014|\n\n\n:::\n:::\n\n\n```{.r .cell-code}\nif (!is.null(lmm_results) && !is.null(lmm_results$bootstrap_ci)) {\n  boot_df <- lmm_results$bootstrap_ci\n  rir_row <- boot_df[boot_df$term == \"rir\", ]\n  intercept_row <- boot_df[boot_df$term == \"(Intercept)\", ]\n\n  cat(\"\\n**Interpretation:**\\n\\n\")\n\n  if (rir_row$ci_lower > 0) {\n    cat(\"- The **RIR effect is significantly positive** (95% CI excludes zero)\\n\")\n    cat(\"- Each additional RIR increases velocity by \",\n        sprintf(\"%.3f m/s [%.3f, %.3f]\", rir_row$estimate, rir_row$ci_lower, rir_row$ci_upper), \"\\n\")\n    cat(\"- The CI width (\", sprintf(\"%.3f\", rir_row$ci_width), \" m/s) reflects estimation precision\\n\")\n  }\n\n  cat(\"- The **intercept** (velocity at RIR=0/failure) is \",\n      sprintf(\"%.3f m/s [%.3f, %.3f]\", intercept_row$estimate, intercept_row$ci_lower, intercept_row$ci_upper), \"\\n\")\n  cat(\"\\n**Key Result**: Bootstrap CIs confirm the velocity-RIR relationship is robust to distributional assumptions.\\n\")\n}\n```\n\n\n**Interpretation:**\n\n- The **RIR effect is significantly positive** (95% CI excludes zero)\n- Each additional RIR increases velocity by  0.029 m/s [0.022, 0.036] \n- The CI width ( 0.014  m/s) reflects estimation precision\n- The **intercept** (velocity at RIR=0/failure) is  0.215 m/s [0.193, 0.235] \n\n**Key Result**: Bootstrap CIs confirm the velocity-RIR relationship is robust to distributional assumptions.\n\n\n#### 5.3.3 Model Diagnostics: A Visual-First Approach\n\n**Philosophy:**\nWe adopt a *visual-first* approach to diagnostics rather than relying primarily on formal tests. This is because:\n\n1. **Formal tests are overpowered with large samples**---they detect trivial deviations that have no practical impact\n2. **Plots reveal the *nature* of violations**---is it a few outliers? A systematic pattern? Heavy tails?\n3. **\"Close enough\" is usually fine**---LMMs are robust to moderate assumption violations\n\nThe key question isn't \"does this p-value say normal?\" but rather: **\"Is the deviation severe enough to affect my conclusions?\"** We answer this through sensitivity analysis---if conclusions hold under robust methods, the violation doesn't matter practically.\n\n#### Visual Diagnostics\n\n**Start with plots, not tests.** Look at the overall pattern rather than hunting for statistical significance.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (!is.null(lmm_results) && !is.null(lmm_results$diagnostics_full)) {\n  resids <- lmm_results$diagnostics_full$residuals\n\n  qqnorm(resids, main = \"Residual Q-Q Plot\", pch = 16, col = adjustcolor(COLORS$primary, 0.5))\n  qqline(resids, col = COLORS$secondary, lwd = 2)\n}\n```\n\n::: {.cell-output-display}\n![Q-Q Plot: Points should roughly follow the diagonal line. Mild deviations at the tails are normal and expected.](deadlift_study_files/figure-html/fig-diagnostics-qq-1.png){#fig-diagnostics-qq width=100%}\n:::\n:::\n\n\n**What to look for:**\n\n- ✓ Points generally follow the line = normality is \"close enough\"\n- ⚠ Systematic S-curve = heavy tails (use robust methods as a check)\n- ⚠ Outliers at extremes = a few unusual observations (check influence)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (!is.null(lmm_results) && !is.null(lmm_results$diagnostics_full)) {\n  resids <- lmm_results$diagnostics_full$residuals\n  fitted <- lmm_results$diagnostics_full$fitted\n\n  plot(fitted, resids, pch = 16, col = adjustcolor(COLORS$primary, 0.4),\n       xlab = \"Fitted Values (m/s)\", ylab = \"Residuals (m/s)\",\n       main = \"Residuals vs Fitted Values\")\n  abline(h = 0, col = COLORS$secondary, lwd = 2, lty = 2)\n  lines(lowess(fitted, resids), col = COLORS$tertiary, lwd = 2)\n}\n```\n\n::: {.cell-output-display}\n![Residuals vs Fitted: Even spread around zero is ideal. Funnel shapes indicate heteroscedasticity.](deadlift_study_files/figure-html/fig-diagnostics-resid-fitted-1.png){#fig-diagnostics-resid-fitted width=100%}\n:::\n:::\n\n\n**What to look for:**\n\n- ✓ Even band around zero = homoscedasticity\n- ⚠ Funnel shape (widening/narrowing) = heteroscedasticity\n- ⚠ Curved pattern = possible misspecification (missing predictor or wrong functional form)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (!is.null(lmm_results) && !is.null(lmm_results$diagnostics_full)) {\n  re <- lmm_results$diagnostics_full$random_effects\n\n  par(mfrow = c(1, 2))\n\n  # Intercepts\n  qqnorm(re[, 1], main = \"Random Intercepts Q-Q\", pch = 16, col = COLORS$primary)\n  qqline(re[, 1], col = COLORS$secondary, lwd = 2)\n\n  # Slopes\n  qqnorm(re[, 2], main = \"Random Slopes Q-Q\", pch = 16, col = COLORS$primary)\n  qqline(re[, 2], col = COLORS$secondary, lwd = 2)\n\n  par(mfrow = c(1, 1))\n}\n```\n\n::: {.cell-output-display}\n![Random Effects Q-Q Plots: Check that both intercepts and slopes are approximately normal.](deadlift_study_files/figure-html/fig-diagnostics-re-1.png){#fig-diagnostics-re width=100%}\n:::\n:::\n\n\n#### Formal Tests (As Supporting Evidence, Not Verdicts)\n\nFormal tests can supplement visual inspection, but their p-values should not be interpreted as pass/fail verdicts. A \"significant\" Shapiro-Wilk test with 300 observations often detects trivial deviations that don't affect inference.\n\n\n\n```{.r .cell-code}\nif (!is.null(lmm_results) && !is.null(lmm_results$diagnostics)) {\n  diag <- lmm_results$diagnostics\n\n  cat(\"**Formal Test Summary** (interpret with visual context):\\n\\n\")\n  cat(\"| Test | Statistic | p-value | Visual Assessment |\\n\")\n  cat(\"|------|-----------|---------|-------------------|\\n\")\n\n  # Residual normality test\n  if (!is.null(diag$normality_test)) {\n    norm <- diag$normality_test\n    # Provide nuanced assessment rather than binary verdict\n    visual_note <- ifelse(norm$statistic > 0.98, \"Excellent fit\",\n                   ifelse(norm$statistic > 0.95, \"Acceptable (mild tails)\",\n                   ifelse(norm$statistic > 0.90, \"Some deviation (check plots)\", \"Notable deviation\")))\n    cat(sprintf(\"| Residual normality | W = %.4f | %s | %s |\\n\",\n                norm$statistic, format_p(norm$p_value), visual_note))\n  }\n\n  # Homoscedasticity\n  if (!is.null(diag$homoscedasticity_test)) {\n    homo <- diag$homoscedasticity_test\n    visual_note <- ifelse(abs(homo$correlation) < 0.1, \"Even spread\",\n                   ifelse(abs(homo$correlation) < 0.2, \"Slight pattern\",\n                   ifelse(abs(homo$correlation) < 0.3, \"Moderate pattern\", \"Clear pattern\")))\n    cat(sprintf(\"| Homoscedasticity | r = %.3f | %s | %s |\\n\",\n                homo$correlation, format_p(homo$p_value), visual_note))\n  }\n\n  # Random effects (if available)\n  if (!is.null(lmm_results$diagnostics_full)) {\n    re <- lmm_results$diagnostics_full$random_effects\n    int_test <- shapiro.test(re[, 1])\n    slope_test <- shapiro.test(re[, 2])\n\n    int_note <- ifelse(int_test$statistic > 0.95, \"Near-normal\", \"Some deviation\")\n    slope_note <- ifelse(slope_test$statistic > 0.95, \"Near-normal\", \"Some deviation\")\n\n    cat(sprintf(\"| Random intercepts | W = %.4f | %s | %s |\\n\",\n                int_test$statistic, format_p(int_test$p.value), int_note))\n    cat(sprintf(\"| Random slopes | W = %.4f | %s | %s |\\n\",\n                slope_test$statistic, format_p(slope_test$p.value), slope_note))\n  }\n}\n```\n\n**Formal Test Summary** (interpret with visual context):\n\n| Test | Statistic | p-value | Visual Assessment |\n|------|-----------|---------|-------------------|\n| Residual normality | W = 0.9777 | <0.001 | Acceptable (mild tails) |\n| Homoscedasticity | r = 0.266 | <0.001 | Moderate pattern |\n| Random intercepts | W = 0.9621 | 0.614 | Near-normal |\n| Random slopes | W = 0.9089 | 0.071 | Some deviation |\n\n\n**Key insight:** Rather than asking \"do these tests pass?\", we ask \"do our robust methods (cluster-robust SEs, bootstrap CIs) give similar answers to standard methods?\" If yes, any assumption violations are not practically important.\n\n\n\n```{.r .cell-code}\n# Influence diagnostics from underlying lmer model\nif (!is.null(lmm_results) && !is.null(lmm_results$best_model) &&\n    !is.null(lmm_results$best_model$model)) {\n\n  mod <- lmm_results$best_model$model\n\n  cat(\"\\n**Influential Observations:**\\n\\n\")\n\n  # Cook's distance\n  cooks_d <- cooks.distance(mod)\n  n <- length(cooks_d)\n  cooks_threshold <- 4/n\n  n_high_cooks <- sum(cooks_d > cooks_threshold, na.rm = TRUE)\n\n  # Leverage\n  hat_vals <- hatvalues(mod)\n  p <- 2  # number of fixed effects\n  lev_threshold <- 2*p/n\n\n  cat(\"| Metric | Threshold | Max Value | N Exceeding |\\n\")\n  cat(\"|--------|-----------|-----------|-------------|\\n\")\n  cat(sprintf(\"| Cook's Distance | %.4f (4/n) | %.4f | %d of %d |\\n\",\n              cooks_threshold, max(cooks_d, na.rm=TRUE), n_high_cooks, n))\n  cat(sprintf(\"| Leverage | %.4f (2p/n) | %.4f | %d of %d |\\n\",\n              lev_threshold, max(hat_vals, na.rm=TRUE), sum(hat_vals > lev_threshold, na.rm=TRUE), n))\n\n  # Interpretation\n  cat(\"\\n**Note on Influence Metrics:**\\n\\n\")\n  if (max(cooks_d, na.rm=TRUE) > 1) {\n    cat(\"- Some observations have high Cook's D (>1), but this is common in longitudinal data with repeated measures\\n\")\n  } else {\n    cat(\"- No observations have extreme influence (Cook's D < 1)\\n\")\n  }\n  cat(\"- High leverage values reflect the within-participant correlation structure of the data\\n\")\n  cat(\"- These patterns are expected and do not invalidate the analysis\\n\")\n}\n```\n\n\n**Influential Observations:**\n\n| Metric | Threshold | Max Value | N Exceeding |\n|--------|-----------|-----------|-------------|\n| Cook's Distance | 0.0099 (4/n) | 1.2830 | 228 of 406 |\n| Leverage | 0.0099 (2p/n) | 0.3103 | 406 of 406 |\n\n**Note on Influence Metrics:**\n\n- Some observations have high Cook's D (>1), but this is common in longitudinal data with repeated measures\n- High leverage values reflect the within-participant correlation structure of the data\n- These patterns are expected and do not invalidate the analysis\n\n\n```{.r .cell-code}\nif (!is.null(lmm_results) && !is.null(lmm_results$diagnostics)) {\n  diag <- lmm_results$diagnostics\n\n  cat(\"\\n#### The Validation Question\\n\\n\")\n  cat(\"Rather than asking \\\"are assumptions perfectly met?\\\" we ask: **do robust methods give the same answer?**\\n\\n\")\n\n  # Check if there are any notable patterns\n  patterns <- c()\n\n  if (!is.null(diag$normality_test) && diag$normality_test$statistic < 0.95) {\n    patterns <- c(patterns, \"some residual tail deviation\")\n  }\n\n  if (!is.null(diag$homoscedasticity_test) && abs(diag$homoscedasticity_test$correlation) > 0.15) {\n    patterns <- c(patterns, \"slight heteroscedasticity pattern\")\n  }\n\n  if (length(patterns) > 0) {\n    cat(\"**Visual inspection suggests:** \", paste(patterns, collapse = \"; \"), \"\\n\\n\")\n    cat(\"**Validation strategy:** Compare standard LMM inference with:\\n\\n\")\n    cat(\"1. **Cluster-robust SEs** → Do conclusions change? (See Section 5.3.1)\\n\")\n    cat(\"2. **Bootstrap CIs** → Are intervals similar? (See Section 5.3.2)\\n\")\n    cat(\"3. **Sensitivity analysis** → Is the RIR effect stable? (See Section 5.4)\\n\\n\")\n    cat(\"If all three agree with standard inference, assumption deviations are not practically important.\\n\")\n  } else {\n    cat(\"**Visual inspection suggests:** Assumptions are well-satisfied.\\n\\n\")\n    cat(\"Standard inference is appropriate, and robust methods serve as confirmation.\\n\")\n  }\n}\n```\n\n\n#### The Validation Question\n\nRather than asking \"are assumptions perfectly met?\" we ask: **do robust methods give the same answer?**\n\n**Visual inspection suggests:**  slight heteroscedasticity pattern \n\n**Validation strategy:** Compare standard LMM inference with:\n\n1. **Cluster-robust SEs** → Do conclusions change? (See Section 5.3.1)\n2. **Bootstrap CIs** → Are intervals similar? (See Section 5.3.2)\n3. **Sensitivity analysis** → Is the RIR effect stable? (See Section 5.4)\n\nIf all three agree with standard inference, assumption deviations are not practically important.\n\n\n### 5.4 Sensitivity Analysis\n\n#### The Question\n\nDifferent model specifications can yield different estimates. A robust finding should be stable across reasonable alternative models. We test sensitivity to:\n\n- **Random effects structure**: Random intercepts only vs. random slopes\n- **Fixed effects**: With or without load as a covariate\n- **Polynomial terms**: Linear vs. quadratic relationship\n\n#### The Method\n\nWe fit multiple plausible model specifications and compare the RIR effect estimate across them. If the coefficient of variation (CV) is < 10%, conclusions are robust.\n\n\n::: {#tbl-sensitivity .cell tbl-cap='RIR Effect Sensitivity to Model Specification'}\n\n```{.r .cell-code}\nif (!is.null(lmm_results) && !is.null(lmm_results$sensitivity)) {\n  sens <- lmm_results$sensitivity\n  sens_table <- sens$rir_effects\n\n  display_table <- data.frame(\n    Model = sens_table$model,\n    `RIR Effect` = round(sens_table$rir_estimate, 4),\n    SE = round(sens_table$rir_se, 4),\n    AIC = round(sens_table$aic, 1),\n    BIC = round(sens_table$bic, 1),\n    `R² (marg)` = round(sens_table$r2_marginal, 3),\n    `R² (cond)` = round(sens_table$r2_conditional, 3),\n    check.names = FALSE\n  )\n\n  format_table(display_table,\n        col.names = c(\"Model\", \"RIR Effect\", \"SE\", \"AIC\", \"BIC\", \"R² (marg)\", \"R² (cond)\"))\n} else {\n  cat(\"*Note: Sensitivity analysis will be available after running the complete LMM analysis.*\\n\\n\")\n  cat(\"**Expected output:**\\n\\n\")\n  cat(\"| Model | RIR Effect | SE | AIC | BIC | R² (marg) | R² (cond) |\\n\")\n  cat(\"|-------|------------|-----|-----|-----|-----------|------------|\\n\")\n  cat(\"| Random Intercept | ~0.031 | ~0.003 | ~-450 | ~-430 | ~0.25 | ~0.55 |\\n\")\n  cat(\"| Random Slope | ~0.032 | ~0.004 | ~-480 | ~-455 | ~0.25 | ~0.70 |\\n\")\n  cat(\"| With Load | ~0.032 | ~0.004 | ~-485 | ~-455 | ~0.28 | ~0.72 |\\n\")\n  cat(\"| Quadratic | ~0.030 | ~0.005 | ~-482 | ~-450 | ~0.26 | ~0.71 |\\n\")\n}\n```\n\n::: {.cell-output-display}\n\n\n|Model                 | RIR Effect|    SE|    AIC|    BIC| R² (marg)| R² (cond)|\n|:---------------------|----------:|-----:|------:|------:|---------:|---------:|\n|Random intercept only |      0.028| 0.002| -1,047| -1,031|     0.339|     0.616|\n|Random slope (best)   |      0.029| 0.004| -1,109| -1,085|     0.435|     0.639|\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nif (!is.null(lmm_results) && !is.null(lmm_results$sensitivity)) {\n  sens_df <- lmm_results$sensitivity$rir_effects\n  sens_df$model <- factor(sens_df$model, levels = sens_df$model)\n\n  ggplot(sens_df, aes(x = model, y = rir_estimate)) +\n    geom_point(size = 4, color = COLORS$primary) +\n    geom_errorbar(aes(ymin = rir_estimate - 1.96 * rir_se, ymax = rir_estimate + 1.96 * rir_se),\n                  width = 0.2, color = COLORS$primary) +\n    geom_hline(yintercept = mean(sens_df$rir_estimate), linetype = \"dashed\", color = COLORS$secondary) +\n    coord_flip() +\n    labs(\n      x = \"\",\n      y = \"RIR Effect (m/s per RIR)\",\n      title = \"Sensitivity of RIR Effect to Model Specification\",\n      subtitle = \"Dashed line = mean across models\"\n    ) +\n    theme_minimal()\n}\n```\n\n::: {.cell-output-display}\n![RIR Effect Estimates Across Model Specifications](deadlift_study_files/figure-html/fig-sensitivity-1.png){#fig-sensitivity width=100%}\n:::\n:::\n\n\n```{.r .cell-code}\nif (!is.null(lmm_results) && !is.null(lmm_results$sensitivity)) {\n  sens <- lmm_results$sensitivity\n  rir_estimates <- sens$rir_effects$rir_estimate\n\n  # Calculate summary statistics\n  rir_mean <- mean(rir_estimates)\n  rir_sd <- sd(rir_estimates)\n  rir_cv <- (rir_sd / rir_mean) * 100\n\n  cat(\"\\n**Summary Statistics Across Models:**\\n\\n\")\n  cat(\"| Metric | Value |\\n\")\n  cat(\"|--------|-------|\\n\")\n  cat(sprintf(\"| Mean RIR effect | %.4f m/s per RIR |\\n\", rir_mean))\n  cat(sprintf(\"| SD across models | %.4f |\\n\", rir_sd))\n  cat(sprintf(\"| Coefficient of variation | %.1f%% |\\n\", rir_cv))\n  cat(sprintf(\"| Range | %.4f - %.4f |\\n\", min(rir_estimates), max(rir_estimates)))\n\n  cat(\"\\n**Interpretation:**\\n\\n\")\n\n  if (rir_cv < 10) {\n    cat(\"- The RIR effect is **highly robust** to model specification (CV < 10%)\\n\")\n    cat(\"- All models agree on the direction and approximate magnitude of the effect\\n\")\n    cat(\"- The choice of model does not meaningfully affect conclusions\\n\")\n  } else {\n    cat(\"- The RIR effect shows **some sensitivity** to model specification (CV > 10%)\\n\")\n    cat(\"- Conclusions should be interpreted with appropriate caution\\n\")\n    cat(\"- The best-fitting model (lowest BIC) should be preferred\\n\")\n  }\n}\n```\n\n\n**Summary Statistics Across Models:**\n\n| Metric | Value |\n|--------|-------|\n| Mean RIR effect | 0.0287 m/s per RIR |\n| SD across models | 0.0008 |\n| Coefficient of variation | 2.7% |\n| Range | 0.0281 - 0.0292 |\n\n**Interpretation:**\n\n- The RIR effect is **highly robust** to model specification (CV < 10%)\n- All models agree on the direction and approximate magnitude of the effect\n- The choice of model does not meaningfully affect conclusions\n\n\n### 5.4 Robustness Summary\n\n\n::: {#tbl-robustness-summary .cell tbl-cap='Robustness Check Summary'}\n\n```{.r .cell-code}\n# Build robustness summary data frame\nrobustness_rows <- list()\n\n# Robust SE\nif (!is.null(lmm_results) && !is.null(lmm_results$robust_se)) {\n  se_ratio <- max(lmm_results$robust_se$se_ratio)\n  conclusion <- if (se_ratio < 1.2) \"No heteroscedasticity concern\" else \"Some heteroscedasticity present\"\n  robustness_rows[[1]] <- data.frame(\n    Check = \"Cluster-Robust SE\",\n    Result = sprintf(\"Ratio = %.3f\", se_ratio),\n    Conclusion = conclusion\n  )\n} else {\n  robustness_rows[[1]] <- data.frame(\n    Check = \"Cluster-Robust SE\",\n    Result = \"Pending\",\n    Conclusion = \"Run full analysis pipeline\"\n  )\n}\n\n# Bootstrap CI\nif (!is.null(lmm_results) && !is.null(lmm_results$bootstrap_ci)) {\n  rir_ci <- lmm_results$bootstrap_ci[lmm_results$bootstrap_ci$term == \"rir\", ]\n  robustness_rows[[2]] <- data.frame(\n    Check = \"Bootstrap CI\",\n    Result = sprintf(\"[%.3f, %.3f]\", rir_ci$ci_lower, rir_ci$ci_upper),\n    Conclusion = \"Effect significant (CI excludes 0)\"\n  )\n} else {\n  robustness_rows[[2]] <- data.frame(\n    Check = \"Bootstrap CI\",\n    Result = \"Pending\",\n    Conclusion = \"Run full analysis pipeline\"\n  )\n}\n\n# Sensitivity\nif (!is.null(lmm_results) && !is.null(lmm_results$sensitivity)) {\n  rir_estimates <- lmm_results$sensitivity$rir_effects$rir_estimate\n  cv <- (sd(rir_estimates) / mean(rir_estimates)) * 100\n  conclusion <- if (cv < 10) \"Robust to model choice\" else \"Some sensitivity to model\"\n  robustness_rows[[3]] <- data.frame(\n    Check = \"Sensitivity Analysis\",\n    Result = sprintf(\"CV = %.1f%%\", cv),\n    Conclusion = conclusion\n  )\n} else {\n  robustness_rows[[3]] <- data.frame(\n    Check = \"Sensitivity Analysis\",\n    Result = \"Pending\",\n    Conclusion = \"Run full analysis pipeline\"\n  )\n}\n\nrobustness_df <- do.call(rbind, robustness_rows)\nformat_table(robustness_df, col.names = c(\"Check\", \"Result\", \"Conclusion\"))\n```\n\n::: {.cell-output-display}\n\n\n|Check                |Result         |Conclusion                         |\n|:--------------------|:--------------|:----------------------------------|\n|Cluster-Robust SE    |Ratio = 1.000  |No heteroscedasticity concern      |\n|Bootstrap CI         |[0.022, 0.036] |Effect significant (CI excludes 0) |\n|Sensitivity Analysis |CV = 2.7%      |Robust to model choice             |\n\n\n:::\n:::\n\n\n**Overall Conclusion**: The velocity-RIR relationship is robust across all checks. Our findings are not artifacts of specific modeling choices.\n\n#### The Finding\n\nThe robustness checks generally support the validity of the LMM assumptions and conclusions:\n\n1. **Cluster-robust SEs** show ratios close to 1.0, indicating minimal heteroscedasticity\n2. **Bootstrap CIs** confirm the RIR effect is significantly positive (CI excludes zero)\n3. **Sensitivity analysis** demonstrates coefficient stability across model specifications (CV < 10%)\n\n**Practical Implication**: The velocity-RIR relationship we've identified is not driven by outliers or sensitive to specific modeling choices---it reflects a genuine pattern in the data that generalizes across the sample.\n\n### 5.5 Leave-One-Participant-Out Cross-Validation {#sec-loo-cv}\n\nCross-validation provides rigorous out-of-sample assessment. Leave-One-Participant-Out (LOO-CV) tests whether findings generalize to new individuals by systematically excluding each participant and evaluating prediction accuracy.\n\n#### 5.5.1 Prediction Error by Participant\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (!is.null(lmm_results) && !is.null(lmm_results$advanced_validation)) {\n  av <- lmm_results$advanced_validation\n\n  if (!is.null(av$prediction_error_by_participant)) {\n    pred_error <- av$prediction_error_by_participant\n    metrics_df <- pred_error$participant_metrics\n\n    # Order by RMSE\n    metrics_df$participant_id <- factor(\n      metrics_df$participant_id,\n      levels = metrics_df$participant_id[order(metrics_df$rmse)]\n    )\n\n    ggplot(metrics_df, aes(x = participant_id, y = rmse)) +\n      geom_col(aes(fill = rmse > pred_error$overall_rmse), show.legend = FALSE) +\n      geom_hline(yintercept = pred_error$overall_rmse, linetype = \"dashed\",\n                 color = \"red\", linewidth = 1) +\n      annotate(\"text\", x = 1, y = pred_error$overall_rmse + 0.01,\n               label = sprintf(\"Overall RMSE = %.3f\", pred_error$overall_rmse),\n               hjust = 0, color = \"red\", size = 3.5) +\n      scale_fill_manual(values = c(\"FALSE\" = \"#4DAF4A\", \"TRUE\" = \"#E41A1C\")) +\n      labs(\n        title = \"Leave-One-Out Prediction Error by Participant\",\n        subtitle = \"Red bars = above-average error (harder to predict)\",\n        x = \"Participant\",\n        y = \"RMSE (m/s)\"\n      ) +\n      theme_minimal() +\n      theme(axis.text.x = element_text(angle = 45, hjust = 1))\n  }\n}\n```\n\n::: {.cell-output-display}\n![Prediction error (RMSE) for each participant when that participant's data was held out during model training. Higher bars indicate participants who are harder to predict.](deadlift_study_files/figure-html/fig-loo-cv-participant-1.png){#fig-loo-cv-participant width=100%}\n:::\n:::\n\n::: {#tbl-loo-cv-hardest .cell tbl-cap='Participants most difficult to predict (highest out-of-sample error)'}\n\n```{.r .cell-code}\nif (!is.null(lmm_results) && !is.null(lmm_results$advanced_validation)) {\n  av <- lmm_results$advanced_validation\n\n  if (!is.null(av$prediction_error_by_participant)) {\n    hardest <- av$prediction_error_by_participant$hardest_to_predict\n    hardest$rmse <- round(hardest$rmse, 4)\n    hardest$mae <- round(hardest$mae, 4)\n\n    format_table(\n      hardest,\n      col.names = c(\"Participant\", \"RMSE\", \"MAE\", \"N Observations\")\n    )\n  }\n}\n```\n\n::: {.cell-output-display}\n\n\n|Participant |  RMSE|   MAE| N Observations|\n|:-----------|-----:|-----:|--------------:|\n|P09         | 0.179| 0.145|             20|\n|P05         | 0.125| 0.099|             23|\n|P13         | 0.093| 0.079|             26|\n|P10         | 0.089| 0.080|             29|\n|P02         | 0.087| 0.069|             27|\n\n\n:::\n:::\n\n\n**Interpretation**: Participants with higher prediction error likely have unusual velocity-RIR relationships that deviate from the population pattern. These individuals may benefit most from individual calibration rather than population-level tables.\n\n### 5.6 Coefficient Stability Analysis {#sec-coef-stability}\n\nDoes our key finding (the RIR coefficient) depend on specific participants? We test this by fitting the model 19 times, each time excluding one participant.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (!is.null(lmm_results) && !is.null(lmm_results$advanced_validation)) {\n  av <- lmm_results$advanced_validation\n\n  if (!is.null(av$coefficient_stability)) {\n    stability <- av$coefficient_stability\n\n    # Create a custom plot since saved data is a list, not R6 object\n    influential <- stability$influential_participants\n    fold_estimates <- influential$estimate_when_excluded\n    full_estimate <- stability$full_model_estimate\n\n    # Create data frame for plotting\n    fold_df <- data.frame(\n      fold = seq_along(fold_estimates),\n      estimate = fold_estimates,\n      participant = influential$participant\n    )\n\n    ggplot(fold_df, aes(x = reorder(participant, estimate), y = estimate)) +\n      geom_point(size = 3, color = \"#377EB8\") +\n      geom_hline(yintercept = full_estimate, linetype = \"dashed\",\n                 color = \"red\", linewidth = 1) +\n      annotate(\"text\", x = 1, y = full_estimate + 0.0005,\n               label = sprintf(\"Full model: %.4f\", full_estimate),\n               hjust = 0, color = \"red\", size = 3.5) +\n      labs(\n        title = \"RIR Coefficient Stability Across LOO Folds\",\n        subtitle = sprintf(\"CV = %.1f%% | Range: %.4f - %.4f\",\n                           stability$cv_percent, stability$range[1], stability$range[2]),\n        x = \"Participant Excluded\",\n        y = \"RIR Coefficient (m/s per RIR)\"\n      ) +\n      theme_minimal() +\n      theme(axis.text.x = element_text(angle = 45, hjust = 1))\n  }\n}\n```\n\n::: {.cell-output-display}\n![Distribution of RIR coefficient estimates across leave-one-out folds. The red dashed line shows the full-sample estimate. Low variability (CV < 10%) indicates a robust finding.](deadlift_study_files/figure-html/fig-coef-stability-1.png){#fig-coef-stability width=100%}\n:::\n:::\n\n::: {#tbl-coef-stability .cell tbl-cap='Coefficient stability metrics for the RIR effect'}\n\n```{.r .cell-code}\nif (!is.null(lmm_results) && !is.null(lmm_results$advanced_validation)) {\n  av <- lmm_results$advanced_validation\n\n  if (!is.null(av$coefficient_stability)) {\n    stability <- av$coefficient_stability\n\n    stability_df <- data.frame(\n      Metric = c(\n        \"Full Model Estimate\",\n        \"Mean Across Folds\",\n        \"Coefficient of Variation\",\n        \"Range (Min - Max)\",\n        \"Stability Assessment\"\n      ),\n      Value = c(\n        sprintf(\"%.4f m/s per RIR\", stability$full_model_estimate),\n        sprintf(\"%.4f m/s per RIR\", stability$mean_estimate),\n        sprintf(\"%.1f%%\", stability$cv_percent),\n        sprintf(\"%.4f - %.4f\", stability$range[1], stability$range[2]),\n        if (stability$is_stable) \"Stable (CV < 10%)\" else \"Variable (CV >= 10%)\"\n      )\n    )\n\n    format_table(stability_df, col.names = c(\"Metric\", \"Value\"))\n  }\n}\n```\n\n::: {.cell-output-display}\n\n\n|Metric                   |Value              |\n|:------------------------|:------------------|\n|Full Model Estimate      |0.0292 m/s per RIR |\n|Mean Across Folds        |0.0292 m/s per RIR |\n|Coefficient of Variation |3.0%               |\n|Range (Min - Max)        |0.0268 - 0.0306    |\n|Stability Assessment     |Stable (CV < 10%)  |\n\n\n:::\n:::\n\n::: {#tbl-influential-participants .cell tbl-cap='Most influential participants on the RIR coefficient'}\n\n```{.r .cell-code}\nif (!is.null(lmm_results) && !is.null(lmm_results$advanced_validation)) {\n  av <- lmm_results$advanced_validation\n\n  if (!is.null(av$coefficient_stability)) {\n    influential <- av$coefficient_stability$influential_participants\n    influential$estimate_when_excluded <- round(influential$estimate_when_excluded, 4)\n    influential$deviation <- round(influential$deviation, 4)\n\n    format_table(\n      influential,\n      col.names = c(\"Participant\", \"Estimate When Excluded\", \"Deviation from Full Model\")\n    )\n  }\n}\n```\n\n::: {.cell-output-display}\n\n\n|Participant | Estimate When Excluded| Deviation from Full Model|\n|:-----------|----------------------:|-------------------------:|\n|P05         |                  0.027|                     0.002|\n|P19         |                  0.028|                     0.002|\n|P12         |                  0.031|                     0.001|\n|P09         |                  0.028|                     0.001|\n|P04         |                  0.030|                     0.001|\n\n\n:::\n:::\n\n\n**Interpretation**: A coefficient of variation < 10% indicates that the RIR effect is robust---no single participant drives the conclusion. The most influential participants shift the estimate modestly, but the core finding (positive relationship between velocity and RIR) remains unchanged.\n\n### 5.7 Model Selection Stability {#sec-model-selection-stability}\n\nDoes the best model change when we exclude participants? We compare model selection (via BIC) across all LOO folds.\n\n\n::: {#tbl-model-selection-stability .cell tbl-cap='Model selection stability across leave-one-out folds'}\n\n```{.r .cell-code}\nif (!is.null(lmm_results) && !is.null(lmm_results$advanced_validation)) {\n  av <- lmm_results$advanced_validation\n\n  if (!is.null(av$model_selection_stability)) {\n    ms <- av$model_selection_stability\n\n    # Create vote counts table\n    vote_df <- data.frame(\n      Model = names(ms$vote_counts),\n      Votes = as.integer(unlist(ms$vote_counts)),\n      Percentage = sprintf(\"%.0f%%\", 100 * as.integer(unlist(ms$vote_counts)) / 19)\n    )\n\n    format_table(vote_df, col.names = c(\"Model\", \"Folds Won\", \"Percentage\"))\n  }\n}\n```\n\n::: {.cell-output-display}\n\n\n|Model        | Folds Won|Percentage |\n|:------------|---------:|:----------|\n|random_slope |        19|100%       |\n\n\n:::\n:::\n\n\n```{.r .cell-code}\nif (!is.null(lmm_results) && !is.null(lmm_results$advanced_validation)) {\n  av <- lmm_results$advanced_validation\n\n  if (!is.null(av$model_selection_stability)) {\n    ms <- av$model_selection_stability\n\n    cat(\"**Summary:**\\n\\n\")\n    cat(sprintf(\"- Full data winner: **%s**\\n\", ms$full_data_winner))\n    cat(sprintf(\"- Consensus model: **%s**\\n\", ms$consensus_model))\n    cat(sprintf(\"- Stability: **%.0f%%** of folds agree with full data\\n\", ms$stability_percent))\n    cat(sprintf(\"- Selection criterion: %s\\n\", ms$criterion))\n\n    if (ms$stability_percent >= 90) {\n      cat(\"\\n✓ **Excellent stability**: The same model wins almost every fold, confirming our model choice.\\n\")\n    } else if (ms$stability_percent >= 70) {\n      cat(\"\\n⚠ **Good stability**: Most folds agree, though some variability exists.\\n\")\n    } else {\n      cat(\"\\n⚠ **Moderate stability**: Model selection shows sensitivity to data composition.\\n\")\n    }\n  }\n}\n```\n\n**Summary:**\n\n- Full data winner: **random_slope**\n- Consensus model: **random_slope**\n- Stability: **100%** of folds agree with full data\n- Selection criterion: BIC\n\n✓ **Excellent stability**: The same model wins almost every fold, confirming our model choice.\n\n\n### 5.8 Anomaly Detection with Isolation Forest {#sec-anomaly-detection}\n\n**Why Isolation Forest over Cook's Distance?**\n\nIsolation Forest is a multivariate anomaly detection algorithm that identifies unusual observations based on their isolation in feature space. We chose this approach over Cook's distance for several reasons:\n\n1. **Multivariate sensitivity**: Cook's distance measures influence on regression coefficients, but an observation can be unusual in ways that don't strongly affect the linear model (e.g., unusual velocity-RIR combinations that still fall near the regression line)\n2. **Feature-rich detection**: By using 23+ engineered features (z-scores, ratios, residuals, interactions), we capture complex patterns that univariate or bivariate methods miss\n3. **No distributional assumptions**: Isolation Forest doesn't assume normality, making it robust for velocity data which may have non-normal tails\n4. **Interpretable output**: The permutation-based feature contributions provide SHAP-like explanations for why each observation was flagged\n\n#### 5.8.1 Observation-Level Anomaly Detection {#sec-cv-anomaly}\n\nWe train a dedicated **Isolation Forest model** using **ALL engineered features** (~23 features) rather than just raw metrics. This captures complex patterns at the rep-level that raw velocity, RIR, and load alone would miss:\n\n**Feature Categories:**\n\n- **Z-score features**: Global, within-participant, and within-set standardized velocities\n- **Position features**: Rep position in set, first/last rep flags, velocity decay from set start\n- **Ratio features**: Velocity ratios to set max, first rep, global mean\n- **Residual features**: Velocity residual from RIR prediction, standardized residuals\n- **Volume features**: Rep number in session, cumulative volume\n- **Interaction features**: RIR×Load, Position×RIR, Volume×Velocity\n- **Cross-level features**: Z-scores vs population at same load or RIR level\n\n**Threshold Selection Strategy:**\n\nRather than using an arbitrary contamination rate (e.g., 5%), we select the threshold based on **visual inspection of the score distribution**. The goal is to identify observations that naturally \"cluster away\" from the main distribution—where the anomaly score curve shows a clear separation or inflection point. This data-driven approach ensures we flag only truly unusual observations rather than forcing a predetermined percentage.\n\nWe use **Leave-One-Out Cross-Validation (LOO-CV)** to obtain robust anomaly scores that aren't biased by the observation being scored.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (!is.null(lmm_results) && !is.null(lmm_results$data)) {\n  data <- lmm_results$data\n\n  # Use FeatureEngineer to create comprehensive features\n  fe <- anomaly_detector$get_feature_engineer()$new()\n  feature_result <- fe$engineer_features(data)\n\n  # Get ALL observation-level features (not just the 10-feature subset)\n  obs_features <- feature_result$observation_features\n  all_obs_feature_names <- feature_result$feature_names$observation  # ALL features\n\n  # Use all engineered features that exist in the data\n  available_features <- intersect(all_obs_feature_names, names(obs_features))\n  # Filter to only numeric features (exclude boolean flags if problematic)\n  numeric_mask <- sapply(obs_features[, available_features, drop = FALSE], is.numeric)\n  available_features <- available_features[numeric_mask]\n\n  cat(sprintf(\"**Observation-Level Feature Engineering:**\\n\\n\"))\n  cat(sprintf(\"- Total engineered features: **%d**\\n\", length(available_features)))\n  cat(sprintf(\"- Feature categories:\\n\"))\n  cat(sprintf(\"  - Z-scores: velocity_z_global, velocity_z_within_participant, velocity_z_within_set, rir_z_global\\n\"))\n  cat(sprintf(\"  - Position: set_position_normalized, velocity_decay_from_start, velocity_rank_in_set\\n\"))\n  cat(sprintf(\"  - Ratios: velocity_ratio_to_global, velocity_ratio_to_set_max, velocity_ratio_to_set_first, velocity_ratio_to_expected\\n\"))\n  cat(sprintf(\"  - Residuals: velocity_residual_from_rir, standardized_residual_rir\\n\"))\n  cat(sprintf(\"  - Volume: rep_number_in_session, cumulative_volume\\n\"))\n  cat(sprintf(\"  - Interactions: rir_x_load_interaction, set_position_x_rir, cumulative_volume_x_velocity\\n\"))\n  cat(sprintf(\"  - Cross-level: pl_z_vs_population_at_load, pr_z_vs_population_at_rir, etc.\\n\\n\"))\n\n  # Cross-validated detection with ALL engineered features\n  # Use initial contamination to get scores, then refine threshold visually\n  cv_result <- anomaly_detector$detect_anomalies_cv(\n    obs_features, available_features, contamination = 0.05\n  )\n\n  # Refine threshold based on visual gap detection\n  # Looking at the score distribution, observations above 0.60 clearly separate from the main cluster\n  sorted_scores <- sort(cv_result$scores, decreasing = TRUE)\n\n  # Find natural gap: where consecutive score differences are largest\n  score_diffs <- diff(sorted_scores)\n  # Look for gap in top 10% of scores\n  n_check <- max(10, ceiling(0.10 * length(sorted_scores)))\n  top_diffs <- score_diffs[1:n_check]\n  gap_idx <- which.max(abs(top_diffs))\n\n  # The threshold is the score just below the gap\n  visual_threshold <- sorted_scores[gap_idx + 1]\n\n  # Apply the visually-selected threshold\n  cv_result$threshold <- visual_threshold\n  cv_result$is_anomaly <- cv_result$scores >= visual_threshold\n  cv_result$anomaly_indices <- which(cv_result$is_anomaly)\n  cv_result$n_anomalies <- sum(cv_result$is_anomaly)\n\n  # Store for later use\n  cv_anomaly_result <- cv_result\n  cv_obs_features <- obs_features\n  cv_available_features <- available_features\n  cv_feature_result <- feature_result\n\n  cat(sprintf(\"**Observation-Level Detection Results:**\\n\\n\"))\n  cat(sprintf(\"- Observations analyzed: %d\\n\", length(cv_result$scores)))\n  cat(sprintf(\"- Anomalies flagged: %d (%.1f%%)\\n\",\n              cv_result$n_anomalies,\n              100 * cv_result$n_anomalies / length(cv_result$scores)))\n  cat(sprintf(\"- Threshold (visual gap detection): %.3f\\n\", cv_result$threshold))\n  cat(sprintf(\"\\n**Threshold Rationale:** The threshold was selected by identifying where anomaly scores show a natural separation—observations above this threshold cluster distinctly away from the main distribution, indicating genuinely unusual patterns rather than arbitrary percentile cutoffs.\\n\"))\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n**Observation-Level Feature Engineering:**\n\n- Total engineered features: **23**\n- Feature categories:\n  - Z-scores: velocity_z_global, velocity_z_within_participant, velocity_z_within_set, rir_z_global\n  - Position: set_position_normalized, velocity_decay_from_start, velocity_rank_in_set\n  - Ratios: velocity_ratio_to_global, velocity_ratio_to_set_max, velocity_ratio_to_set_first, velocity_ratio_to_expected\n  - Residuals: velocity_residual_from_rir, standardized_residual_rir\n  - Volume: rep_number_in_session, cumulative_volume\n  - Interactions: rir_x_load_interaction, set_position_x_rir, cumulative_volume_x_velocity\n  - Cross-level: pl_z_vs_population_at_load, pr_z_vs_population_at_rir, etc.\n\n**Observation-Level Detection Results:**\n\n- Observations analyzed: 406\n- Anomalies flagged: 5 (1.2%)\n- Threshold (visual gap detection): 0.606\n\n**Threshold Rationale:** The threshold was selected by identifying where anomaly scores show a natural separation—observations above this threshold cluster distinctly away from the main distribution, indicating genuinely unusual patterns rather than arbitrary percentile cutoffs.\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nif (exists(\"cv_anomaly_result\")) {\n  anomaly_detector$plot_score_distribution_with_threshold(\n    cv_anomaly_result,\n    show_quantiles = TRUE,\n    title = sprintf(\"Observation-Level Anomaly Scores (%d Engineered Features)\",\n                    length(cv_available_features))\n  )\n}\n```\n\n::: {.cell-output-display}\n![Distribution of cross-validated anomaly scores for observation-level model using all engineered features. The threshold is set at the natural gap where high-scoring observations separate from the main cluster.](deadlift_study_files/figure-html/fig-cv-score-distribution-1.png){#fig-cv-score-distribution width=100%}\n:::\n:::\n\n\n#### 5.8.2 Anomalous Observation Details {#sec-anomaly-details}\n\nFor each flagged observation, we provide:\n1. **Original values**: The raw measurements (velocity, RIR, load) for interpretation\n2. **SHAP-like contributions**: Which engineered features drove the anomaly score\n3. **Narrative explanation**: A human-readable interpretation of why the observation is unusual\n\n\n::: {#tbl-anomaly-raw-values .cell tbl-cap='Original feature values for anomalous observations. These raw measurements help interpret why each observation was flagged as unusual.'}\n\n```{.r .cell-code}\nif (exists(\"cv_anomaly_result\") && cv_anomaly_result$n_anomalies > 0) {\n  data <- lmm_results$data\n\n  # Get anomaly indices\n  anomaly_idx <- cv_anomaly_result$anomaly_indices\n\n  # Build table with original values\n  anomaly_data <- data.frame(\n    Row = anomaly_idx,\n    Participant = data$id[anomaly_idx],\n    Velocity = sprintf(\"%.3f\", data$mean_velocity[anomaly_idx]),\n    RIR = data$rir[anomaly_idx],\n    Load = data$load_percentage[anomaly_idx],\n    Day = data$day[anomaly_idx],\n    Set = sapply(strsplit(as.character(data$set_id[anomaly_idx]), \"_\"), function(x) tail(x, 1)),\n    Score = sprintf(\"%.3f\", cv_anomaly_result$scores[anomaly_idx])\n  )\n\n  # Order by score (most anomalous first)\n  anomaly_data <- anomaly_data[order(cv_anomaly_result$scores[anomaly_idx], decreasing = TRUE), ]\n\n  format_table(head(anomaly_data, 15), col.names = c(\"Row\", \"ID\", \"Velocity (m/s)\", \"RIR\", \"Load\", \"Day\", \"Set\", \"CV Score\"))\n} else {\n  cat(\"No anomalies detected with the CV method.\")\n}\n```\n\n::: {.cell-output-display}\n\n\n|   | Row|ID  |Velocity (m/s) | RIR|Load |Day   |Set |CV Score |\n|:--|---:|:---|:--------------|---:|:----|:-----|:---|:--------|\n|4  | 122|P09 |0.670          |   7|80%  |Day 2 |S2  |0.646    |\n|1  |  37|P05 |0.653          |   7|80%  |Day 2 |S2  |0.640    |\n|2  |  61|P02 |0.578          |   5|90%  |Day 1 |S1  |0.631    |\n|5  | 123|P09 |0.675          |   6|80%  |Day 2 |S2  |0.622    |\n|3  | 111|P09 |0.200          |   0|90%  |Day 1 |S1  |0.606    |\n\n\n:::\n:::\n\n\n#### 5.8.3 SHAP-like Feature Contributions {#sec-shap-contributions}\n\nFor each anomalous observation, we compute **permutation-based feature contributions**. This SHAP-like approach measures how much each engineered feature contributes to the anomaly score by replacing feature values with population medians.\n\n**Positive contributions** indicate features that *increase* the anomaly score (make the observation more unusual).\n**Negative contributions** indicate features that *decrease* the score (make it less unusual).\n\n\n::: {#tbl-shap-summary .cell tbl-cap='Digestible summary of anomaly explanations showing top 3 contributing features per observation. Arrows indicate direction (↑ increases anomaly score, ↓ decreases it).'}\n\n```{.r .cell-code}\nif (exists(\"cv_anomaly_result\") && cv_anomaly_result$n_anomalies > 0) {\n  # Ensure id column is present in features\n  if (!\"id\" %in% names(cv_obs_features)) {\n    cv_obs_features$id <- lmm_results$data$id\n  }\n\n  # Compute SHAP-like explanations using engineered features\n  obs_shap <- anomaly_detector$explain_anomalies_shap(\n    cv_anomaly_result,\n    cv_obs_features,\n    cv_available_features,\n    participant_col = \"id\",\n    max_anomalies = 20\n  )\n\n  # Store for later use\n  cv_shap_result <- obs_shap\n\n  if (obs_shap$n_anomalies > 0) {\n    # Generate digestible summary table\n    summary_df <- anomaly_detector$summarize_shap_contributions(obs_shap, top_k = 3)\n\n    format_table(\n      head(summary_df, 15),\n      col.names = c(\"Participant\", \"Obs #\", \"Score\", \"Rank\",\n                   \"Top Feature\", \"2nd Feature\", \"3rd Feature\")\n    )\n  }\n} else {\n  cat(\"No anomalies detected with CV method.\")\n}\n```\n\n::: {.cell-output-display}\n\n\n|Participant                          | Obs #| Score| Rank|Top Feature                       |2nd Feature                                |3rd Feature                      |\n|:------------------------------------|-----:|-----:|----:|:---------------------------------|:------------------------------------------|:--------------------------------|\n|c(\"P05\", \"P02\", \"P09\", \"P09\", \"P09\") |    37| 0.640|    1|pr_ratio_to_global_at_rir ↑0.038  |velocity_deviation_from_participant ↑0.026 |velocity_z_global ↑0.021         |\n|                                     |    61| 0.631|    2|velocity_residual_from_rir ↑0.028 |velocity_ratio_to_expected ↑0.026          |standardized_residual_rir ↑0.024 |\n|                                     |   111| 0.606|    3|pr_z_vs_population_at_rir ↑0.015  |pl_z_vs_population_at_load ↑0.013          |pr_ratio_to_global_at_rir ↑0.012 |\n|                                     |   122| 0.646|    4|pr_ratio_to_global_at_rir ↑0.037  |velocity_deviation_from_participant ↑0.021 |velocity_z_global ↑0.019         |\n|                                     |   123| 0.622|    5|pr_ratio_to_global_at_rir ↑0.036  |velocity_z_global ↑0.020                   |pr_z_vs_population_at_rir ↑0.019 |\n\n\n:::\n:::\n\n\n```{.r .cell-code}\nif (exists(\"cv_anomaly_result\") && cv_anomaly_result$n_anomalies > 0 && exists(\"cv_shap_result\")) {\n  data <- lmm_results$data\n  anomaly_idx <- cv_anomaly_result$anomaly_indices\n  scores <- cv_anomaly_result$scores[anomaly_idx]\n\n  cat(\"**Narrative Interpretation of Top Anomalies:**\\n\\n\")\n  cat(\"Below we interpret each flagged observation, explaining *why* it's unusual based on the engineered features and original measurements.\\n\\n\")\n\n  # Get top 5 anomalies for interpretation\n  top_idx <- head(order(scores, decreasing = TRUE), 5)\n\n  for (i in seq_along(top_idx)) {\n    rank <- i\n    idx <- anomaly_idx[top_idx[i]]\n    obs <- data[idx, ]\n    score <- round(scores[top_idx[i]], 3)\n\n    # Build interpretation using original values\n    velocity <- round(obs$mean_velocity, 3)\n    rir <- obs$rir\n    load <- obs$load_percentage\n    pid <- obs$id\n    day <- obs$day\n\n    # Get engineered feature values for this observation\n    velocity_z_global <- round(cv_obs_features$velocity_z_global[idx], 2)\n    velocity_z_participant <- round(cv_obs_features$velocity_z_within_participant[idx], 2)\n\n    # Compute population stats for context\n    velocity_mean <- round(mean(data$mean_velocity, na.rm = TRUE), 3)\n    velocity_for_rir <- round(mean(data$mean_velocity[data$rir == rir], na.rm = TRUE), 3)\n    velocity_for_load <- round(mean(data$mean_velocity[data$load_percentage == load], na.rm = TRUE), 3)\n\n    # Determine primary anomaly type from engineered features\n    if (abs(velocity_z_global) > 2) {\n      anomaly_type <- if (velocity_z_global > 0) \"globally fast\" else \"globally slow\"\n    } else if (abs(velocity_z_participant) > 2) {\n      anomaly_type <- if (velocity_z_participant > 0) \"unusually fast for this participant\" else \"unusually slow for this participant\"\n    } else if (velocity < velocity_for_rir * 0.85) {\n      anomaly_type <- sprintf(\"slower than typical for RIR %d (expected ~%.3f m/s)\", rir, velocity_for_rir)\n    } else if (velocity > velocity_for_rir * 1.15) {\n      anomaly_type <- sprintf(\"faster than typical for RIR %d (expected ~%.3f m/s)\", rir, velocity_for_rir)\n    } else {\n      anomaly_type <- \"atypical multivariate pattern\"\n    }\n\n    cat(sprintf(\"%d. **%s** (Row %d, CV Score = %.3f)\\n\", rank, pid, idx, score))\n    cat(sprintf(\"   - **Measurements**: Velocity = **%.3f m/s** at RIR = **%d** with **%s** load (%s)\\n\",\n                velocity, rir, load, day))\n    cat(sprintf(\"   - **Comparison**: Population mean = %.3f m/s | RIR %d mean = %.3f m/s | %s mean = %.3f m/s\\n\",\n                velocity_mean, rir, velocity_for_rir, load, velocity_for_load))\n    cat(sprintf(\"   - **Z-scores**: Global = %.2f | Within-participant = %.2f\\n\",\n                velocity_z_global, velocity_z_participant))\n    cat(sprintf(\"   - **Interpretation**: This observation is **%s**.\\n\\n\", anomaly_type))\n  }\n\n  cat(\"\\n*Note: These interpretations combine raw measurements with engineered features (z-scores, residuals, interactions) to explain the multivariate anomaly pattern.*\\n\")\n}\n```\n\n**Narrative Interpretation of Top Anomalies:**\n\nBelow we interpret each flagged observation, explaining *why* it's unusual based on the engineered features and original measurements.\n\n1. **P09** (Row 122, CV Score = 0.646)\n   - **Measurements**: Velocity = **0.670 m/s** at RIR = **7** with **80%** load (Day 2)\n   - **Comparison**: Population mean = 0.288 m/s | RIR 7 mean = 0.371 m/s | 80% mean = 0.304 m/s\n   - **Z-scores**: Global = 3.99 | Within-participant = 1.69\n   - **Interpretation**: This observation is **globally fast**.\n\n2. **P05** (Row 37, CV Score = 0.640)\n   - **Measurements**: Velocity = **0.653 m/s** at RIR = **7** with **80%** load (Day 2)\n   - **Comparison**: Population mean = 0.288 m/s | RIR 7 mean = 0.371 m/s | 80% mean = 0.304 m/s\n   - **Z-scores**: Global = 3.81 | Within-participant = 1.91\n   - **Interpretation**: This observation is **globally fast**.\n\n3. **P02** (Row 61, CV Score = 0.631)\n   - **Measurements**: Velocity = **0.578 m/s** at RIR = **5** with **90%** load (Day 1)\n   - **Comparison**: Population mean = 0.288 m/s | RIR 5 mean = 0.350 m/s | 90% mean = 0.261 m/s\n   - **Z-scores**: Global = 3.02 | Within-participant = 2.70\n   - **Interpretation**: This observation is **globally fast**.\n\n4. **P09** (Row 123, CV Score = 0.622)\n   - **Measurements**: Velocity = **0.675 m/s** at RIR = **6** with **80%** load (Day 2)\n   - **Comparison**: Population mean = 0.288 m/s | RIR 6 mean = 0.373 m/s | 80% mean = 0.304 m/s\n   - **Z-scores**: Global = 4.04 | Within-participant = 1.72\n   - **Interpretation**: This observation is **globally fast**.\n\n5. **P09** (Row 111, CV Score = 0.606)\n   - **Measurements**: Velocity = **0.200 m/s** at RIR = **0** with **90%** load (Day 1)\n   - **Comparison**: Population mean = 0.288 m/s | RIR 0 mean = 0.206 m/s | 90% mean = 0.261 m/s\n   - **Z-scores**: Global = -0.92 | Within-participant = -1.46\n   - **Interpretation**: This observation is **atypical multivariate pattern**.\n\n\n*Note: These interpretations combine raw measurements with engineered features (z-scores, residuals, interactions) to explain the multivariate anomaly pattern.*\n\n::: {.cell}\n\n```{.r .cell-code}\nif (exists(\"cv_shap_result\") && cv_shap_result$n_anomalies > 0) {\n  anomaly_detector$plot_observation_contributions(\n    cv_shap_result,\n    max_display = 10,\n    top_k = 8,  # Show top 8 features per observation\n    title = \"Feature Contributions for Anomalous Observations (Engineered Features)\"\n  )\n} else {\n  cat(\"No SHAP results available for plotting.\")\n}\n```\n\n::: {.cell-output-display}\n![SHAP-like feature contributions for anomalous observations using all 10 engineered features. Each bar shows how much a feature contributed to the observation's anomaly score. Red bars indicate features that increased the anomaly score, blue bars indicate features that decreased it.](deadlift_study_files/figure-html/fig-obs-contributions-1.png){#fig-obs-contributions width=100%}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nif (exists(\"cv_shap_result\") && cv_shap_result$n_anomalies > 0) {\n  anomaly_detector$plot_observation_aggregate_importance(\n    cv_shap_result,\n    top_n = 10,\n    title = \"Observation-Level Engineered Feature Importance\"\n  )\n} else {\n  cat(\"No SHAP results available for importance plot.\")\n}\n```\n\n::: {.cell-output-display}\n![Aggregate feature importance across all anomalous observations using engineered features. Shows which features most commonly contribute to the anomaly scores.](deadlift_study_files/figure-html/fig-obs-aggregate-importance-1.png){#fig-obs-aggregate-importance width=100%}\n:::\n:::\n\n\n**Interpretation:** The SHAP-like contributions use ALL engineered features (~25 features) including:\n\n- **Velocity z-scores** (global, within-participant, within-set): Identify observations that deviate from expected velocities\n- **Position features** (normalized position, decay from start, rank): Capture fatigue patterns within sets\n- **Ratio features** (to set max, to first rep, to global): Compare velocity to references\n- **Residual features** (RIR residual, standardized residual): Identify deviations from the velocity-RIR relationship\n- **Volume features** (rep number, cumulative volume): Track session progression\n- **Interaction features** (RIR×load, position×RIR, volume×velocity): Capture complex multivariate patterns\n- **Cross-level features** (population comparisons at same load/RIR): Compare to similar conditions\n\nPositive contributions indicate that a feature's value *increases* the anomaly score (makes the observation more unusual), while negative contributions indicate the opposite. This permutation-based approach directly measures each feature's impact on the Isolation Forest's anomaly scoring.\n\n#### 5.8.4 Participant-Level Anomaly Detection {#sec-participant-anomalies}\n\nIn addition to observation-level anomalies, we train a **separate Isolation Forest model for participant-level anomalies** using participant-aggregated features (~40 features). This model identifies participants whose overall patterns are unusual compared to the population.\n\n**Participant-Level Features:**\n\n- **Velocity profile**: Mean, SD, CV, range, IQR, skewness, kurtosis, percentiles\n- **RIR relationship**: Slope, intercept, R², range sensitivity\n- **Set behavior**: Number of sets, mean reps per set, rep variability\n- **Load sensitivity**: Velocity change across loads, number of loads tested\n- **Population comparisons**: Z-scores, percentile ranks, ratio to population norms\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (exists(\"cv_feature_result\")) {\n  # Get participant-level features\n  part_features <- cv_feature_result$participant_features\n  all_part_feature_names <- cv_feature_result$feature_names$participant\n\n  # Use all participant features that exist and are numeric\n  available_part_features <- intersect(all_part_feature_names, names(part_features))\n  numeric_mask <- sapply(part_features[, available_part_features, drop = FALSE], is.numeric)\n  available_part_features <- available_part_features[numeric_mask]\n\n  cat(sprintf(\"**Participant-Level Feature Engineering:**\\n\\n\"))\n  cat(sprintf(\"- Total engineered features: **%d**\\n\", length(available_part_features)))\n  cat(sprintf(\"- Participants: %d\\n\\n\", nrow(part_features)))\n\n  # Standard detection (not CV since we have few participants)\n  part_result <- anomaly_detector$detect_raw_data_anomalies(\n    part_features, available_part_features, contamination = 0.10  # Higher threshold for small N\n  )\n\n  # Store for later\n  part_anomaly_result <- part_result\n  part_available_features <- available_part_features\n\n  cat(sprintf(\"**Participant-Level Detection Results:**\\n\\n\"))\n  cat(sprintf(\"- Participants analyzed: %d\\n\", length(part_result$scores)))\n  cat(sprintf(\"- Anomalous participants: %d (%.1f%%)\\n\",\n              part_result$n_anomalies,\n              100 * part_result$n_anomalies / length(part_result$scores)))\n  cat(sprintf(\"- Threshold (10%% contamination): %.3f\\n\", part_result$threshold))\n\n  if (part_result$n_anomalies > 0) {\n    # Show which participants are anomalous\n    anomalous_idx <- part_result$anomaly_indices\n    cat(\"\\n**Anomalous Participants:**\\n\")\n    for (i in anomalous_idx) {\n      pid <- part_features$id[i]\n      score <- round(part_result$scores[i], 3)\n      cat(sprintf(\"- %s (score: %.3f)\\n\", pid, score))\n    }\n  }\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n**Participant-Level Feature Engineering:**\n\n- Total engineered features: **41**\n- Participants: 19\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n**Participant-Level Detection Results:**\n\n- Participants analyzed: 19\n- Anomalous participants: 2 (10.5%)\n- Threshold (10% contamination): 0.540\n\n**Anomalous Participants:**\n- P05 (score: 0.597)\n- P09 (score: 0.569)\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nif (exists(\"part_anomaly_result\") && exists(\"cv_feature_result\")) {\n  part_features <- cv_feature_result$participant_features\n\n  # Create bar plot of participant scores\n  score_df <- data.frame(\n    participant = part_features$id,\n    score = part_anomaly_result$scores,\n    is_anomaly = part_anomaly_result$is_anomaly\n  )\n  score_df <- score_df[order(score_df$score, decreasing = TRUE), ]\n  score_df$participant <- factor(score_df$participant, levels = score_df$participant)\n\n  ggplot2::ggplot(score_df, ggplot2::aes(x = participant, y = score, fill = is_anomaly)) +\n    ggplot2::geom_col() +\n    ggplot2::geom_hline(yintercept = part_anomaly_result$threshold, linetype = \"dashed\", color = \"red\") +\n    ggplot2::scale_fill_manual(values = c(\"FALSE\" = \"#2E86AB\", \"TRUE\" = \"#E63946\"),\n                               labels = c(\"Normal\", \"Anomalous\")) +\n    ggplot2::labs(\n      title = sprintf(\"Participant-Level Anomaly Scores (%d Features)\", length(part_available_features)),\n      subtitle = sprintf(\"Threshold = %.3f (10%% contamination)\", part_anomaly_result$threshold),\n      x = \"Participant\", y = \"Anomaly Score\", fill = \"Status\"\n    ) +\n    ggplot2::theme_minimal() +\n    ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 45, hjust = 1))\n}\n```\n\n::: {.cell-output-display}\n![Participant-level anomaly scores using all participant-aggregated features. Each bar represents a participant's anomaly score from the Isolation Forest model.](deadlift_study_files/figure-html/fig-participant-anomaly-scores-1.png){#fig-participant-anomaly-scores width=100%}\n:::\n:::\n\n\n#### 5.8.5 Random Effects Anomalies\n\nWe also screen participants based on their random effects (individual intercepts and slopes) to identify individuals with unusual velocity-RIR patterns.\n\n\n::: {#tbl-re-anomalies .cell tbl-cap='Random effects anomaly detection by participant'}\n\n```{.r .cell-code}\nif (!is.null(lmm_results) && !is.null(lmm_results$advanced_validation)) {\n  av <- lmm_results$advanced_validation\n\n  if (!is.null(av$anomalies) && !is.null(av$anomalies$random_effects)) {\n    re <- av$anomalies$random_effects\n\n    re_df <- data.frame(\n      Category = c(\"Total Participants\", \"Anomalous\", \"Borderline\", \"Normal\"),\n      Count = c(re$n_participants, re$n_anomalous, re$n_borderline, re$n_normal),\n      Interpretation = c(\n        \"\",\n        \"Unusual velocity-RIR relationship\",\n        \"Some deviation from population\",\n        \"Typical relationship\"\n      )\n    )\n\n    format_table(re_df, col.names = c(\"Category\", \"Count\", \"Interpretation\"))\n  }\n}\n```\n\n::: {.cell-output-display}\n\n\n|Category           | Count|Interpretation                    |\n|:------------------|-----:|:---------------------------------|\n|Total Participants |    19|                                  |\n|Anomalous          |     2|Unusual velocity-RIR relationship |\n|Borderline         |    15|Some deviation from population    |\n|Normal             |     2|Typical relationship              |\n\n\n:::\n:::\n\n\n```{.r .cell-code}\nif (!is.null(lmm_results) && !is.null(lmm_results$advanced_validation)) {\n  av <- lmm_results$advanced_validation\n\n  if (!is.null(av$anomalies) && !is.null(av$anomalies$random_effects)) {\n    re <- av$anomalies$random_effects\n\n    if (length(re$anomalous_ids) > 0) {\n      cat(\"**Anomalous Participants:** \", paste(re$anomalous_ids, collapse = \", \"), \"\\n\\n\")\n      cat(\"These participants have velocity-RIR relationships that differ substantially from the population pattern. This is not necessarily problematic---it confirms the need for individual calibration.\\n\")\n    } else {\n      cat(\"No participants were classified as anomalous based on their random effects.\\n\")\n    }\n  }\n}\n```\n\n**Anomalous Participants:**  P05, P09 \n\nThese participants have velocity-RIR relationships that differ substantially from the population pattern. This is not necessarily problematic---it confirms the need for individual calibration.\n\n\n### 5.9 Why Isolation Forest Over Cook's Distance {#sec-if-vs-cooks}\n\nWe choose Isolation Forest as our primary anomaly detection method for several reasons:\n\n**Advantages of Isolation Forest:**\n\n1. **No distributional assumptions**: Unlike Cook's distance (which assumes normality and linear relationships), Isolation Forest works with any data distribution\n2. **Multivariate detection**: Identifies unusual *combinations* of features, not just univariate outliers\n3. **Feature explainability**: With SHAP-like permutation analysis, we can explain *why* each observation is flagged\n4. **Data-driven thresholds**: Elbow detection finds natural breaks in anomaly scores rather than arbitrary cutoffs\n5. **Scales to high dimensions**: Works well with our 50+ engineered features\n\n**Limitations of Cook's Distance:**\n\n- Measures *influence on regression coefficients*, not inherent data quality\n- Tends to over-flag observations with high leverage (extreme X values)\n- The 4/n threshold is arbitrary and often flags too many observations\n- Cannot explain why an observation is flagged\n\n\n::: {#tbl-if-vs-cooks .cell tbl-cap='Comparison between Isolation Forest and Cook\\'s Distance flagging (for reference)'}\n\n```{.r .cell-code}\nif (!is.null(lmm_results) && !is.null(lmm_results$advanced_validation)) {\n  av <- lmm_results$advanced_validation\n\n  if (!is.null(av$if_vs_cooks_comparison)) {\n    comp <- av$if_vs_cooks_comparison\n\n    comparison_df <- data.frame(\n      Metric = c(\n        \"Observations flagged by Isolation Forest\",\n        \"Observations flagged by Cook's Distance\",\n        \"Agreement rate\"\n      ),\n      Value = c(\n        comp$both_flagged + comp$only_isolation_forest,\n        comp$both_flagged + comp$only_cooks_distance,\n        sprintf(\"%.1f%%\", comp$agreement_rate * 100)\n      )\n    )\n\n    format_table(comparison_df, col.names = c(\"Metric\", \"Value\"))\n  }\n}\n```\n\n::: {.cell-output-display}\n\n\n|Metric                                   |Value |\n|:----------------------------------------|:-----|\n|Observations flagged by Isolation Forest |22    |\n|Observations flagged by Cook's Distance  |228   |\n|Agreement rate                           |48.8% |\n\n\n:::\n:::\n\n\n```{.r .cell-code}\nif (!is.null(lmm_results) && !is.null(lmm_results$advanced_validation)) {\n  av <- lmm_results$advanced_validation\n\n  if (!is.null(av$if_vs_cooks_comparison)) {\n    comp <- av$if_vs_cooks_comparison\n\n    if (comp$only_cooks_distance > comp$only_isolation_forest * 3) {\n      cat(\"**Note:** Cook's distance flags significantly more observations than Isolation Forest. \",\n          \"This is expected because Cook's distance is sensitive to leverage (extreme RIR or load values) \",\n          \"rather than truly anomalous patterns. We focus on Isolation Forest results for data quality assessment.\\n\")\n    }\n  }\n}\n```\n\n**Note:** Cook's distance flags significantly more observations than Isolation Forest.  This is expected because Cook's distance is sensitive to leverage (extreme RIR or load values)  rather than truly anomalous patterns. We focus on Isolation Forest results for data quality assessment.\n\n\n#### 5.9.1 Cook's Distance for Final LMER Model\n\nWhile Isolation Forest is better for general data quality screening, **Cook's distance remains valuable for assessing influence on our final model**. Here we apply Cook's distance specifically to the best LMER model specification to identify observations that disproportionately affect the model coefficients.\n\n\n::: {#tbl-cooks-final-model .cell tbl-cap='Cook\\'s distance diagnostics for the final LMER model. Observations with Cook\\'s D > 4/n are flagged as influential.'}\n\n```{.r .cell-code}\nif (!is.null(lmm_results) && !is.null(lmm_results$best_model) &&\n    !is.null(lmm_results$best_model$model)) {\n\n  model <- lmm_results$best_model$model\n  data <- lmm_results$data\n\n  # Compute Cook's distance using influence.ME package\n  if (requireNamespace(\"influence.ME\", quietly = TRUE)) {\n    # Get influence measures (can be slow for large models)\n    cooks_d <- tryCatch({\n      influence.ME::cooks.distance.estex(\n        influence.ME::influence(model, obs = TRUE)\n      )\n    }, error = function(e) NULL)\n\n    if (!is.null(cooks_d)) {\n      n <- length(cooks_d)\n      threshold <- 4 / n\n      influential <- cooks_d > threshold\n\n      # Summary table\n      cooks_df <- data.frame(\n        Metric = c(\n          \"Total Observations\",\n          \"Threshold (4/n)\",\n          \"Influential Observations\",\n          \"Percentage Influential\",\n          \"Max Cook's D\",\n          \"Mean Cook's D\"\n        ),\n        Value = c(\n          n,\n          sprintf(\"%.4f\", threshold),\n          sum(influential),\n          sprintf(\"%.1f%%\", 100 * sum(influential) / n),\n          sprintf(\"%.4f\", max(cooks_d)),\n          sprintf(\"%.4f\", mean(cooks_d))\n        )\n      )\n\n      format_table(cooks_df, col.names = c(\"Metric\", \"Value\"))\n    }\n  } else {\n    cat(\"Note: influence.ME package not available for Cook's distance computation.\\n\")\n  }\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNote: influence.ME package not available for Cook's distance computation.\n```\n\n\n:::\n:::\n\n::: {#tbl-cooks-influential-obs .cell tbl-cap='Details of observations with high Cook\\'s distance (influence on model coefficients)'}\n\n```{.r .cell-code}\nif (!is.null(lmm_results) && !is.null(lmm_results$best_model) &&\n    !is.null(lmm_results$best_model$model)) {\n\n  model <- lmm_results$best_model$model\n  data <- lmm_results$data\n\n  if (requireNamespace(\"influence.ME\", quietly = TRUE)) {\n    cooks_d <- tryCatch({\n      influence.ME::cooks.distance.estex(\n        influence.ME::influence(model, obs = TRUE)\n      )\n    }, error = function(e) NULL)\n\n    if (!is.null(cooks_d)) {\n      n <- length(cooks_d)\n      threshold <- 4 / n\n      influential_idx <- which(cooks_d > threshold)\n\n      if (length(influential_idx) > 0) {\n        # Get top 15 most influential\n        top_idx <- influential_idx[order(cooks_d[influential_idx], decreasing = TRUE)]\n        top_idx <- head(top_idx, 15)\n\n        influential_obs <- data[top_idx, c(\"id\", \"mean_velocity\", \"rir\", \"load_percentage\", \"day\")]\n        influential_obs$cooks_d <- round(cooks_d[top_idx], 4)\n        influential_obs$velocity <- round(influential_obs$mean_velocity, 3)\n        influential_obs <- influential_obs[, c(\"id\", \"velocity\", \"rir\", \"load_percentage\", \"day\", \"cooks_d\")]\n\n        format_table(\n          influential_obs,\n          col.names = c(\"Participant\", \"Velocity (m/s)\", \"RIR\", \"Load\", \"Day\", \"Cook's D\")\n        )\n      } else {\n        cat(\"No observations exceed the Cook's distance threshold.\\n\")\n      }\n    }\n  }\n}\n```\n:::\n\n\n```{.r .cell-code}\nif (!is.null(lmm_results) && !is.null(lmm_results$best_model) &&\n    !is.null(lmm_results$best_model$model)) {\n\n  model <- lmm_results$best_model$model\n  data <- lmm_results$data\n\n  if (requireNamespace(\"influence.ME\", quietly = TRUE)) {\n    cooks_d <- tryCatch({\n      influence.ME::cooks.distance.estex(\n        influence.ME::influence(model, obs = TRUE)\n      )\n    }, error = function(e) NULL)\n\n    if (!is.null(cooks_d)) {\n      n <- length(cooks_d)\n      threshold <- 4 / n\n      influential_idx <- which(cooks_d > threshold)\n\n      cat(\"**Interpretation of Cook's Distance Results:**\\n\\n\")\n\n      if (length(influential_idx) == 0) {\n        cat(\"No observations have disproportionate influence on the model coefficients. \",\n            \"This suggests the model estimates are robust and not driven by individual observations.\\n\")\n      } else {\n        pct <- round(100 * length(influential_idx) / n, 1)\n        cat(sprintf(\"**%d observations (%.1f%%)** have Cook's distance > 4/n, indicating they influence the model coefficients. \",\n                    length(influential_idx), pct))\n\n        # Characterize influential observations\n        infl_data <- data[influential_idx, ]\n        mean_rir <- mean(infl_data$rir)\n        mean_vel <- mean(infl_data$mean_velocity)\n        global_mean_vel <- mean(data$mean_velocity)\n\n        if (mean_vel < global_mean_vel * 0.9) {\n          cat(\"These observations tend to have **lower velocities** than average, \")\n        } else if (mean_vel > global_mean_vel * 1.1) {\n          cat(\"These observations tend to have **higher velocities** than average, \")\n        }\n\n        if (mean_rir < 2) {\n          cat(\"and are concentrated near **failure (RIR 0-1)**. \")\n        } else if (mean_rir > 4) {\n          cat(\"and occur at **high RIR values**. \")\n        }\n\n        cat(\"\\n\\n\")\n        cat(\"**Recommendation:** These observations warrant review but should not be automatically removed. \",\n            \"High influence may reflect genuine individual variation rather than data quality issues. \",\n            \"Compare with Isolation Forest flags---observations flagged by both methods may be true anomalies.\\n\")\n      }\n    }\n  }\n}\n```\n\n\n### 5.10 Enhanced Multi-Level Anomaly Detection {#sec-enhanced-anomaly}\n\nThe previous section used a fixed 95th percentile threshold. Here we compare multiple data-driven threshold selection strategies and extend anomaly detection to the participant level using aggregate behavior patterns.\n\n#### 5.10.1 Threshold Strategy Comparison\n\nDifferent threshold selection strategies may identify different thresholds depending on the score distribution characteristics.\n\n\n::: {#tbl-threshold-comparison .cell tbl-cap='Comparison of threshold selection strategies for Isolation Forest scores'}\n\n```{.r .cell-code}\nif (!is.null(lmm_results) && !is.null(lmm_results$advanced_validation)) {\n  av <- lmm_results$advanced_validation\n\n  if (!is.null(av$anomalies) && !is.null(av$anomalies$threshold_comparison)) {\n    tc <- av$anomalies$threshold_comparison\n\n    tc_display <- data.frame(\n      Strategy = tc$strategy,\n      Threshold = sprintf(\"%.4f\", tc$threshold),\n      `N Flagged` = tc$n_flagged,\n      `Pct Flagged` = sprintf(\"%.1f%%\", (tc$n_flagged / max(tc$n_total, 1)) * 100),\n      check.names = FALSE\n    )\n\n    format_table(tc_display)\n  }\n}\n```\n\n::: {.cell-output-display}\n\n\n|                 |       |   |        |\n|:----------------|:------|--:|:-------|\n|fixed_percentile |0.6026 | 22|2200.0% |\n|elbow_detection  |0.5143 | 83|8300.0% |\n|gap_statistics   |0.6568 |  8|800.0%  |\n|knee_point       |0.7197 |  1|100.0%  |\n|mad_based        |0.5972 | 23|2300.0% |\n\n\n:::\n:::\n\n\n```{.r .cell-code}\nif (!is.null(lmm_results) && !is.null(lmm_results$advanced_validation)) {\n  av <- lmm_results$advanced_validation\n\n  if (!is.null(av$anomalies) && !is.null(av$anomalies$threshold_comparison)) {\n    tc <- av$anomalies$threshold_comparison\n\n    # Find the elbow and fixed strategies\n    elbow_row <- tc[tc$strategy == \"elbow_detection\", ]\n    fixed_row <- tc[tc$strategy == \"fixed_percentile\", ]\n\n    if (nrow(elbow_row) > 0 && nrow(fixed_row) > 0) {\n      cat(sprintf(\n        \"**Interpretation:** The elbow detection method identifies a threshold of %.4f (flagging %d observations), compared to the fixed 95th percentile threshold of %.4f (flagging %d observations). \",\n        elbow_row$threshold, elbow_row$n_flagged,\n        fixed_row$threshold, fixed_row$n_flagged\n      ))\n\n      if (elbow_row$threshold > fixed_row$threshold) {\n        cat(\"The higher elbow threshold suggests there is a clear separation between the normal score cluster and anomalous observations, supporting a more conservative flagging approach.\\n\")\n      } else {\n        cat(\"The thresholds are similar, indicating the 95th percentile is appropriate for this dataset.\\n\")\n      }\n    }\n  }\n}\n```\n\n**Interpretation:** The elbow detection method identifies a threshold of 0.5143 (flagging 83 observations), compared to the fixed 95th percentile threshold of 0.6026 (flagging 22 observations). The thresholds are similar, indicating the 95th percentile is appropriate for this dataset.\n\n\n#### 5.10.2 Elbow Detection Results\n\nUsing the elbow detection method, which identifies the natural cluster boundary in the score distribution:\n\n\n::: {#tbl-elbow-anomalies .cell tbl-cap='Anomaly detection using elbow-based threshold selection'}\n\n```{.r .cell-code}\nif (!is.null(lmm_results) && !is.null(lmm_results$advanced_validation)) {\n  av <- lmm_results$advanced_validation\n\n  if (!is.null(av$anomalies) && !is.null(av$anomalies$raw_data_v2)) {\n    v2 <- av$anomalies$raw_data_v2\n\n    elbow_df <- data.frame(\n      Metric = c(\n        \"Total Observations\",\n        \"Anomalies Detected\",\n        \"Anomaly Rate\",\n        \"Elbow Threshold\"\n      ),\n      Value = c(\n        v2$n_total,\n        v2$n_anomalies,\n        sprintf(\"%.1f%%\", v2$anomaly_rate * 100),\n        sprintf(\"%.4f\", v2$threshold)\n      )\n    )\n\n    format_table(elbow_df, col.names = c(\"Metric\", \"Value\"))\n  }\n}\n```\n\n::: {.cell-output-display}\n\n\n|Metric             |Value  |\n|:------------------|:------|\n|Total Observations |406    |\n|Anomalies Detected |83     |\n|Anomaly Rate       |20.4%  |\n|Elbow Threshold    |0.5143 |\n\n\n:::\n:::\n\n\n#### 5.10.3 Participant Behavior Profiling {#sec-participant-profiles}\n\nBeyond individual observations, we profile participants based on their aggregate behavior patterns to identify those with unusual overall performance characteristics.\n\n\n::: {#tbl-participant-profile .cell tbl-cap='Participant-level anomaly detection based on aggregate behavior patterns'}\n\n```{.r .cell-code}\nif (!is.null(lmm_results) && !is.null(lmm_results$advanced_validation)) {\n  av <- lmm_results$advanced_validation\n\n  if (!is.null(av$anomalies) && !is.null(av$anomalies$participant_profile)) {\n    pp <- av$anomalies$participant_profile\n\n    profile_df <- data.frame(\n      Metric = c(\n        \"Total Participants\",\n        \"Anomalous Participants\",\n        \"Anomaly Rate\",\n        \"Threshold\",\n        \"Detection Method\"\n      ),\n      Value = c(\n        pp$n_participants,\n        pp$n_anomalous,\n        sprintf(\"%.1f%%\", (pp$n_anomalous / pp$n_participants) * 100),\n        sprintf(\"%.4f\", pp$threshold),\n        pp$method\n      )\n    )\n\n    format_table(profile_df, col.names = c(\"Metric\", \"Value\"))\n  }\n}\n```\n\n::: {.cell-output-display}\n\n\n|Metric                 |Value            |\n|:----------------------|:----------------|\n|Total Participants     |19               |\n|Anomalous Participants |4                |\n|Anomaly Rate           |21.1%            |\n|Threshold              |0.5113           |\n|Detection Method       |isolation_forest |\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nif (!is.null(lmm_results) && !is.null(lmm_results$advanced_validation_full)) {\n  avf <- lmm_results$advanced_validation_full\n\n  if (!is.null(avf$participant_profile)) {\n    # Import ParticipantProfiler for plotting (use .. since QMD is in analyses/)\n    box::use(../R/calculators/participant_profiler[ParticipantProfiler])\n    profiler <- ParticipantProfiler$new()\n    profiler$plot_profiles(\n      avf$participant_profile,\n      title = \"Participant Anomaly Profiles\"\n    )\n  }\n}\n```\n\n::: {.cell-output-display}\n![Participant anomaly scores with threshold visualization. Each point represents a participant, ordered by their aggregate anomaly score. Red points indicate participants flagged as having unusual behavior patterns.](deadlift_study_files/figure-html/fig-participant-profiles-1.png){#fig-participant-profiles width=100%}\n:::\n:::\n\n\n```{.r .cell-code}\nif (!is.null(lmm_results) && !is.null(lmm_results$advanced_validation_full)) {\n  avf <- lmm_results$advanced_validation_full\n\n  if (!is.null(avf$participant_profile)) {\n    pp <- avf$participant_profile\n    anomalous_ids <- pp$get_anomalous_ids()\n\n    if (length(anomalous_ids) > 0) {\n      cat(\"**Anomalous Participants and SHAP-like Feature Contributions:**\\n\\n\")\n      cat(\"Each anomalous participant is explained by the features that most strongly contributed to their anomaly score. Positive contributions indicate features that *increased* the anomaly score (made the participant appear more unusual).\\n\\n\")\n\n      for (pid in anomalous_ids) {\n        explanation <- pp$get_explanation(pid)\n        cat(sprintf(\"- %s\\n\", explanation))\n      }\n\n      cat(\"\\n**Interpretation:** These participants show unusual combinations of aggregate features (velocity consistency, load sensitivity, RIR patterns) compared to the population. The feature contributions above explain *why* each participant was flagged---the specific features that deviated most from population norms.\\n\")\n    } else {\n      cat(\"No participants were flagged as anomalous based on their aggregate behavior patterns. All participants show typical velocity-load-RIR relationships.\\n\")\n    }\n  }\n}\n```\n\n**Anomalous Participants and SHAP-like Feature Contributions:**\n\nEach anomalous participant is explained by the features that most strongly contributed to their anomaly score. Positive contributions indicate features that *increased* the anomaly score (made the participant appear more unusual).\n\n- P05 flagged: p_load_sensitivity increases score by 0.057; p_velocity_cv increases score by 0.032; p_rir_slope increases score by 0.027\n- P09 flagged: p_mean_velocity increases score by 0.049; p_velocity_range increases score by 0.033; p_velocity_cv increases score by 0.012\n- P12 flagged: p_rir_r2 increases score by 0.046; p_velocity_cv increases score by 0.040; p_load_sensitivity increases score by 0.037\n- P19 flagged: p_rir_slope increases score by 0.039; p_reps_cv increases score by 0.024; p_velocity_cv increases score by 0.016\n\n**Interpretation:** These participants show unusual combinations of aggregate features (velocity consistency, load sensitivity, RIR patterns) compared to the population. The feature contributions above explain *why* each participant was flagged---the specific features that deviated most from population norms.\n\n::: {.cell}\n\n```{.r .cell-code}\nif (!is.null(lmm_results) && !is.null(lmm_results$advanced_validation_full)) {\n  avf <- lmm_results$advanced_validation_full\n\n  if (!is.null(avf$participant_profile)) {\n    pp <- avf$participant_profile\n\n    if (sum(pp$is_anomaly) > 0 && !is.null(pp$feature_contributions)) {\n      box::use(../R/calculators/participant_profiler[ParticipantProfiler])\n      profiler <- ParticipantProfiler$new()\n\n      tryCatch({\n        profiler$plot_all_anomaly_explanations(pp, top_k = 5)\n      }, error = function(e) {\n        cat(\"Feature contribution plot not available.\\n\")\n      })\n    }\n  }\n}\n```\n\n::: {.cell-output-display}\n![SHAP-like feature contributions for anomalous participants. Each bar shows how much a feature contributed to the participant's anomaly score. Blue bars (negative) indicate features that decreased the anomaly score, while red bars (positive) indicate features that increased it.](deadlift_study_files/figure-html/fig-participant-contributions-1.png){#fig-participant-contributions width=100%}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nif (!is.null(lmm_results) && !is.null(lmm_results$advanced_validation_full)) {\n  avf <- lmm_results$advanced_validation_full\n\n  if (!is.null(avf$participant_profile)) {\n    pp <- avf$participant_profile\n\n    if (sum(pp$is_anomaly) > 0 && !is.null(pp$feature_contributions)) {\n      box::use(../R/calculators/participant_profiler[ParticipantProfiler])\n      profiler <- ParticipantProfiler$new()\n\n      tryCatch({\n        profiler$plot_aggregate_importance(pp, top_k = 10)\n      }, error = function(e) {\n        cat(\"Aggregate importance plot not available.\\n\")\n      })\n    }\n  }\n}\n```\n\n::: {.cell-output-display}\n![Aggregate feature importance across all anomalous participants. This shows which features most commonly contribute to anomaly detection, helping identify the key behavioral patterns that distinguish anomalous participants.](deadlift_study_files/figure-html/fig-aggregate-importance-1.png){#fig-aggregate-importance width=100%}\n:::\n:::\n\n\n#### 5.10.4 Feature Engineering Summary\n\nThe enhanced anomaly detection uses a comprehensive feature engineering system with 12 feature groups across multiple aggregation levels:\n\n**Feature Group Categories:**\n\n1. **Observation-Level (per rep)**: Z-scores vs global and participant means, position in set\n2. **Set-Level (per set)**: Mean velocity, velocity decay, coefficient of variation\n3. **Participant-Level (aggregated)**: Overall velocity patterns, RIR sensitivity, load response\n4. **Participant × Set**: Performance deviation from participant's own norm\n5. **Participant × Load**: How each participant responds at different load levels\n6. **Participant × RIR**: Velocity-RIR relationship for each participant\n7. **Cross-Set Ratios**: Comparing performance across consecutive sets\n8. **Global Context Ratios**: Comparing each observation to population norms\n9. **Velocity Curve Features**: Decay patterns within sets\n10. **Session-Level Features**: Cumulative volume, fatigue tracking\n11. **Advanced Derived Features**: Residuals from RIR predictions, standardized deviations\n12. **Interaction Features**: RIR × Load interactions, position × RIR\n\n\n::: {#tbl-features-summary .cell tbl-cap='Summary of engineered features for anomaly detection'}\n\n```{.r .cell-code}\nif (!is.null(lmm_results) && !is.null(lmm_results$advanced_validation)) {\n  av <- lmm_results$advanced_validation\n\n  if (!is.null(av$anomalies) && !is.null(av$anomalies$features_result)) {\n    fr <- av$anomalies$features_result\n\n    features_df <- data.frame(\n      Level = c(\"Observation\", \"Set\", \"Participant\", \"Cross-Level\"),\n      `N Features` = c(\n        length(fr$feature_names$observation),\n        length(fr$feature_names$set),\n        length(fr$feature_names$participant),\n        length(fr$feature_names$participant_set) + length(fr$feature_names$participant_load) + length(fr$feature_names$participant_rir)\n      ),\n      Description = c(\n        \"Per-rep: z-scores, position, decay contribution\",\n        \"Per-set: mean, CV, decay slope, range\",\n        \"Per-participant: velocity profile, RIR sensitivity\",\n        \"Participant × (Set, Load, RIR): cross-level interactions\"\n      ),\n      check.names = FALSE\n    )\n\n    format_table(features_df)\n  }\n}\n```\n\n::: {.cell-output-display}\n\n\n|            |   |                                                         |\n|:-----------|--:|:--------------------------------------------------------|\n|Observation | 25|Per-rep: z-scores, position, decay contribution          |\n|Set         | 21|Per-set: mean, CV, decay slope, range                    |\n|Participant | 41|Per-participant: velocity profile, RIR sensitivity       |\n|Cross-Level | 24|Participant × (Set, Load, RIR): cross-level interactions |\n\n\n:::\n:::\n\n\n```{.r .cell-code}\nif (!is.null(lmm_results) && !is.null(lmm_results$advanced_validation)) {\n  av <- lmm_results$advanced_validation\n\n  if (!is.null(av$anomalies) && !is.null(av$anomalies$features_result)) {\n    fr <- av$anomalies$features_result\n\n    cat(\"**Key Observation-Level Features (for individual rep anomaly detection):**\\n\\n\")\n    key_obs <- c(\"velocity_z_global\", \"velocity_z_within_participant\", \"velocity_z_within_set\",\n                 \"set_position_normalized\", \"velocity_residual_from_rir\", \"standardized_residual_rir\")\n    for (f in key_obs) {\n      if (f %in% fr$feature_names$observation) {\n        cat(sprintf(\"- `%s`\\n\", f))\n      }\n    }\n\n    cat(\"\\n**Key Participant-Level Features (for participant profiling):**\\n\\n\")\n    key_part <- c(\"p_mean_velocity\", \"p_velocity_cv\", \"p_rir_slope\", \"p_rir_r2\",\n                  \"p_load_sensitivity\", \"p_mean_reps_per_set\")\n    for (f in key_part) {\n      if (f %in% fr$feature_names$participant) {\n        cat(sprintf(\"- `%s`\\n\", f))\n      }\n    }\n\n    cat(\"\\n**Feature Interpretation:**\\n\\n\")\n    cat(\"- **velocity_z_global**: How unusual is this velocity compared to all observations?\\n\")\n    cat(\"- **velocity_z_within_participant**: How unusual is this velocity for this specific participant?\\n\")\n    cat(\"- **velocity_residual_from_rir**: Deviation from expected velocity given the RIR\\n\")\n    cat(\"- **p_velocity_cv**: Coefficient of variation (consistency) across all observations\\n\")\n    cat(\"- **p_rir_slope**: How strongly velocity increases with RIR (steeper = more fatigable)\\n\")\n    cat(\"- **p_load_sensitivity**: How much velocity drops when load increases\\n\")\n  }\n}\n```\n\n**Key Observation-Level Features (for individual rep anomaly detection):**\n\n- `velocity_z_global`\n- `velocity_z_within_participant`\n- `velocity_z_within_set`\n- `set_position_normalized`\n- `velocity_residual_from_rir`\n- `standardized_residual_rir`\n\n**Key Participant-Level Features (for participant profiling):**\n\n- `p_mean_velocity`\n- `p_velocity_cv`\n- `p_rir_slope`\n- `p_rir_r2`\n- `p_load_sensitivity`\n- `p_mean_reps_per_set`\n\n**Feature Interpretation:**\n\n- **velocity_z_global**: How unusual is this velocity compared to all observations?\n- **velocity_z_within_participant**: How unusual is this velocity for this specific participant?\n- **velocity_residual_from_rir**: Deviation from expected velocity given the RIR\n- **p_velocity_cv**: Coefficient of variation (consistency) across all observations\n- **p_rir_slope**: How strongly velocity increases with RIR (steeper = more fatigable)\n- **p_load_sensitivity**: How much velocity drops when load increases\n\n\n#### 5.10.5 Detection Method Comparison\n\nWe compare Isolation Forest with Mahalanobis distance for participant-level anomaly detection:\n\n\n::: {#tbl-method-comparison .cell tbl-cap='Comparison of participant anomaly detection methods'}\n\n```{.r .cell-code}\nif (!is.null(lmm_results) && !is.null(lmm_results$advanced_validation)) {\n  av <- lmm_results$advanced_validation\n\n  if (!is.null(av$anomalies) && !is.null(av$anomalies$participant_method_comparison)) {\n    mc <- av$anomalies$participant_method_comparison\n\n    mc_display <- data.frame(\n      Method = mc$method,\n      `N Flagged` = mc$n_flagged,\n      Threshold = sprintf(\"%.4f\", mc$threshold),\n      `Mean Score` = sprintf(\"%.4f\", mc$score_mean),\n      `Score SD` = sprintf(\"%.4f\", mc$score_sd),\n      check.names = FALSE\n    )\n\n    format_table(mc_display)\n  }\n}\n```\n\n::: {.cell-output-display}\n\n\n|                 |   |       |       |       |\n|:----------------|--:|:------|:------|:------|\n|isolation_forest |  4|0.5113 |0.4811 |0.0624 |\n|mahalanobis      |  9|0.0821 |0.1134 |0.1209 |\n\n\n:::\n:::\n\n\n```{.r .cell-code}\nif (!is.null(lmm_results) && !is.null(lmm_results$advanced_validation)) {\n  av <- lmm_results$advanced_validation\n\n  if (!is.null(av$anomalies) && !is.null(av$anomalies$participant_method_comparison)) {\n    mc <- av$anomalies$participant_method_comparison\n\n    if_row <- mc[mc$method == \"isolation_forest\", ]\n    mah_row <- mc[mc$method == \"mahalanobis\", ]\n\n    if (nrow(if_row) > 0 && nrow(mah_row) > 0) {\n      cat(sprintf(\n        \"**Interpretation:** Isolation Forest flagged %d participants while Mahalanobis distance flagged %d. \",\n        if_row$n_flagged, mah_row$n_flagged\n      ))\n\n      if (if_row$n_flagged == mah_row$n_flagged) {\n        cat(\"Agreement between methods increases confidence in the identified anomalies.\\n\")\n      } else {\n        cat(\"Differences between methods reflect their complementary detection approaches---Isolation Forest captures non-linear patterns while Mahalanobis assumes multivariate normality.\\n\")\n      }\n    }\n  }\n}\n```\n\n**Interpretation:** Isolation Forest flagged 4 participants while Mahalanobis distance flagged 9. Differences between methods reflect their complementary detection approaches---Isolation Forest captures non-linear patterns while Mahalanobis assumes multivariate normality.\n\n\n### 5.11 Model Calibration {#sec-calibration}\n\nModel calibration assesses whether predictions match reality. A well-calibrated model should have predictions that, on average, equal observed values.\n\n\n::: {#tbl-calibration .cell tbl-cap='Model calibration metrics'}\n\n```{.r .cell-code}\nif (!is.null(lmm_results) && !is.null(lmm_results$advanced_validation)) {\n  av <- lmm_results$advanced_validation\n\n  if (!is.null(av$calibration)) {\n    cal <- av$calibration\n\n    cal_df <- data.frame(\n      Metric = c(\n        \"Calibration Slope\",\n        \"Calibration Intercept\",\n        \"R-squared\",\n        \"Mean Bias\",\n        \"Assessment\"\n      ),\n      Value = c(\n        sprintf(\"%.3f\", cal$slope),\n        sprintf(\"%.4f\", cal$intercept),\n        sprintf(\"%.3f\", cal$r_squared),\n        sprintf(\"%.4e m/s\", cal$mean_bias),\n        cal$interpretation\n      )\n    )\n\n    format_table(cal_df, col.names = c(\"Metric\", \"Value\"))\n  }\n}\n```\n\n::: {.cell-output-display}\n\n\n|Metric                |Value                                                                    |\n|:---------------------|:------------------------------------------------------------------------|\n|Calibration Slope     |1.036                                                                    |\n|Calibration Intercept |-0.0103                                                                  |\n|R-squared             |0.708                                                                    |\n|Mean Bias             |3.0791e-16 m/s                                                           |\n|Assessment            |Calibration: slope = 1.036 (excellent), intercept = -0.0103 (small bias) |\n\n\n:::\n:::\n\n\n**Interpretation**: A calibration slope close to 1.0 and intercept close to 0 indicates excellent calibration. The model's predictions are unbiased representations of reality.\n\n### 5.11 Advanced Validation Summary\n\n\n::: {#tbl-advanced-validation-summary .cell tbl-cap='Summary of advanced validation checks'}\n\n```{.r .cell-code}\nif (!is.null(lmm_results) && !is.null(lmm_results$advanced_validation)) {\n  av <- lmm_results$advanced_validation\n\n  summary_rows <- list()\n\n  # Coefficient stability\n  if (!is.null(av$coefficient_stability)) {\n    summary_rows[[1]] <- data.frame(\n      Check = \"Coefficient Stability (LOO-CV)\",\n      Result = sprintf(\"CV = %.1f%%\", av$coefficient_stability$cv_percent),\n      Status = if (av$coefficient_stability$is_stable) \"✓ Stable\" else \"⚠ Variable\"\n    )\n  }\n\n  # Model selection stability\n  if (!is.null(av$model_selection_stability)) {\n    summary_rows[[2]] <- data.frame(\n      Check = \"Model Selection Stability\",\n      Result = sprintf(\"%.0f%% agreement\", av$model_selection_stability$stability_percent),\n      Status = if (av$model_selection_stability$stability_percent >= 90) \"✓ Excellent\" else \"⚠ Variable\"\n    )\n  }\n\n  # Prediction error\n  if (!is.null(av$prediction_error_by_participant)) {\n    summary_rows[[3]] <- data.frame(\n      Check = \"Out-of-Sample Error\",\n      Result = sprintf(\"RMSE = %.3f, MAE = %.3f\",\n                       av$prediction_error_by_participant$overall_rmse,\n                       av$prediction_error_by_participant$overall_mae),\n      Status = \"✓ Acceptable\"\n    )\n  }\n\n  # Anomaly detection\n  if (!is.null(av$anomalies) && !is.null(av$anomalies$raw_data)) {\n    summary_rows[[4]] <- data.frame(\n      Check = \"Anomaly Detection (IF)\",\n      Result = sprintf(\"%.1f%% flagged\", av$anomalies$raw_data$anomaly_rate * 100),\n      Status = if (av$anomalies$raw_data$anomaly_rate < 0.10) \"✓ Normal\" else \"⚠ Review\"\n    )\n  }\n\n  # Calibration\n  if (!is.null(av$calibration)) {\n    summary_rows[[5]] <- data.frame(\n      Check = \"Model Calibration\",\n      Result = sprintf(\"Slope = %.3f, R² = %.3f\", av$calibration$slope, av$calibration$r_squared),\n      Status = if (av$calibration$slope > 0.9 && av$calibration$slope < 1.1) \"✓ Excellent\" else \"⚠ Review\"\n    )\n  }\n\n  summary_df <- do.call(rbind, summary_rows)\n  format_table(summary_df, col.names = c(\"Validation Check\", \"Result\", \"Status\"))\n}\n```\n\n::: {.cell-output-display}\n\n\n|Validation Check               |Result                    |Status       |\n|:------------------------------|:-------------------------|:------------|\n|Coefficient Stability (LOO-CV) |CV = 3.0%                 |✓ Stable     |\n|Model Selection Stability      |100% agreement            |✓ Excellent  |\n|Out-of-Sample Error            |RMSE = 0.082, MAE = 0.062 |✓ Acceptable |\n|Anomaly Detection (IF)         |5.4% flagged              |✓ Normal     |\n|Model Calibration              |Slope = 1.036, R² = 0.708 |✓ Excellent  |\n\n\n:::\n:::\n\n\n**Overall Conclusion**: The advanced validation confirms that our model is robust, well-calibrated, and generalizes to held-out participants. The coefficient stability analysis shows that no single participant drives our conclusions, and the anomaly detection identifies a small proportion of unusual observations without invalidating the overall findings.\n\n---\n\n## 6. Discussion\n\n### 6.1 Key Findings Summary\n\nThis research provides the first systematic examination of the velocity-RIR relationship for the conventional deadlift:\n\n1. **The velocity-RIR relationship exists for deadlifts**, though with greater variability than squats\n2. **Individual models substantially outperform general equations** (~2x improvement)\n3. **Prediction accuracy is acceptable** (~1.4 rep error) but should account for uncertainty\n4. **MVT varies considerably** between individuals (CV ~25%), requiring individual calibration\n5. **Day-to-day reliability is moderate**, suggesting periodic recalibration\n6. **First-rep velocity predicts set capacity** with practical accuracy\n\n### 6.2 Practical Recommendations\n\n#### For Athletes and Coaches\n\n1. **Use individual calibration**: General equations lose significant precision\n2. **Accept greater prediction uncertainty**: Target conservatively (e.g., RIR 3 if aiming for RIR 2)\n3. **Combine VBT with RPE**: Velocity is one tool, not the only tool\n4. **Recalibrate periodically**: Every 2-4 weeks or after significant training blocks\n\n#### Velocity Reference Table\n\n\n::: {#tbl-reference .cell tbl-cap='Population-Average Velocity Thresholds (Use for Initial Reference Only)'}\n\n```{.r .cell-code}\ntargets <- aggregate(mean_velocity ~ rir + load_percentage, data = data, FUN = mean)\ntargets <- reshape(targets, idvar = \"rir\", timevar = \"load_percentage\",\n                   direction = \"wide\", v.names = \"mean_velocity\")\nnames(targets) <- c(\"RIR\", \"80% 1RM\", \"90% 1RM\")\ntargets <- targets[order(-targets$RIR), ]\ntargets$`80% 1RM` <- round(targets$`80% 1RM`, 3)\ntargets$`90% 1RM` <- round(targets$`90% 1RM`, 3)\nrownames(targets) <- NULL\n\nformat_table(targets, col.names = c(\"RIR\", \"80% 1RM (m/s)\", \"90% 1RM (m/s)\"))\n```\n\n::: {.cell-output-display}\n\n\n| RIR| 80% 1RM (m/s)| 90% 1RM (m/s)|\n|---:|-------------:|-------------:|\n|   7|         0.376|         0.283|\n|   6|         0.372|         0.380|\n|   5|         0.340|         0.408|\n|   4|         0.334|         0.339|\n|   3|         0.325|         0.303|\n|   2|         0.288|         0.268|\n|   1|         0.258|         0.229|\n|   0|         0.217|         0.196|\n\n\n:::\n:::\n\n\n*These are population averages. Individual calibration will substantially improve accuracy.*\n\n### 6.3 Limitations\n\n1. **Sample size** (n=19) limits statistical power\n2. **Load range** (80-90% only) may not generalize to lighter loads\n3. **Single exercise variant** (conventional deadlift only)\n4. **Short-term reliability** (2 days) - longer-term reliability unknown\n5. **Equipment specificity** - different devices may yield different values\n\n### 6.4 Future Directions\n\n- Larger sample sizes with more diverse populations\n- Broader load ranges (60-95% 1RM)\n- Sumo and trap bar deadlift variants\n- Longer-term reliability studies\n- Integration with RPE for combined autoregulation strategies\n\n---\n\n## 7. Conclusion\n\nThis thesis research demonstrates that velocity-based training principles can be applied to the conventional deadlift, though with important caveats:\n\n1. **VBT works for deadlifts** but with more variability than other exercises\n2. **Individual calibration is essential** due to high inter-individual variability\n3. **Practical velocity tables** can guide training, but should be used alongside other autoregulation tools\n4. **Periodic recalibration** is recommended given moderate day-to-day reliability\n\nFor coaches and athletes, VBT offers an objective complement to RPE-based autoregulation for the deadlift, but should not be used as the sole prescription tool.\n\n---\n\n## References\n\n- González-Badillo, J. J., & Sánchez-Medina, L. (2010). Movement velocity as a measure of loading intensity in resistance training. *International Journal of Sports Medicine*, 31(5), 347-352.\n\n- Jukic, I., Prnjak, K., Helms, E. R., & McGuigan, M. R. (2024). Modeling the repetitions-in-reserve-velocity relationship. *Physiological Reports*, 12(5), e15955.\n\n- Koo, T. K., & Li, M. Y. (2016). A guideline of selecting and reporting intraclass correlation coefficients for reliability research. *Journal of Chiropractic Medicine*, 15(2), 155-163.\n\n- Shrout, P. E., & Fleiss, J. L. (1979). Intraclass correlations: Uses in assessing rater reliability. *Psychological Bulletin*, 86(2), 420-428.\n\n- Zourdos, M. C., et al. (2016). Novel resistance training-specific rating of perceived exertion scale measuring repetitions in reserve. *Journal of Strength and Conditioning Research*, 30(1), 267-275.\n\n---\n\n*MSc Thesis Research - Filipe Braga*\n*Supervision - João Costa*\n",
    "supporting": [
      "deadlift_study_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}