{
  "hash": "67afe2edce217ffe2f14ed5a3a64bae4",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Does Training to Failure Matter?\"\nsubtitle: \"Replicating Pelland et al. (2024) Meta-Regression on RIR and Training Outcomes\"\nauthor: \"Deadlift Study Project\"\ndate: today\n---\n\n\n\n\n## The Question Every Lifter Asks\n\n**Should I push every set to complete failure, or stop a few reps short?**\n\nThis question has practical implications:\n\n- Training to failure is **harder** and requires more recovery\n- If stopping short gives the same results, you could train more frequently\n- But if failure is necessary for gains, stopping short wastes your time\n\nPelland and colleagues tackled this question by analyzing **all available research** on the topic.\n\n## What is \"Proximity to Failure\"?\n\nResearchers use **Repetitions in Reserve (RIR)** to measure how close you are to failure:\n\n| RIR | Meaning |\n|-----|---------|\n| 0 | Complete failure - couldn't do another rep |\n| 1 | Stopped with 1 rep \"left in the tank\" |\n| 2 | Stopped with 2 reps remaining |\n| 3+ | Stopped well short of failure |\n\nThe key question: **Does RIR predict training outcomes?**\n\n## The Study Design\n\n### Meta-Regression: Analyzing All the Evidence\n\nRather than running a single study, the authors performed a **meta-regression** - a statistical technique that:\n\n1. Gathers effect sizes from many individual studies\n2. Weights each study by its precision (larger studies count more)\n3. Models how a predictor (RIR) relates to outcomes across all studies\n4. Accounts for non-independence (multiple effects from the same study)\n\n### The Data\n\n\n::: {#tbl-data-summary .cell tbl-cap='Summary of included effect sizes'}\n\n```{.r .cell-code}\ndata.frame(\n  Outcome = c(\"Strength\", \"Hypertrophy\"),\n  `Effect Sizes` = c(nrow(results$data_strength), nrow(results$data_hypertrophy)),\n  `Imputed Correlation` = c(\n    round(results$correlation_strength, 3),\n    round(results$correlation_hypertrophy, 3)\n  ),\n  check.names = FALSE\n) |> format_table()\n```\n\n::: {.cell-output-display}\n\n\n|            |    |      |\n|:-----------|---:|-----:|\n|Strength    | 243| 0.866|\n|Hypertrophy | 140| 0.875|\n\n\n:::\n:::\n\n\nThe analysis included **243 strength effect sizes** and **140 hypertrophy effect sizes**.\n\n## The Key Finding: Strength vs Hypertrophy Differ\n\n### Strength Gains\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstr_mod <- results$strength_model\nstr_rir_b <- str_mod$b[\"avg.rir\", 1]\nstr_rir_p <- str_mod$pval[rownames(str_mod$b) == \"avg.rir\"]\n```\n:::\n\n\nFor **strength gains**, RIR showed:\n\n- **Coefficient**: 0.0018 (effect per 1 RIR increase)\n- **P-value**: 0.784\n- **Interpretation**: Not statistically significant\n\n::: {.callout-note}\n## What This Means for Strength Training\nTraining closer to failure does **not** produce significantly greater strength gains. You can stop 2-3 reps short and still get similar strength improvements.\n:::\n\n### Muscle Hypertrophy\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhyp_mod <- results$hypertrophy_model\nhyp_rir_b <- hyp_mod$b[\"avg.rir\", 1]\nhyp_rir_p <- hyp_mod$pval[rownames(hyp_mod$b) == \"avg.rir\"]\n```\n:::\n\n\nFor **muscle growth**, RIR showed:\n\n- **Coefficient**: -0.0193 (effect per 1 RIR increase)\n- **P-value**: 0.004\n- **Interpretation**: Statistically significant and negative\n\n::: {.callout-important}\n## What This Means for Muscle Building\nTraining closer to failure **does** produce greater muscle hypertrophy. Each RIR reduction (getting closer to failure) is associated with slightly more muscle growth.\n:::\n\n## Visualizing the Difference\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create comparison data\ncomparison_df <- data.frame(\n  Outcome = c(\"Strength\", \"Hypertrophy\"),\n  Estimate = c(str_rir_b, hyp_rir_b),\n  SE = c(str_mod$se[rownames(str_mod$b) == \"avg.rir\"],\n         hyp_mod$se[rownames(hyp_mod$b) == \"avg.rir\"]),\n  Significant = c(\"No\", \"Yes\")\n)\n\ncomparison_df$Lower <- comparison_df$Estimate - 1.96 * comparison_df$SE\ncomparison_df$Upper <- comparison_df$Estimate + 1.96 * comparison_df$SE\n\nggplot(comparison_df, aes(x = Outcome, y = Estimate, color = Significant)) +\n  geom_point(size = 4) +\n  geom_errorbar(aes(ymin = Lower, ymax = Upper), width = 0.2, linewidth = 1) +\n  geom_hline(yintercept = 0, linetype = \"dashed\", color = COLORS$gray) +\n  scale_color_significance() +\n  labs(\n    x = NULL,\n    y = \"RIR Coefficient (Hedge's g per RIR)\",\n    title = \"Effect of RIR on Training Outcomes\",\n    subtitle = \"Negative values = closer to failure is better\"\n  )\n```\n\n::: {.cell-output-display}\n![RIR Effect on Strength vs Hypertrophy Outcomes](01_pelland_meta_regression_files/figure-html/fig-comparison-1.png){#fig-comparison width=100%}\n:::\n:::\n\n\nThe figure shows:\n\n- **Strength** (gray): Confidence interval includes zero - no significant effect\n- **Hypertrophy** (red): Entirely below zero - significant negative effect\n\n## Replication Validation\n\nOur replication matches the published findings:\n\n\n::: {#tbl-validation .cell tbl-cap='Replication vs Published Results'}\n\n```{.r .cell-code}\ndata.frame(\n  Outcome = c(\"Strength\", \"Hypertrophy\"),\n  `Paper Claim` = c(\n    \"CI contains null (not significant)\",\n    \"Negative slope, CI excludes null\"\n  ),\n  `Our Result` = c(\n    paste0(\"p = \", format_p(str_rir_p), \" (not significant)\"),\n    paste0(\"b = \", round(hyp_rir_b, 3), \", p = \", format_p(hyp_rir_p))\n  ),\n  Match = c(\"Yes\", \"Yes\"),\n  check.names = FALSE\n) |> format_table()\n```\n\n::: {.cell-output-display}\n\n\n|            |                                   |                            |    |\n|:-----------|:----------------------------------|:---------------------------|:---|\n|Strength    |CI contains null (not significant) |p = 0.784 (not significant) |Yes |\n|Hypertrophy |Negative slope, CI excludes null   |b = -0.019, p = 0.004       |Yes |\n\n\n:::\n:::\n\n\n## Practical Implications\n\n### For Strength Training\n\n1. **Stop 2-3 reps short** of failure on most sets\n2. Reserve failure training for testing or peaking phases\n3. This allows higher frequency and volume\n\n### For Muscle Building\n\n1. **Train closer to failure** for optimal hypertrophy\n2. 0-2 RIR appears beneficial\n3. Balance this against recovery demands\n\n### The Trade-Off\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Conceptual illustration\nrir_seq <- 0:5\nconcept_df <- data.frame(\n  RIR = rep(rir_seq, 2),\n  Outcome = rep(c(\"Strength Gain\", \"Muscle Growth\"), each = length(rir_seq)),\n  Benefit = c(\n    rep(1, length(rir_seq)),  # Strength: flat line (no effect)\n    1 - 0.15 * rir_seq        # Hypertrophy: decreasing line\n  )\n)\n\nggplot(concept_df, aes(x = RIR, y = Benefit, color = Outcome)) +\n  geom_line(linewidth = 1.5) +\n  geom_point(size = 3) +\n  scale_x_reverse() +\n  scale_color_outcome() +\n  labs(\n    x = \"Repetitions in Reserve (RIR)\",\n    y = \"Relative Benefit\",\n    title = \"Conceptual Model: RIR Effects by Outcome\",\n    subtitle = \"Lower RIR = closer to failure\"\n  )\n```\n\n::: {.cell-output-display}\n![The Strength-Hypertrophy Trade-off with RIR](01_pelland_meta_regression_files/figure-html/fig-tradeoff-1.png){#fig-tradeoff width=100%}\n:::\n:::\n\n\n## Methods Summary\n\n### Statistical Model\n\nWe used a multi-level meta-regression with:\n\n- **Fixed effects**: RIR, load, volume equating, duration, training status\n- **Random effects**: Nested structure (~1|study/group/obs)\n- **Effect sizes**: Hedge's g (bias-corrected standardized mean change)\n- **Estimation**: REML with t-distribution tests\n\n### Pre-Post Correlation Imputation\n\nMissing pre-post correlations were imputed via meta-analysis:\n\n- Strength: r = 0.866\n- Hypertrophy: r = 0.875\n\n## References\n\n::: {#refs}\n:::\n\n## Source\n\n- Original paper: [Pelland et al. (2024) Sports Medicine](https://link.springer.com/article/10.1007/s40279-024-02069-2)\n- Data and code: [OSF Repository](https://osf.io/7knsj/)\n",
    "supporting": [
      "01_pelland_meta_regression_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}